### ISSUE TITLE
Placement of objects is offset from the cursor

### ISSUE THREAD

**Issue by BobdaBiscuit** [space-wizards/RobustToolbox#100]
When you go to place things the object is often offset from your cursors actual position, and the tile select modes select tiles that your cursor is not over.

https://www.youtube.com/watch?v=I-zs6gEmZDw displays the issue.

I THINK it's from your characters position, with the offset shifting based on my dudes position within a tile.

**Comment by psykzz** [comment]
Fixed by #146
