### ISSUE TITLE
You can see different distances at different resolutions

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/RobustToolbox#1001]
At higher resolutions you can see further, which means that you'll get slightly different feel / view at different resolutions. At 2K this is annoying compared to 1920x1080 since everything is smaller. Haven't tested at 4K but I'd imagine it's pretty bad at that res. I think a good fix for this would be to have the camera dynamically zoom based on window resolution. Could be an option if not everyone wants this.

**Comment by PJB3005** [comment]
First step in solving this is deciding what default view size we should have.

**Comment by RemieRichards** [comment]
SS13 was 15x15 tiles, not a terrible starting point, but we have the luxury of being able to widen that without the game shitting itself completely now, so maybe a little more.

**Comment by metalgearsloth** [comment]
My 4k monitor sees about 60 x 32 tiles which is more or less the whole station currently.

**Comment by azerty999** [comment]
there should be option to zoom in and out like unitystation has

**Comment by PJB3005** [comment]
Zooming out is a big no-no because we need to keep this consistent so that people with a 4k monitor don't have a massive advantage (though maybe some stuff with genetic powers etc could be neat here).

Zooming in I feel has little uses since you'd put yourself at such a stupid huge disadvantage, but OTOH I guess it could be useful when testing/keeping a small game window open as observer.

**Comment by azerty999** [comment]
first of all you wouldnt see whole station, the view is blocked by walls and stuff, second enemies coming from bottom of the screen have advantage because my view is blocked by ui, if i could zoom out, i could both see the ui and my enemies

**Comment by FlanOfFlans** [comment]
Seems like it'd be easiest to restrict how far you can see in a given direction, similar to current shadow mechanics but not based on lighting information, and allow players to zoom in/out as they please on top of that. That way, we mitigate problems with UI blocking valuable information, without giving players on large monitors an advantage. Also, freely zooming would make security cameras (including AI) way more usable, when/if that's implemented.

**Comment by PJB3005** [comment]
> first of all you wouldnt see whole station, the view is blocked by walls and stuff

Large hallways exist and are an important factor of combat.

> if i could zoom out, i could both see the ui and my enemies

That's a good idea yeah, but I wouldn't personally classify that as "zooming out". That's making your viewport smaller.

**Comment by azerty999** [comment]
yeah large hallways exist,i think unitystation made like view distance after 15 tiles you see only black

**Comment by PrPleGoo** [comment]
Zoom functionality would be very useful for ghosts and admins.

**Comment by PJB3005** [comment]
> Zoom functionality would be very useful for ghosts and admins.

Oh, absolutely. When I'm talking about distances and such observers are completely out of the question. The easier the round is to observe the better.

**Comment by snowsignal** [comment]
I'll try to fix this issue. I think 15x15 is a good starting point for view distance.

**Comment by snowsignal** [comment]
You can unassign me from this issue, I've been working on other things and have a long way to go with learning OpenGL before I'm ready to work with the rendering code.

**Comment by gradientvera** [comment]
Fixed now with the viewport improvements.
