### ISSUE TITLE
Implement Multithreading

### ISSUE THREAD

**Issue by snowsignal** [space-wizards/RobustToolbox#1032]
Right now, `EntityManager` runs systems one at a time on a single thread. This does not take advantage of modern processors. The great thing about ECS architecture is that its possible to know exactly what resources a system will use: therefore, running multiple systems in parallel is not as tricky as it would be with other game engine architectures.

Multithreading will be opt-in: a system will be able to implement an interface, such as `IParallelEntitySystem`, that will make it into a multithreaded system. If a system is multithreaded, it basically tells the EntityManager "hey, if no other system is using the resources I'm using, you can run me in a separate thread without any problems."

Gradually, we will be able to convert more and more systems to be multithreaded. If we can run multiple computationally-expensive systems simultaneously, the increase in performance will hopefully be noticeable. 

Of course, in order for all of this to work, all components and managers must be locked behind mutexes. My plan is to have managers and components use mutexes internally, and then expose both a 'single-thread' and 'multiple-thread' API. Synchronous systems won't have to change any of their code, but if you're writing a multithreaded system the expectation is you will use thread-safe getters, i.e. `Entity.GetComponentMutex` instead of `Entity.GetComponent`.

**Comment by PJB3005** [comment]
The concern with requiring thread-safe getters is that lock contention and such could cause a serious performance hit, on top of other synchronization stuff. I feel like right now we'll probably get *reduced* performance from trying to implement multithreading, because we really aren't hurting for single-threaded performance yet (and if we were, we still have a lot of room to optimize).

**Comment by snowsignal** [comment]
> The concern with requiring thread-safe getters is that lock contention and such could cause a serious performance hit, on top of other synchronization stuff. I feel like right now we'll probably get _reduced_ performance from trying to implement multithreading, because we really aren't hurting for single-threaded performance yet (and if we were, we still have a lot of room to optimize).

Locks are simply a safety measure: the dispatcher will run multithreaded systems in such a way that resources will never be double-borrowed. The only case in which lock contention would occur is if a system gets a resource that was not included in its EntityQuery and another system tries to access that resource at the same time. My plan is to log a warning the first time lock contention occurs for a given component, so that programmers can diagnose the issue.

I also want to rewrite EntityQuery to be more flexible and allow subqueries, intersections, etc. My inspiration for all this multi-threaded stuff is a very powerful multi-threaded ECS framework written in Rust: https://github.com/amethyst/specs.

**Comment by PJB3005** [comment]
Yeah I'm familiar with better ECS approaches like specs.

There is still the concern of startup time of the extra job threads. I know PLINQ has a really high startup latency making it not worth it for low volume use cases (like ours, for the mean time).

**Comment by snowsignal** [comment]
> Yeah I'm familiar with better ECS approaches like specs.
> 
> There is still the concern of startup time of the extra job threads. I know PLINQ has a really high startup latency making it not worth it for low volume use cases (like ours, for the mean time).

That's true. I was thinking of probably rolling our own query system, should we decide to use multithreading.

**Comment by metalgearsloth** [comment]
Physics and PVS (2 of the most expensive things in SS14) both use multi-threading so we probably don't need a general issue given 99% of systems are fine single-threaded.

The only other thing that might be a contender is gastileoverlay or atmos (though the latter kills the vera).
