### ISSUE TITLE
GUIObject with focus does not stop background keybindings

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#104]
When you are searching within a text box we do not handle focus correctly.

**Comment by PJB3005** [comment]
One really annoying issue with SFML that I've found is that because `TextEntered` is a separate event, preventing a key down from happening before a caught textentered is hard as hell. But I don't think you can easily fix this either.

**Comment by psykzz** [comment]
We could always disable the TextEntered Event and handle it ourselves.
Would suck, but would mean we get the control we need.

**Comment by PJB3005** [comment]
Yep we'd probably be dealing with incorrect text entry bugs for ages.

**Comment by PJB3005** [comment]
Can this be closed @psykzz?, the replacement for #128 got merged.

**Comment by Acruid** [comment]
Fixed in the referenced UI Rework.
