### ISSUE TITLE
Bullets cause an exception due to gravity check

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/RobustToolbox#1056]
Gravity check for friction here:
https://github.com/space-wizards/RobustToolbox/blob/a72dd8c85bc1903ef98e709fc1a735bd5e667bdc/Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs#L117

Gets the CollidableComponent of the bullet:
https://github.com/space-wizards/RobustToolbox/blob/a72dd8c85bc1903ef98e709fc1a735bd5e667bdc/Robust.Server/GameObjects/EntitySystems/PhysicsSystem.cs#L209

Which was deleted in the previous loop where the gravity check is. [ProjectileComponent.cs#L93](https://github.com/space-wizards/space-station-14/blob/15ba4f50a4cc3ac4eb43b171dfaa5b88999655bd/Content.Server/GameObjects/Components/Projectiles/ProjectileComponent.cs#L93)

```cs
if (collidedwith.Count > 0)
{
    Owner.Delete();
}
```

Could do a temporary fix by checking for deleted entity, but #1037 is almost done.

**Comment by snowsignal** [comment]
Cool, I'll add that check in for #1037

**Comment by ghost** [comment]
Should be fixed now?

**Comment by snowsignal** [comment]
Yeah, it should be.
