### ISSUE TITLE
DrawingHandleWorld goes skewiff when firing lasers

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1065]
Whenever firing a laser anything that uses DrawingHandleWorld will move:

![image](https://user-images.githubusercontent.com/31366439/82694490-b0076400-9ca6-11ea-8177-e58fd2f96179.png)

On master branch if you have the spawn entity icon up and fire a laser it will distort.

![image](https://user-images.githubusercontent.com/31366439/82694654-f957b380-9ca6-11ea-96d8-b8265d7cef94.png)

(It's easier to do when I full-screen on my 4k monitor)

I assume the problem is in EffectSystem somewhere as from memory it only ever happens with the content hitscan weapon.

**Comment by ComicIronic** [comment]
Yeah, this happens because the effect system, to draw a rotated texture (like laser fire), rotates the `DrawingHandleWorld`, including everything on it. I'll have a go at fixing this.
