### ISSUE TITLE
Make it possible to specify cvars over environment variables.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1075]
Right now watchdog API tokens are handed to the server over command line arguments. This means they can show up in listings like `ps`, exposing the tokens. Environment variables don't have this issue I believe.

**Comment by 20kdc** [comment]
Did a little test locally (Ubuntu 19.10, Linux 5.3.0-51-generic)
Environment variables *can* be shown by, say, `ps axe`, but I can't see the environment variables of a process owned by any other user (as a non-root user) (tested targets: root, & a separate non-root user).
Not a 100% guarantee of safety but definitely more secure than command-line arguments.

**Comment by PJB3005** [comment]
If you're the same user as the server process then you can just do other malicious stuff so it doesn't really matter.

**Comment by ComicIronic** [comment]
Should cvars overwritten by environment variables be saved to the config file? I feel like they shouldn't.

**Comment by PJB3005** [comment]
They shouldn't. CVars specified via command line are handled separately already and the same system could be used.
