### ISSUE TITLE
The problem with Kestrel inside StatusHost

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1076]
#966 moved the `StatusHost` to using Kestrel instead of the previous system. The problem is that the standalone Kestrel packages we rely on are no longer maintained and will not get updated (Microsoft dropped them after Core 3...)

I'm not too fond of using an unmaintained HTTP handler like this, naturally.

Some solutions:
1. Move to a different HTTP server implementation.
2. Ship ALL of ASP.NET Core with the server (please dear god no).
3. Rely on the ASP.NET Core runtime being installed on the system (please no).

**Comment by Tyler-IN** [comment]
The PR I posted ships the minimal amount (3MB) of ASP.NET Core 3.1 needed, requires ASP.NET Core installed on the _building system._

**Comment by PJB3005** [comment]
Fixed by #1423
