### ISSUE TITLE
Text macros for "the"?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1083]
To distinguish between proper/improper nouns, really.

One thing to consider is how the data of proper/improper should be stored. In BYOND this is done with a special character and a macro. We could do the same sort of by using the private-use area of Unicode. There are obvious concerns with sanitization, although they may not be as bad (not using an actual text character like BYOND did, because we have proper Unicode support).

**Comment by Hugal31** [comment]
Another solution would be to add a ~~Noun~~GrammarComponent, or whatever, that is in charge of storing data relative to the grammar macros.

**Comment by ComicIronic** [comment]
This could be done in the form of `IGenderable` - we could implement a new interface for getting proper/improper status, stick components on things, and add a new text macro. That seems saner than special text bits.

**Comment by PJB3005** [comment]
My thought for "special text bits" was the same as the presumable reasoning for BYOND, if you change the name of an object you wouldn't have to copy grammar information explicitly (which seems like a pain?).

Then again I suppose this is a rare operation and it may just be better to have a high-level handler that does all this instead.
