### ISSUE TITLE
Any object near by you when you click ANYWHERE will be triggered as if you clicked on it properly

### ISSUE THREAD

**Issue by BobdaBiscuit** [space-wizards/RobustToolbox#109]
Rabbit hole starts at GameScreen.cs#666 MouseDown()

Basically from my tests as long as you are in range of the clicked object you will trigger it regardless of where you actually clicked.

I went down the rabbit hole and I think the click check for if you actually hit anything literally doesn't exist.

At the bottom of the rabbit hole in (Animated  too) SpriteComponent.cs#177 the necessary check literally doesn't exist.

**Comment by Acruid** [comment]
I cannot reproduce this issue, so I am assuming it was fixed in the last 8 months. I am considering this fixed.
