### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#110]
Is there any chat systems used for discussions?
Slack / Discord / IRC  or something else

**Comment by PJB3005** [comment]
`irc.rizon.net#spacebus` for an IRC channel. I set up a Discord relay to the /vg/station coding Discord server where we've got a remake specific channel that everybody uses.

https://discord.gg/29WZwgt

**Comment by psykzz** [comment]
Works for me.
