### ISSUE TITLE
RSIs don't fail to load if they have duplicate states defined in their JSON.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1134]
Multiple RSIs in content have this and it's currently going silent.

**Comment by ComicIronic** [comment]
What's the desired behaviour? Error logging? If sprite code is meant to be resilient, which it mostly is ATM, this seems to be correct as-is.

**Comment by PJB3005** [comment]
Sprite component != RSI loading. This should be treated as the JSON being malformed and the entire RSIResource refusing to load.
