### ISSUE TITLE
EffectSystem throws if grid gets deleted while effects are playing on it.

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1157]
Stacktrace:
`Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '2' was not present in the dictionary.`
`  at System.Collections.Generic.Dictionary2.get_Item(TKey key)`
`  at Robust.Shared.Map.MapManager.GetGrid(GridId gridID) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Map\MapManager.cs:line 496`
`   at Robust.Shared.Map.GridCoordinates.ToMapPos(IMapManager mapManager) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Shared\Map\Coordinates.cs:line 97`
`   at Robust.Client.GameObjects.EffectSystem.Effect.Update(Single frameTime) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\EffectSystem.cs:line 248`
`   at Robust.Client.GameObjects.EffectSystem.FrameUpdate(Single frameTime) in D:\ProgrammingProjects\space-station-14\RobustToolbox\Robust.Client\GameObjects\EntitySystems\EffectSystem.cs:line 79`

I blew up a grenade and while the effect was still present I used `restartround` which gave this exception. Looks like because the new round has a new grid and the queued effect is on the old (removed) grid it caused it.

**Comment by Acruid** [comment]
Can't reproduce, assumed to be fixed because this bug was before the EntityCoordinates epoch.
