### ISSUE TITLE
Grid-local DynamicTrees and GridPosition caching.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1159]
Right now we have multiple `DynamicTree`s indexing positions of entities and AABBs. These trees implicitly cache the world position of the entities inside them (because they have to index them) and this is a problem for moving large grids: if you move the grid, ALL the entities *on* the grid have to have their dynamic tree updated, which is too expensive.

Furthermore, a frankly ridiculous amount of time is spent calculating `WorldPosition`s for various operations like rendering and *still* `DynamicTree`, because doing a non-approximate collision check resolves the `WorldMatrix` of the entity in question which *might as well be* a `WorldPosition` recalculation. This is not cached and expensive.

So on one side, we already *have* the data cached but are not using it efficiently, on the other side keeping it cached is too expensive...

I hereby propose that we make all dynamic trees relative to *grids*, then allow `TransformComponent` to cache `GridPosition`. The advantage of this is that when moving grids themselves, nothing expensive has to get recalculated for all the entities ON those grids. We can then use `GridPosition` caching to make various operations significantly less expensive aswell.

cc @Acruid @Tyler-IN

**Comment by ComicIronic** [comment]
> I hereby propose that we make all dynamic trees relative to grids, then allow TransformComponent to cache GridPosition.

When you describe it like this I'm surprised it doesn't do that already.

**Comment by RemieRichards** [comment]
> We can then use GridPosition caching **_to make various operations significantly more expensive_** aswell.

Sounds like a bad idea then! :P

**Comment by Tyler-IN** [comment]
> When you describe it like this I'm surprised it doesn't do that already.
I think we discussed and agreed on this ages ago, I think it should also apply to containers (with low growth tuning) as well in the future.

**Comment by metalgearsloth** [comment]
It's finally done.
