### ISSUE TITLE
Melee Hit Audio Fails To Play On Hit That Destroys Entity

### ISSUE THREAD

**Issue by SoulSloth** [space-wizards/RobustToolbox#1191]
Reproduction steps:
1. Destroy an entity with punches or any melee attack
Expected Result: The hit sound plays as normal
Actual: The client fails to find the entity that has been destroyed and logs an error: Server tried to play audio file /Audio/Weapons/genhit1.ogg on entity ... which does not exist.

**Comment by Acruid** [comment]
Cannot reproduce, seems resolved.
