### ISSUE TITLE
PVS needs increased size for large objects like lights

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1198]
Object like lights have large visual areas of effect and PVS does not handle this, meaning that even with correct viewport size you can easily see outdated data for a light before the server starts sending updates for it.

**Comment by Tyler-IN** [comment]
Lights ranges need to be detectable or have zones of effect that have shapes that can be tested against, increasing PVS range will never sufficiently accomplish this without becoming too large to have any effect. I already reported that.

**Comment by PJB3005** [comment]
That is what I meant though yes admittedly the issue title is not very clear.

**Comment by metalgearsloth** [comment]
Could we add an interface and add it to certain components like PointLight and have a separate BVH that stores anything that needs different bounds for PVS purposes? Though it would make the query slower...
