### ISSUE TITLE
Provide wrapper C executable to enable NVIDIA Optimus.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1201]
To use the dedicated NVIDIA GPU on Optimus systems, [you need to export the `NvOptimusEnablement` symbol from the executable](https://docs.nvidia.com/cuda/optimus-developer-guide/index.html).

We cannot do this easily because, well, .NET. The solution is to make a tiny C executable that exports it and then hosts CoreCLR to run the game, but it's still a bit annoying.

**Comment by Acruid** [comment]
https://github.com/lmagder/OptimusEnablementNET

Maybe this is better?

**Comment by PJB3005** [comment]
That solution is from 2014 and predates .NET Core. That *was* a valid solution on .NET Framework because Framework used the same `.exe` for the managed assembly and the executable. This is no longer the case for .NET Core however. (The `.exe` is only a preset loader which loads the managed assembly with the same name).

**Comment by PJB3005** [comment]
https://github.com/AaronRobinsonMSFT/DNNE seems like it's what we want.

**Comment by gradientvera** [comment]
We now force-load `nvapi64.dll` which is much more convenient and does the same thing without needing a C wrapper executable.
