### ISSUE TITLE
Don't use NaNs to hide PVS movers.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1210]

**Comment by moonheart08** [comment]
using a flat NaN still does have some advantages here for network usage. What could be done is to make use of [NaN Boxing](https://sean.cm/a/nan-boxing)

Also why the heck is this a normal NaN and not a signalling NaN :T
EDIT: Ok apparently C# doesn't have the concept of a signalling NaN (or rather, using it may lead to interesting behavior if it actually does anything at all). Scratch that

**Comment by Tyler-IN** [comment]
No reason specified as to why not to use NaNs. No big deal.

**Comment by PJB3005** [comment]
NaNs have many issues like breaking audio playback. This requires extremely ugly hacks in the audio system and other ass pains. If we could just move the hidden entities to nullspace it'd "just work".

**Comment by PJB3005** [comment]
This caused an *extremely* hard to track down bug in DynamicTree, corrupting its internal state.

*sigh*

**Comment by Acruid** [comment]
This needs a solution that does not involve artificially desyncing the network state of the TransformComponent on the client. The true solution to this is going to be actually deleting the entity on the client, or if we need to cache the entity for perf reasons, make it inaccessible like the paused flag.

It is not feasible for the server to store the LastSeenState of 24K ents for all 300 clients. Without this piece of info, the only baseline the server can use when delta compressing a mover that enters PVS for an arbitrary client is the prototype. Anchored ents (https://github.com/space-wizards/RobustToolbox/pull/1829, https://github.com/space-wizards/RobustToolbox/pull/1845) are about 80% of the total ents in view, and they are static/nonmoving (therefore don't enter/leave pvs) so they are not considered in this problem. Most of the mover ents are going to be items, and most of those are currently inside containers, so hiding container contents (https://github.com/space-wizards/RobustToolbox/issues/1432) should be implemented before considering solutions to this problem.

**Comment by metalgearsloth** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/pull/2247 (assuming no reverty)

**Comment by PaulRitter** [comment]
> This needs a solution that does not involve artificially desyncing the network state of the TransformComponent on the client. The true solution to this is going to be actually deleting the entity on the client, or if we need to cache the entity for perf reasons, make it inaccessible like the paused flag.
> 
> It is not feasible for the server to store the LastSeenState of 24K ents for all 300 clients. Without this piece of info, the only baseline the server can use when delta compressing a mover that enters PVS for an arbitrary client is the prototype. Anchored ents (#1829, #1845) are about 80% of the total ents in view, and they are static/nonmoving (therefore don't enter/leave pvs) so they are not considered in this problem. Most of the mover ents are going to be items, and most of those are currently inside containers, so hiding container contents (#1432) should be implemented before considering solutions to this problem.

for the record, i solved this by moving entities to nullspace & remembering the mapid they were on. when they reenter pvs, i simply move them back to their previous map & apply all the states.
