### ISSUE TITLE
Provide explicit FloatMath.Clamp implementations for integer types.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1224]
Contradictory as it may sound right now `FloatMath.Clamp` already works via integer types due to the `Clamp<T>(...) where T : IComparable<T>` implementation. These are less efficient than a manual implementation though so this should provide some nice savings.

**Comment by GalacticChimp** [comment]
This was already fixed by you @PJB3005 , might as well close this
