### ISSUE TITLE
FrameUpdate gets called with 0 dt when paused.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1226]
For some reason the implementation of `IGameTiming.FrameTime` returns zero when out of simulation and paused. This causes `FrameUpdate()` to get called with 0 dt and as such UI animations to break when in the main menu. 

@Acruid

**Comment by Acruid** [comment]
Working as expected, use `IGameTiming.RealFrameTime` for UI animations.
