### ISSUE TITLE
Saving server config causing stackoverflow

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#123]
Typing `saveconfig` will trigger
```
System.StackOverflowException was unhandled
Message: An unhandled exception of type 'System.StackOverflowException' occurred in sfmlnet-system-2.dll
```

https://github.com/space-wizards/space-station-14/blob/master/SS14.Server.Services/Configuration/ConfigurationManager.cs#L52 looks to be the breaking line.

**Comment by ComicIronic** [comment]
Weird one. Nothing in PersistentConfiguration seems like it would be causing a recursion issue - only value types and strings. Maybe it's just being called too deeply? What's the stack like leading up to the method being called?

**Comment by PJB3005** [comment]
The error is in `sfmlnet-system-2.dll` so it's probably the `vector2i` in the `PersistentConfiguration` that's causing it.

Thanks. SFML.

**Comment by Acruid** [comment]
The configuration system is now completely replaced, and does not use Vector2i. The underlying issue of SFML crashing when accessing the Vector2i is still an issue.  Does this need to be closed?

**Comment by PJB3005** [comment]
Can be closed.
