### ISSUE TITLE
Dirty() for owner player only

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1255]
Or an equivalent.

Some content-side components such as statuseffects and overlays only need to send their data to the player attached to the entity (to reduce bandwidth and reduce data exposed for cheating) rather than every single player in PVS range. Currently this is boilerplated in where needed.

**Comment by PJB3005** [comment]
It would probably be best to have an overload of `GetComponentState` that takes in the `IPlayerSession` it's being generated for.

**Comment by metalgearsloth** [comment]
How about a bool on a component that the alternative GetComponentState method should be called and pvs then chooses which one to use?

**Comment by metalgearsloth** [comment]
Done in https://github.com/space-wizards/RobustToolbox/pull/1569
