### ISSUE TITLE
Subtick Movement and Friction

### ISSUE THREAD

**Issue by Acruid** [space-wizards/RobustToolbox#1261]
## How to reproduce
* Execute `cvar net.tickrate 2` on the server.
* Quickly tap a movement key so that it is pressed and released within a tick.
* Watch the player move forward and rubberband backwards because of a prediction error.

## Details
Right now on the server subtick movement is handled by changing the movespeed/velocity of the player each tick so that the impulse is correct each tick. The idea is that very quick subtick movements will generate small movement speeds like 0.2m/s for that tick. The problem is these very small speeds are being completely negated by friction on the server.

The server currently simulates all onground bodies as sliding. For a player, this would be like him laying on the floor and pushing himself around with his legs. Humans stand upright and invented wheels to reduce friction with the ground. It seems like the friction of the body needs to be set very close to 0 while the player is standing to better model this.

## Resolution
- [ ] Determine why there is a prediction error at all. All of the physics is ran in a shared context, so why are we seeing prediction errors to begin with? My guess is that because the player movement is predicted at ~60hz framerate, and the server is predicted at 2tps, there is something wrong with the movement accumulation on the client, or the physics math on the server.

- [ ] Set the player's friction to 0 in the movement controller while standing. This will cause the kinematic impulses of moving to not be effected by friction, and the movement controller can model the player bracing themselves against outside forces. When the player is down from slip/decompression, set the friction to normal values so he slides across the floor as expected.

**Comment by metalgearsloth** [comment]
I think this is okay now right?

**Comment by PJB3005** [comment]
There are certainly still mispredicts with movement at low tickrates but not remotely as severely as there would if it was due to friction (this issue) so... probably fine?

**Comment by Acruid** [comment]
This is outdated, I'm closing it. Someone can debug any current mispredicts and write up a new issue.
