### ISSUE TITLE
Potential for nested entity components in entity templates

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#127]
For example
```
<MoverComp>
    <TransformComp></TransformComp>
    <VelocityComp></VelocityComp>
    <DirectionComp></DirectionComp>
</Mover>
```

This could ultimately get flattened out in code, so that we don't need to change many internals.

**Comment by Acruid** [comment]
This issue is outdated. If we need this functionality someone can create a new issue explaining    what this is used for and why someone should code it in more detail.
