### ISSUE TITLE
YML prototype schema design.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#131]
I will make a page on the repo wiki shortly.

**Comment by PJB3005** [comment]
Draft 1: https://github.com/space-wizards/space-station-14/wiki/YAML-prototype-schema-prototype

Please give feedback.

**Comment by psykzz** [comment]
Just to be clear, with this we can create "generics" and use those to power our entities?
Like for example. Generic Door, and then have space door, normal door, hanger door ect.

Otherwise, all good for me

**Comment by PJB3005** [comment]
@psykzz should be doable since single inheritance is available.

**Comment by PJB3005** [comment]
I want some opinions on the exact best way to implement the inheritance system.

What I currently have is a simple `YamlMappingNode` (aka a dict for the YAML for a component) for each component, but this obviously plays very poorly with inheritance.

I'm thinking maybe have a dictionary of YAML nodes, allow the individual nodes to be inherited but only if a node with the same name does not already exist. Then we can probably add custom logic later.

Does that sound fair?

**Comment by ZoldorfTheWizard** [comment]
Merged in #211

**Comment by PJB3005** [comment]
Not done yet though, I forgot the data field.
