### ISSUE TITLE
C# extension assembly loading

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#133]
An `Assembly.LoadFrom("SS14.Server.Content.dll")` should probably enough.

Types will be discovered through reflection over the assembly.

**Comment by ZoldorfTheWizard** [comment]
Is this good to close now that you implemented DI?

**Comment by PJB3005** [comment]
Not yet,  there's still some other things to work on. Namely making the
loaded assembly have an automatic entry point to add IoC things with and
moving client side loading to the connection code.

**Comment by PJB3005** [comment]
We need an entry point into the DLL to allow things such as IoC to be registered. I'm thinking just making this:
```cs
namespace SS14.Shared.Interfaces.Content
{
    public interface IEntryPoint
    {
        /// <summary>
        /// Gets called on a new instance when the assembly is loaded.
        /// </summary>
        void Enter();
    }
}
```

This sound good?

**Comment by Acruid** [comment]
https://github.com/space-wizards/space-station-14/pull/295 covers this feature. This issue should be good to close.
