### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#135]
This is something that's been on my mind for a while: should we have localization?

It may be hard to uphold in the SS13 ecosystem, but if we can I think we should go for some engine-level support.

**Comment by ComicIronic** [comment]
What would the localisation be for, user content? There's no harm in allowing it. More generally, we can make a system where prototype loading changes based on some runtime options, and then allow the schema to support it, and localisation should fall out.

**Comment by N3X15** [comment]
Localization is much easier to implement earlier in development, so it'd be good to get on it ASAP.  gettext is standard, but not sure if it has a C# counterpart.  Factorio also has a nice system.

**Comment by RemieRichards** [comment]
There's NGettext for gettext + C#, open source under MIT.

**Comment by psykzz** [comment]
Ton of free "crowd sourcing" sites will let us setup a connection with github and their systems to dynamically update loc.

**Comment by psykzz** [comment]
Localization should come from the content repo.
We should just use whatever strings are provided, or default to ours if none available.

**Comment by PJB3005** [comment]
I am interested in doing this semi-soonish.

The problem is I'm not sure whether we want to use gettext or handroll something like Factorio did.

The problem I have with gettext is that I fear that it might suck to use with prototypes, but I don't have any experience to know for sure. I also think gettext's approach of "translations are identified by english" feels *off* and I like Factorio's approach better, but at the same time I understand how being able to focus on English is easier on development.

**Comment by PJB3005** [comment]
ddbeccdb8c510953a2abdb30a456fd6810bc39ca done.
