### ISSUE TITLE
Movement isn't constant

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1372]
Possibly related to Acruid's issue #1261 

tl;dr is that if you're moving in a constant direction your speed oscillates up and down 0.05 units which I don't think it should do?

```
[DEBG] root: LinearVelocity dirty as (7.0282106, 0)
[DEBG] root: LinearVelocity dirty as (6.971044, 0)
[DEBG] root: LinearVelocity dirty as (7.0282106, 0)
[DEBG] root: LinearVelocity dirty as (6.971044, 0)
[DEBG] root: LinearVelocity dirty as (7.0282106, 0)
[DEBG] root: LinearVelocity dirty as (6.971044, 0)
[DEBG] root: LinearVelocity dirty as (7.0282106, 0)
[DEBG] root: LinearVelocity dirty as (6.971044, 0)
```

If you fix then bandwidth savings as you don't need to send physics state updates to the client every tick which is a big win.

**Comment by PJB3005** [comment]
This is *probably* a content bug but it does deserve some investigation.

**Comment by metalgearsloth** [comment]
Moved to https://github.com/space-wizards/space-station-14/issues/2492
