### ISSUE TITLE
Sending console commands while client is connected can cause exceptions on server

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1393]
The receive handler for `MsgConCmd` assumes the player has a player session which is not necessarily the case: https://github.com/space-wizards/RobustToolbox/blob/d5982b3ea2f75c1cae024a755a710c10b1e6bf40/Robust.Server/Console/ConsoleShell.cs#L92

**Comment by gradientvera** [comment]
Is this still an issue after the consoleshell refactor? @Acruid

**Comment by Acruid** [comment]
Maybe? Idk when the client would not have a session though. If the client did not ahve a session and sent a console message, this would crash.
