### ISSUE TITLE
Invalid Markup in FormattedMessage should be ignored

### ISSUE THREAD

**Issue by exp111** [space-wizards/RobustToolbox#1418]
Currently `AddMarkup` calls `ParseOrThrow`, which throws if you have invalid markup.
For cases like the paper UI in SS14, where the input is from the user, it should rather ignore invalid tags and just use them as strings.

**Comment by PJB3005** [comment]
I would prefer if a separate method were made for this instead.

**Comment by PJB3005** [comment]
Fixed by 04cc1f616d1c73e102199869cb0234d225cfe9e5. Use `AddMarkupPermissive` or `FromMarkupPermissive`.
