### ISSUE TITLE
Interface Issues for May 9th 2017

### ISSUE THREAD

**Issue by ghost** [space-wizards/RobustToolbox#142]
- [x] There's no button or keyboard shortcut (ex: ESC) to go back to the Main Menu from the Job Selection interface (first after Connect)
- [x] OverridePlacement in Entity Spawn should default to "AlignFree", not "None", it prevents spawning until you set it properly
- [ ] You can't select the chat by clicking on the text bar, only on the box itself, which is a bit odd
- [ ] The scrollwheel in the Entity Spawn menu prevents selecting anything if it's moved out of its original position
- [ ] Clicking anywhere outside of the chat window doesn't deselect it, this is not intuitive. Even ESC doesn't unfocus it
- [x] "Quit" ingame is maybe a bit too literal. It crashes the game immediately

**Comment by psykzz** [comment]
5th issue is being worked on in #128.

**Comment by ZoldorfTheWizard** [comment]
>april 9th

WHAT MONTH IS IT??!?!?

**Comment by psykzz** [comment]
Honestly most of these should be pulled out into separate issues.
That way its easy to track when each is fixed and by who, as most are not related (other than being UI)

**Comment by ghost** [comment]
At the same time, most appear to be easy fixes (add a button to return to main menu, make it so text line in chat focuses the chat, set another default/disable None as a choice for OverridePlacement, etc)

**Comment by PJB3005** [comment]
I mean really the entire UI framework needs rewriting.

**Comment by ComicIronic** [comment]
It doesn't matter how easy they are to fix, a single issue is useless for tracking. We might as well have a mega-issue where all the bugs go.

**Comment by ghost** [comment]
At least for now, that is

It's certainly better than fishing them out from the Discord

Only major issues should have their own tickets. If they fit on a bulletpoint, prolly not

**Comment by ComicIronic** [comment]
>Only major issues should have their own tickets.

I mean, no. An issue should have its own ticket because then we can close it when it gets fixed. It also lets us use the autocloser without fiddling around. An issue like this is more difficult to close (what if one of the bugs turns out to be really complex, but all the others are fixed?) and it doesn't help with tracking, because

1. It messes with bug stats
2. It doesn't give good history for each issue

**Comment by h3half** [comment]
2nd issue is fixed with #172

**Comment by h3half** [comment]
#175 attempts to address the first issue

**Comment by ghost** [comment]
Total fucking mess, closing. If any issues still exist, need re-testing
