### ISSUE TITLE
Tile Selection is not rounding properly

### ISSUE THREAD

**Issue by ghost** [space-wizards/RobustToolbox#143]
- Tile selection doesn't round properly on both axis in specific quadrants of the screens. To be specific, up/down works perfectly in the bottom right corner for example. I've also had left/right working perfectly in another case, but it doesn't work properly and jumps at about 0.5/center otherwise

**Comment by psykzz** [comment]
Should be fixed by #146

**Comment by ghost** [comment]
Will check shortly

**Comment by ghost** [comment]
Well, that is fixed
