### ISSUE TITLE
Issues with movement and rotation when being stuck

### ISSUE THREAD

**Issue by ghost** [space-wizards/RobustToolbox#144]
- If you are walled in, you can still make moving animations, you can't turn however. You don't move in both cases. This will probably be an issue once "being unable to move" becomes a part of the game

**Comment by PJB3005** [comment]
Is this a bug really?

Honestly I'm fine with this as long as we do a good job at preventing you from getting into these kinds of situations.

Actually bumping you out may be a good idea.

**Comment by ghost** [comment]
Well, imagine we have a way to prevent someone from moving completely like a restraint or a spell (inb4 no wizard no magic)

Are they still gonna do the animation ?

Same if we have variable speed, like a speed boost or speed slow from things. Are they still gonna wade at normal speed while going faster/slower ?

**Comment by ShadowCommander** [comment]
This is because of lines 30-33 in [InputSystems.cs](https://github.com/space-wizards/space-station-14/blob/master/SS14.Client.GameObjects/EntitySystems/InputSystem.cs), which **only** checks for input, but it doesn't check if the player actually moved.

**Comment by Acruid** [comment]
Player movement animations were not implemented when the new RSI system replaced the old animation system. This issue is not applicable anymore.
