### ISSUE TITLE
A grid added after a map is paused has its grid entity unpaused

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/RobustToolbox#1444]
- Create a map (sMapManager.CreateMap).
- Pause it (sPauseManager.SetMapPaused(mapId, true)).
- Create a grid on that map (sMapManager.CreateGrid(mapId)).
- IPauseManager.IsMapPaused will return true for that map id.
- IPauseManager.IsGridPaused will return true for that grid id.
- IEntity.Paused will be false for that grid's entity.

Pausing the map after the grid is created does pause the grid's entity though.

**Comment by metalgearsloth** [comment]
Smug cleaning up my bugs
