### ISSUE TITLE
Why Appveyor is broken

### ISSUE THREAD

**Issue by ComicIronic** [space-wizards/RobustToolbox#145]
SonarQube requires an auth token, and Appveyor lets you securely put them in a config to later be decrypted by the CI server. Since I don't own the build, I can't encrypt the SQ token, and the build can't run successfully - yet.

**Comment by ZoldorfTheWizard** [comment]
This should be fixed. Needs some testing

**Comment by ComicIronic** [comment]
AppVeyor is no longer broken!
