### ISSUE TITLE
Reduce the number of ways to do events

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1451]
Currently you can do:
* EventBus
* Component messages (HandleMessage and HandleNetworkMessage)
* C# events
* Interfaces (e.g. IAttack)

Ideally you only need:
1. to handle general events like "MoveEvent" where you want to subscribe to all of them, and 
2. events specific to an entity.

EventBus fulfills the role of 1, and for 2 it's either use interfaces or components (IMO). At this stage it's leaning towards using interfaces though 1 downside is that both component messages and interfaces currently just iterate over every component on an entity which can be silly.

**Comment by gradientvera** [comment]
So basically, we remove C# events and use the rest.
- EventBus & Component Messages are for notifying events that things might care about.
- Interfaces are for implementing specific behaviors.

Related issue, in a way: #1488

**Comment by Acruid** [comment]
The engine only uses the Component Messages and the EventBus.
* Component Messages are limited to the Components on the Entity talking to each other, with outside code able to raise events on an Entity. #1488 is an implementation detail for performance, not an actual change to the system design.
* EventBus is supposed to only be for the Systems to communicate with each other, but other non-ECS code can raise and consume events on it. The E/C style components we have will need to raise events on the EventBus.
* C# events are bad for ECS but OK (and good) for anything else. Technically they should not be on Systems, but meh.
* IAttack style interface events are purely a content thing, which seems to be a solution Unity developers use for E/C component communication. Open an issue in the content repo if you want to do something with them.

After a month there are no new design proposals in this issue, so i'm closing it.
