### ISSUE TITLE
`GetEntitiesInRange` is checking HALF the range

### ISSUE THREAD

**Issue by chairbender** [space-wizards/RobustToolbox#1465]
`EntityManager.GetEntitiesInRange` creates a box centered on the coordinates with a length and width of `range`. This results in the range check only finding entities within HALF of the specified range. Instead it should check the full range (don't divide the coordinates by two), since that's kind of what 'range' implies (distance from the target coordinates).

As part of this, make sure to audit any usages of this method (even in Content) to ensure the range being checked still is right. It looks like current usages of the method are expecting it to work in the (fixed) way described in this ticket, but some places such as singularity might need to be tweaked, as this is going to double the range that gets effected.

**Comment by chairbender** [comment]
thanks to @daniel-cr for finding this over in https://github.com/space-wizards/space-station-14/pull/2819

**Comment by Ygg01** [comment]
Is the range supposed to be square or circle?

**Comment by PJB3005** [comment]
`EntityManager.GetEntitiesInRange` is an absolutely terrible API and this is one of the many reasons why. Frankly we're better off just removing it.

**Comment by Ygg01** [comment]
What should we use instead?

**Comment by PJB3005** [comment]
That really depends on what kind of entities you need. For example if you need all physics entities there are indexes for that in the physics system. Etc with sprites, occluders, etc...

The behavior of `GetEntitiesInRange` is too ill-defined and generic to really be used for much.

**Comment by GalacticChimp** [comment]
I can try this one

**Comment by gradientvera** [comment]
Fixed by 6cb7641c070675542c03087ed557b9347d7b813a, pretty sure
