### ISSUE TITLE
Add support for fixedrotation to transforms

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1479]
Some stuff should never have their local rotation adjusted (e.g. walls, windows, low walls). Some stuff (e.g. players) also needs their world rotation fixed (so players always appear upright to you).

Implementing the former would bandaid occluders for now (until rotated grids) but that's not really the point.

The main pain point of a pr is you'd need to update the transforms of all walls on saltern though you could probably script it.

**Comment by PJB3005** [comment]
The problem with walls should be fixed on placement so that certain entities can be blacklisted from rotation.

The problem with players should be solved by modifying the SpriteComponent rendering code.
