### ISSUE TITLE
Add an IgnoredComponents merge driver

### ISSUE THREAD

**Issue by ike709** [space-wizards/RobustToolbox#1486]
@PaulRitter

**Comment by PaulRitter** [comment]
should be fairly easy, i haven't written a merge driver & gotten enough other assigned issues rn so this is fair game

**Comment by PaulRitter** [comment]
maybe something for @20kdc since they are already working on the map merge driver

**Comment by 20kdc** [comment]
IgnoredComponents really shouldn't need a merge driver.

**Comment by ike709** [comment]
IgnoredComponents is the most often conflicting file in the codebase.

**Comment by PaulRitter** [comment]
ye ignoredcomponents are literally a conflict in every second pr

**Comment by PJB3005** [comment]
Here's your merge driver: add stuff to the middle of the list randomely instead of to the end.

Problem solved.
