### ISSUE TITLE
Components need to specify which messages they receive.

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#1488]
Bookkeeping. This way we don't need to iterate EVERY component that might care about a message on entities with large amounts of components (humans, for example)

**Comment by PaulRitter** [comment]
maybe could be achieved by doing annotations?
[SubscribeMessage(typeof(MessageType))]

**Comment by moonheart08** [comment]
Could possibly also do this with reflection, it'd be less error prone (no need to duplicate the subscribe message and actually getting messages), but has a billion complications

**Comment by this-is-the-bard** [comment]
So are we caching for both comp messages and interfaces? Because they both iterate through every comp.

**Comment by gradientvera** [comment]
> So are we caching for both comp messages and interfaces? Because they both iterate through every comp.

It'd be ideal, in my opinion

**Comment by PaulRitter** [comment]
> Could possibly also do this with reflection, it'd be less error prone (no need to duplicate the subscribe message and actually getting messages), but has a billion complications

Thats what i meant by doing it per annotations, you could do a [SubscribeMessage] attribute with the CTOR of SubscribeMessage(params Type[] messageTypes) and read & cache that when doing the componentregistrations

**Comment by Acruid** [comment]
Superseded by https://github.com/space-wizards/RobustToolbox/issues/1599.
