### ISSUE TITLE
Logs for release builds or at least a crashdump

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/RobustToolbox#1494]
### **Today on "Why is that not already a thing":**

so i can actually help testers that get this shown to them
![grafik](https://user-images.githubusercontent.com/16618384/104107987-3bc71280-52c1-11eb-80d3-e5fbfeedb71c.png)

**Comment by PJB3005** [comment]
Fixed by https://github.com/space-wizards/SS14.Launcher/commit/eac5608efdd3791093f39afec719f8fa2b1fcb63
