### ISSUE TITLE
Move to a decentralized grid system.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#150]
Basically, space without a grid would be, well, space.

Grids (like the station) are themselves can move around in this space.

Global coordinates are relative to a central 0,0 point. Each grid has its own coordinate set to refer to the individual tiles on the grid.

**Comment by ghost** [comment]
This could lead to some pretty hardcore station destruction simulation, or actual ships, something we never had before

On the other hand, this would need an incredibly robust tiling system, and all floors and walls would basically become objects of their own, with the "space background" being the only real tile

**Comment by ZoldorfTheWizard** [comment]
This is the plan yes.

**Comment by Acruid** [comment]
Added in https://github.com/space-wizards/space-station-14/pull/338
