### ISSUE TITLE
Clients are still getting incorrect net.tick_rate when connecting to public servers in some cases

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1516]
Had another report of client broken that was fixed by cycling net_tickrate on the server. Needs investigation. I have a few hunches:

1. Race condition in connect sequence causing it to fail to apply?
2. `net.tick_rate` is `ARCHIVE`. Is it getting saved in config files and as such a culprit?

**Comment by gradientvera** [comment]
This reminded me that I couldn't get any (ARCHIVE, obviously) CVar changes on the server to sync properly to the client on a RobustToolbox project.

**Comment by PJB3005** [comment]
The problem is indeed (2). If `net.tick_rate` is saved as 30 it causes the CVar to not be recognized as changed when the client connects to our servers (they run at 30) and the TickRate is never set to 30 because the OnValueChanged handler never runs.
