### ISSUE TITLE
Move to doubles for world positions?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#153]
Might be a good idea. Making this issue for discussion.

**Comment by ComicIronic** [comment]
The reasons to use floats are:

- If an existing library requires it
- If you're doing a lot of GPU calculations with the number
- If you need the memory

So I'd say we're 0/3, and there's no reason not to switch

**Comment by PJB3005** [comment]
World positions are already floats. The point of the discussion was to move from single precision floats to double precision ones to prevent accuracy loss.

**Comment by ComicIronic** [comment]
By floats, I meant singles. I forget if C# actually has "single" as an alias for the type.

**Comment by PJB3005** [comment]
Oh I misread your comment and didn't notice the *not*.

Nevermind.

**Comment by psykzz** [comment]
Some things i found during research

```
Doubles are slower on every platform you'll care about writing games, take twice the memory bandwidth, and have fewer specialized CPU instructions available.

Single-precision floats remain the standard for hardware graphics interfaces, both on the C/C++ side and inside shaders

You'll probably need a double vector at some point, but it should be used when needed, not by default
```

**Comment by h3half** [comment]
World coordinates are currently of the type `SFML.System.Vector2f`.

If we're moving away from SFML that'll have to change anyways - if we're going to switch to double-precision floats that would be the time to do it.

**Comment by psykzz** [comment]
But personally though, you just don't need the precision for doubles and floats are supported with more operations within the GPU.

**Comment by PJB3005** [comment]
Alright.
