### ISSUE TITLE
Layers (not ZLevels)

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#155]
How do we want to handle stacking of items.

Some things should be higher in priority than other, so that when you place an item on the floor, it should appear above blood.

This can also be expanded to things like layers of Space > Station > Pipe > Floor > Ent.

**Comment by ZoldorfTheWizard** [comment]
Space 
Scaffolding 
Plating
Pipes Wires ect
Floor
Items

Is my two cents

**Comment by ghost** [comment]
Layers still work fine

Space should be the absolute background, impossible to interact with (for obvious reasons). You should only be able to lay structures connected to other structures, or maybe using a magic "station starter beacon" or "ship starting beacon" or whatever, like Space Engineer does it

For the rest, layers work fine, but we'll want to revisit how plating, pipes, wiring and flooring works. However, I think having catwalk floor like in the Aliens style industrial deco through which piping and wiring goes is cool

**Comment by PJB3005** [comment]
What @dylanstrategie said.

**Comment by clusterfack** [comment]
Absolute background
Space
Space Effects

Underfloor
Underfloor layer (pipes, wires, etc)
Floor
Overfloor layer (vents, etc)

Items / Mobs
Effects
Lighting
HUD

**Comment by PJB3005** [comment]
2D sprites have a `DrawDepth` enum that fills this role. Might not be enough though..

**Comment by Acruid** [comment]
Closing this as it seems everyone reached an agreement. If there is an actual problem with layer/depth sorting in the engine open a new issue about it.
