### ISSUE TITLE
Add rcon

### ISSUE THREAD

**Issue by DrSmugleaf** [space-wizards/RobustToolbox#1550]
![image](https://user-images.githubusercontent.com/10968691/107820669-7538e500-6d7b-11eb-9781-22d41a64ff5e.png)

**Comment by Acruid** [comment]
![image](https://user-images.githubusercontent.com/1685952/147710080-a156c6a5-479d-4472-bd9c-a668cf3a9674.png)
The issue has been blessed, we are good to go!

**Comment by PJB3005** [comment]
It has come to my knowledge that rcon has 0 form of security other than some implementations using hmac-**md4**. Unless my googling has failed me and there *is* a commonly-understood version that uses at least sha-256 as digest, this is getting veto'd.
