### ISSUE TITLE
Can't add new component instead of old, marked for removal one

### ISSUE THREAD

**Issue by io-june** [space-wizards/RobustToolbox#1580]
Recently discovered in #1564

When adding new component via AddComponent, it checks for duplicates and removes them, but misses components that are marked for removal:
https://github.com/space-wizards/RobustToolbox/blob/master/Robust.Shared/GameObjects/ComponentManager.cs#L108

https://github.com/space-wizards/RobustToolbox/blob/e0cdcd228e4773b9c737cc9c09737c08d13d248d/Robust.Shared/GameObjects/ComponentManager.cs#L265

In the end, we get `System.ArgumentException: An item with the same key has already been added.` from
https://github.com/space-wizards/RobustToolbox/blob/master/Robust.Shared/GameObjects/ComponentManager.cs#L114

I think we should immediately delete these components even if they were marked for removal before.

**Comment by Acruid** [comment]
Yep, the component should be immediately actually deleted even if marked for removal in this case so that the new one can take it's place.
