### ISSUE TITLE
Move LogManager to IoC and shared. Implement it on the client.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#159]

**Comment by psykzz** [comment]
Completed it https://github.com/space-wizards/space-station-14/pull/163

**Comment by PJB3005** [comment]
Not moved to IoC yet.

**Comment by PJB3005** [comment]
Though I guess in hindsight it wouldn't be the end of the world to not have it on IoC.

**Comment by PJB3005** [comment]
Ok actually no scratch that it would be because we definitely need differences between client and server.
