### ISSUE TITLE
Deprecate IEntityQuery

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1607]
There are other, better ways of doing it IMO:
![image](https://user-images.githubusercontent.com/31366439/109923516-019f4d80-7d13-11eb-9d32-98fb73555928.png)
* AllEntityQuery -> EntityManager.AllEntities
* IntersectingEntityQuery -> Collision lookup (SharedBroadPhaseSystem on new physics, IPhysicsManager on old)
* MultipleTypeEntityQuery -> ComponentManager
* PredicateEntityQuery -> ComponentManager
* TypeEntityQuery -> ComponentManager
* TypeEntityQuery<T> -> ComponentManager

**Comment by GalacticChimp** [comment]
I can try this one
