### ISSUE TITLE
Reparenting/container removal deletion issue on the client

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#1646]
This is an issue I found thanks to disposals on content, but I feel like this is the correct place to open it.
The bug is the following:

1. On the server, an entity B is reparented from (*removed from container*) entity A
2. Immediately, entity A is deleted.
3. The client deletes entity A and recursively deletes entity B

This is obviously an issue, as the client should have reparented entity A *before* deleting entity B.

**Comment by Acruid** [comment]
The client does apply the gamestates before deleting entities. Lockers drop their contents in their OnRemove event, and they have no problems. Can you verify this bug still exists, and list steps on how to reproduce this bug on master?

**Comment by gradientvera** [comment]
> The client does apply the gamestates before deleting entities. Lockers drop their contents in their OnRemove event, and they have no problems. Can you verify this bug still exists, and list steps on how to reproduce this bug on master?

Apparently, this was fixed at some point so the workaround I used is no longer needed
