### ISSUE TITLE
Grid splitting and merging.

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#1647]
We should have methods to split grids into two, and also to merge two grids into one.
This will be useful in content for shuttles and fancy stuff like parts of the station flying off into space when they stop being connected through tiles to the rest of the station

Requires #1648, most likely.

**Comment by Peptide90** [comment]
So much potential. I'm seeing a space station with compartments that break apart now. Jettison security to get rid of the blob...

**Comment by metalgearsloth** [comment]
Done with https://github.com/space-wizards/RobustToolbox/pull/3627 I was just too lazy to write tests.
