### ISSUE TITLE
Remove "tiles"

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#165]
Tiles should not be a concept in the game.
We should instead recreate walls as entities and have them replace any walls.
Same with Floors

**Comment by PJB3005** [comment]
Yeah that's what I want to do as part of #150

**Comment by ghost** [comment]
This would be very revolutionary, but possible. The issue is making sure that tiles stay coherent with each other should they move, merge and separate, since I imagine that's the end goal (otherwise, we'd be using static world tiles)

**Comment by clusterfack** [comment]
Tiles may not be useful, but snap to grids definitely are

**Comment by psykzz** [comment]
I agree to keeping grids definitely.

**Comment by clusterfack** [comment]
I'm curious how you would locate nearby objects without tiles though

**Comment by BobdaBiscuit** [comment]
Could we perhaps have """tiles""" just be everything that's on a grid coordinate?

**Comment by clusterfack** [comment]
I think people are trying to say they don't want "turfs" as such, but we still need to be conscientious of what turfs in ss13 are actually used for.

- setting what is in the view of a user and sending them info
- holding info on location of objects and finding nearby objects
- collision mechanics
- a grid for construction to be based on
- a grid for movement to be based on
- a few other things I've surely forgotten

It's probably important to say which of these you still want or need. I think the first two in my list are absolutely necessary but you can abstract them out to structs.

**Comment by PJB3005** [comment]
I think for some things like collision you would still use "tiles" in the form of a global quadtree, but for construction it would be the individual grids that you'd be aligning to.

**Comment by psykzz** [comment]
Why would you need to use tiles for collisions, the collisions manager already manages collisions as buckets anyway, we just need an optimize function that creates buckets from buckets and we're golden

**Comment by ghost** [comment]
Still undecided

**Comment by YotaXP** [comment]
I'm still strongly against the removal of tiles/turfs.  The grid of floors and walls make up a large amount of data that will take a long time to iterate through and send through the network if it's not given special treatment.  There are also assumptions we are allowed to make when floors (and walls) are hard locked to a grid.  I don't want to constantly have to protect myself from that wise guy who will eventually try creating a floor or wall that's slightly off the grid.

**Comment by PJB3005** [comment]
Floors is meh but even basic walls quickly balloon to be so complicated
that you'd need a tile entity for everything.

**Comment by Acruid** [comment]
Turfs are not a thing anymore. Regular entities are not locked to tile locations. There are now map Grids which are a 2D array of tiles that form the map. The tiles themselves are just a struct with a tileDefId and damage value fields. If someone has a reason to change tiles to use a TileEntity, they can open a new issue.
