### ISSUE TITLE
MapLoader does not initialize entities in preorder.

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#1654]
Which means children can get initialized before parents, which leads to some funky bugs involving GridTileLookupSystem.

**Comment by PJB3005** [comment]
I don't think the map loader should be enforced to any specific initialization order. GridTileLookupSystem should probably handle this instead.

**Comment by Acruid** [comment]
GridTileLookupSystem does not exist anymore. The only guarantee in initialization is that the current component is deserialized and that Transform/MetaData components are in a valid state on ALL entities in the TransformTree. PJB is right, maploader should not be responsible for this. All maploader does is alloc ents to the TransformTree, an perform a deserialization pass before init.

AFAIK the algorithm to do this would cause terrible perf issues, so the solution here is to not rely on entity lifestages/init order.
