### ISSUE TITLE
Stuttering while walking around

### ISSUE THREAD

**Issue by ike709** [space-wizards/RobustToolbox#1714]
Just walking in a straight line with no obstacles causes semifrequent microstutters.

Here's a video example: https://streamable.com/vgnbix

Examples (most to least obvious) at 0:18, 0:04, 0:13.

I'm assuming this is a prediction or physics issue.

**Comment by ike709** [comment]
Just an FYI this was on the steam server, not on a debug build.

**Comment by PJB3005** [comment]
It's because the render targets used to render post-process shaders are getting leaked and cleaned up in batches by finalizers.

**Comment by ike709** [comment]
Yep I understand most of those words separately.

**Comment by Acruid** [comment]
If it is a GC issue, you should be seeing frame time increased and increased allocations/sec on the F3 graph when it is stuttering.
