### ISSUE TITLE
Investigate generic query system / reducing DynamicTree boilerplate

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1716]
We could just have the methods query the relevant DynamicTrees instead and cut down on memory usage i.e. query physics dynamictrees and renderingtreesystem's sprite / pointlight trees. We could also potentially combine all of this into a generic query system to reduce the code duplication between all of them and make it easy to extend for new components. Callers could just pass in flags if they want to only query a specific DynamicTree. Ideally you could also make it so content can extend this for its own components.

That way we only need a DynamicTree in IEntityLookup that tracks entities that aren't already on an existing tree and an entity is only ever on the one DynamicTree rather than potentially being on 3 like they currently can be.

**Comment by ElectroJr** [comment]
Other than the light & sprite tree stuff, this is basically done now?
