### ISSUE TITLE
Visualizers can't be internal

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1740]
You get type not found exceptions. Would it be because Robust.Client needs access to the types? Not sure if it should be supported or not.

**Comment by DrSmugleaf** [comment]
https://github.com/space-wizards/RobustToolbox/blob/80f9f24243fe9852d5010a99b40ad5daa5e42740/Robust.Shared/Reflection/ReflectionManager.cs#L227-L230
