### ISSUE TITLE
Filter improvements

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#1745]
- Right now, `Filter` implements `Recipients` explicitly, meaning you must cast it to `IFilter` before accessing it.
This seems dumb and useless, everything using `Filter` currently does that. If we're meant to use `IFilter` instead of `Filter`, then perhaps the static methods in `Filter` should return `IFilter`, and things should ALWAYS take `IFilter`.

- Recipients is currently an `IList<ICommonSession>`. This isn't great, as it doesn't allow us to, for example, code an immutable filter, or force devs using the API to go through our methods instead of modifying the underlying list directly. In my opinion, we should change this to `IEnumerable<ICommonSession>`.

- Should `IFilter` implement `IEnumerable<ICommonSession>? This would allow people using filters to simply enumerate it when they want to get all sessions being filtered. It'd be very convenient!

- EntitySystems should have a `RaiseNetworkEvent()` overload that takes in a filter.

**Comment by Acruid** [comment]
![image](https://user-images.githubusercontent.com/1685952/117522896-a552e700-af6a-11eb-94a8-032e4fb9fc33.png)

**Comment by gradientvera** [comment]
Fixed by #1747
