### ISSUE TITLE
Really bad lighting pop-in

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/RobustToolbox#1754]
## Description

happens basically everywhere but bridge is most egregious

https://user-images.githubusercontent.com/19853115/116831003-d180f900-ab61-11eb-8fa0-959cf088f05b.mp4

**Additional context**

**Comment by 20kdc** [comment]
This looks like space-wizards/space-station-14#3922 tbh

**Comment by PJB3005** [comment]
Pretty sure this is PVS related, actually.

**Comment by Acruid** [comment]
The lights are not even close to the edge of the screen though, so they should not be PVS culled. It would have been nice if the view shadow was removed so we could see if the light fixture was disappearing or not.

**Comment by Acruid** [comment]
Looks like not PVS.

**Comment by Acruid** [comment]
https://github.com/space-wizards/RobustToolbox/blob/master/Robust.Client/GameObjects/EntitySystems/RenderingTreeSystem.cs#L310

Looks like a bug, this conditional block will always be true, so light remove code is never ran.

**Comment by metalgearsloth** [comment]
I'm retarded don't research.

**Comment by metalgearsloth** [comment]
Okay the remaining pop-in is PVS. Just increase your ping and watch the pop-in get worse. On server right now for me it's especially bad at 300ms.

**Comment by Acruid** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/pull/1798. Similar symptoms to https://github.com/space-wizards/RobustToolbox/issues/1198, but a completely different issue.
