### ISSUE TITLE
XAML files throw a ton of errors in VS

### ISSUE THREAD

**Issue by SweptWasTaken** [space-wizards/RobustToolbox#1762]
![image](https://user-images.githubusercontent.com/49448379/119175191-0b566880-ba59-11eb-8422-27a54a5183ab.png)

Maybe get some kind of suppression for these?

**Comment by PaulRitter** [comment]
2 seconds of google: https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-errors-warnings?view=vs-2019#suppress-xaml-designer-errors
