### ISSUE TITLE
Bright lights when rejoining a server

### ISSUE THREAD

**Issue by h3half** [space-wizards/RobustToolbox#179]
Fairly self-explanatory. If you join a server, leave using the ESC menu, then rejoin the lights will be very very bright.

**Comment by ZoldorfTheWizard** [comment]
![image](https://cloud.githubusercontent.com/assets/7108570/26479069/dca00124-418d-11e7-8cc6-51ec1a5c4f7b.png)

The rendertargets are not getting disposed properly when the gamescreen state shuts down, so when you rejoin the texture gets reused and the lights are resampled over each other creating the bright white effect

**Comment by ZoldorfTheWizard** [comment]
Time Traveling Wizard Here: This was most likely caused by #315. Testing is needed to see if issue persists. it is very unlikely the issue has persisted.

**Comment by h3half** [comment]
Whether or not the underlying cause is the same, this is currently still an issue.

This is after leaving and rejoining five times:
![screenshot_1](https://user-images.githubusercontent.com/1471542/29408779-8aa32790-8317-11e7-858b-23acada1d9f3.png)
