### ISSUE TITLE
Wiki Cleanup

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/RobustToolbox#180]
We need to clean up like one or two of the pages in the wiki that have information from the first remake team. Most of it doesn't apply to the current engine.

**Comment by Pangogie** [comment]
Mild *spiffification* has been achieved.

**Comment by Pangogie** [comment]
Is [World and Position](https://github.com/space-wizards/space-station-14/wiki/World-and-Position) up-to-date or can it be removed?
Do we still need [#spaceart Piratepad backup](https://github.com/space-wizards/space-station-14/wiki/%23spaceart-Piratepad-backup)? Could this information be moved elsewhere?

**Comment by PJB3005** [comment]
@Pangogie keep the backup.

**Comment by PJB3005** [comment]
I've added a notice to world and positioning saying. Keep it for reference because it's probably a correct description of the mess we currently have.

**Comment by gradientvera** [comment]
Fixed after the move to hackmd, I think.
