### ISSUE TITLE
Use the dotnet LinkedList for physics LinkedLists

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1809]
Currently they just use their own implementation and I hate looking at.

**Comment by GalacticChimp** [comment]
I might have a moment to attempt this, in the next few days

**Comment by GalacticChimp** [comment]
ok, going for a deep dive, wish me luck

**Comment by metalgearsloth** [comment]
You're better off doing the tile friction issue tbh

**Comment by GalacticChimp** [comment]
@metalgearsloth ok, I'll give it a shot
