### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#181]
As far as I can tell, next to none of the code is thread safe. Bad.

We should at least keep it in the back of our heads.

**Comment by clusterfack** [comment]
What does that look like?

**Comment by PJB3005** [comment]
@clusterfack basically writing code that doesn't have data races and stuff by correctly using locks.

**Comment by PJB3005** [comment]
https://docs.microsoft.com/en-us/dotnet/articles/standard/threading/managed-threading-basics

**Comment by PJB3005** [comment]
Eh. I don't think this issue is really specific enough to be an issue.
