### ISSUE TITLE
Replace Lidgren.Network?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#182]
Lidgren is unmaintained, seems to have some issues, and doesn't have stuff like IPv6 support.

On one side we can try to maintain it, on the other we can maybe look for a replacement. This library got linked in Lidgren's google group: https://github.com/RevenantX/LiteNetLib

**Comment by psykzz** [comment]
Alternative point though, many people have successfully, and continue to successfully, use Lidgren in their applications without issues.

**Comment by gbasood** [comment]
There's a PR on the lidgren repo that adds ipv6 support
The multi-client per IP thing is an implementation error, i.e. our fault.

**Comment by PJB3005** [comment]
IPv6 support in a lone PR is not something I'd trust though.

**Comment by gbasood** [comment]
Better than re-implementing our entire netcode using something lower level than what we're using now.

**Comment by PJB3005** [comment]
There's always the option of replacement instead of rolling our own.

**Comment by gbasood** [comment]
Looking it over it looks like litenetlib is better in the long run because:
 - We don't have to fix the ipv6 implementation
 - We don't have to fix other lingering issues
 - litenetlib is supposedly more efficient

**Comment by ghost** [comment]
@gbasood 
> 👍 from litenetlib creator 

🤔

**Comment by PJB3005** [comment]
This is obviously gonna be a *really* long term goal, so not something we should be working on yet.

That said it may be worth making an abstraction layer on top of Lidgren so we can swap it out more easily later if we have to (interfaces for things like the incoming and outgoing message types)

**Comment by gbasood** [comment]
Honestly whoever does it is going to have a *great* time doing so since there doesn't seem to be straight parallels between any part of Lidgren we're currently using and litenetlib
Also litenetlib isn't documented, and there are no tutorials related to it and game dev, so you're going to end up learning from the code

**Comment by RevenantX** [comment]
@outbools i am collecting feedbacks. Because not all users write to me (i understand). Documentation exists (in XML) (and covers almost all features except very obvious). And after reading this thread i added **.chm** file.
I am trying to make my library very similar to lidgren3 in many aspects :)

**Comment by PJB3005** [comment]
Now this is some service.

**Comment by Acruid** [comment]
The IPV6 issue was fixed in https://github.com/space-wizards/space-station-14/pull/204. There does not seem to be any actual issues with Lidgren, so unless something comes up there is no point taking the effort to replace it.
