### ISSUE TITLE
AddComponent doesn't seem to be syncing comps

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1839]
I've noticed this twice where if I AddComponent<T> on server the comp is never synced to the client. I would assume by default it should be.

The current mapgrid PR https://github.com/space-wizards/space-station-14/pull/4200 is an easy way to check where it does AddComponent<GravityComponent> but the client never receives it (either when joining initially or during game). Even if you give it a ComponentState and dirty it it never seems to get received.

Maybe I'm going crazy but I did try watching it with net_entwatch 855 and never got anything when toggling the gravity generator and breakpointing server to confirm AddComponent is being called. It's also not in the ignore list for client.

**Comment by gradientvera** [comment]
can't replicate anymore

**Comment by Acruid** [comment]
I can't reproduce this, I'm assuming it was fixed.
