### ISSUE TITLE
WMI query for HWID can fail, giving users an obscure "Invalid class" error message.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#1876]
https://www.reddit.com/r/ss14/comments/oon1cc/i_cant_join_any_server_i_tried_a_couple_of_months/

**Comment by PJB3005** [comment]
This is apparently caused by corrupt WMI registries, not sure we should fix this.

**Comment by PaulRitter** [comment]
i saw something about being able to set a pragma flag. #pragma autorecover or stmh
