### ISSUE TITLE
Saved entities being spawned at (0, 0).

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/RobustToolbox#192]
All saved map entities appear to be spawning at (0, 0), the start location for the player.

**Comment by h3half** [comment]
`TransformComponent` is being properly applied to entities, but they're just not moving. Along with #193, my uneducated guess is that something broke the transform component's ability to translate objects.

**Comment by ZoldorfTheWizard** [comment]
Yes, the entity is correctly building the components

SS14.client is firing off the event handlers for the keybourd input and the server is receiving the movement updates but it seems the client keeps sending the same position and never a new position.
