### ISSUE TITLE
Server cannot load "SavedMap". Forcing NewMap( ).

### ISSUE THREAD

**Issue by Pangogie** [space-wizards/RobustToolbox#194]
MapManager forces NewMap( ). No code to receive saved map name from configuration.

[MapManager.cs Ln 33](https://github.com/space-wizards/space-station-14/blob/master/SS14.Server/Map/MapManager.cs#L33)

**Comment by ZoldorfTheWizard** [comment]
The map system was reworked by YotaXP a long time ago. the new map system never got finished so the server just makes a map using the newmap method https://github.com/space-wizards/space-station-14/blob/master/SS14.Server/Map/MapManager.cs#L447

The idea was for the map to have chunks of 16 i believe

**Comment by PJB3005** [comment]
This error message is pretty deceiving actually. The map loader doesn't even bother and prints that message instantly.
