### ISSUE TITLE
PVS optimisations

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1957]
Here's my main ideas on further optimising it:
- [x] Remove anchored entities from EntityLookup. This is the easiest and allows you to remove the anchored check in FastEntitiesIntersecting.
- [ ] Container hiding for entities. My only idea on this is don't store contained entities on EntityLookup and have a separate tree for entities with containers, then iterate through these entities + containers separately.
- [x] Sharing states between players and using chunking for entity visibility. The way things are designed now 2 players can get 2 entirely different states for the same tick as GetComponentState takes in an ICommonSession but 99% of entities don't need to use this and PVS is effectively O(n) atm in regards to querying entities in range + getting their states.

**Comment by PaulRitter** [comment]
would player specific states also be a bulletpoint for this issue?

**Comment by metalgearsloth** [comment]
Potentially.

So:
* I tried container-culling on a separate DynamicTree but it was annoying to implement and just making sure the containers were being queried correctly made it slower than the current version so this one is probably beyond me. The only other think I can think of is using the visibility masks (though you still need to do the TryGetComponent for each contained entity in range) and update it whenever an entity is inserted / removed from a container.
* I tried chunking the entire pipeline (anchored + regular entities) but it was too slow as I could only parallel specific parts internally and had to run other parts sequentially.

I had a new idea on sharing and that is:
1. During EntityLookup's Update() (which is called immediately prior to PVS) the server works out the viewers + what chunks are in range for each player. These chunks are transient for each tick and we don't store data on them outside of PVS.
2. For each chunk we do the regular PVS query (i.e. FastEntitiesIntersecting + RecursiveAdd) to get a hashset of its relevant entityuids
3. PVS now just queries which chunks are in range for each player and essentially does a union of the entities for each one.
4. Server clears chunk data for next tick.

This would mean that:
* We don't need to do many duplicate AABB intersections (e.g. if there's 300 players in bar we don't do the same AABB check for each entity 300 times).
* We can just do the expensive RecursiveAdd once for each entity (or at least once per visibilitymask so realistically twice).
* We still do the previousset / currentset swapout but we don't have to deal with entirely new bugs popping up from an entirely new PVS.

*If* this ends up being faster we could extend it to also include storing all the relevant entity states on the chunk to share data. In the interim anchored entities would also remain as-is (O(n)) for now because it's very easy to make PVS shittier if you're not careful and anchored entities rarely update anyway. 

I tried to do too much originally and it would've required lots of work to even achieve parity with what we have whereas I think this is more feasible in seeing actual benefits in the near future.

**Comment by PaulRitter** [comment]
so i might have put off reading this because mucho texto, but its nice to see we had similar ideas :heck:

my main ideas for making pvs go zoom rn are:
- keep a cache of all entities mapped to grid/map chunks. that way you only need to calculate which chunks are in pvs range and send their contents, making this WAY less expensive
- calculate entitystates once per pvs-run & cache them

**Comment by PaulRitter** [comment]
maybe i might even look into caching the entire recursiveadd either per run or in general, using events. we'll see. that one stays in the shed for now tho
