### ISSUE TITLE
WorldHandle DrawCircle should have more segments

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1976]
Currently it has 8 and we get complaints all the time it's not a circle. ScreenHandle uses 64 but like a comment on WorldHandle says it should be dynamic based on the radius. Maybe for now just make it radius x 16?

**Comment by PaulRitter** [comment]
radius x 16 sounds fine, but we should also add a minimum when making it dynamic. maybe a minimum of 8?
