### ISSUE TITLE
chunk pop-up needs fixing

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#1984]
Currently when the client moves around it can get up to 3 chunks / up to 768 anchored entities dumped on it at once from pvs which is bad.

We can probably just enlarge pvs to get a lower priority chunk range (for any chunks the client has never seen before and isn't already included in pvs) and send these entities over multiple ticks instead to reduce this impact.

If sending a whole chunk is still bad (It probably will be) you could piecemeal it further and send say 1/4 of a chunk every tick (when we aren't already sending a bunch of chunks).

**Comment by PJB3005** [comment]
I can definitely notice lag spikes from moving around with the "send whole map initially" disabled now, on debug builds.
