### ISSUE TITLE
Allow C# 7.0 features?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#203]
Pattern matching, tuples, out vars. All damn amazing.

Issue is that VS 2015 users will be screwed. Is it worth it to drop VS 2017 in favor of C# 7.0?

Mono supports C# 7.0, and both MacOS and Linux on Travis use it.

**Comment by gbasood** [comment]
`https://blogs.msdn.microsoft.com/benjaminperkins/2017/03/23/how-to-enable-c-7-in-visual-studio-2017/

**Comment by ZoldorfTheWizard** [comment]
burn 2015

**Comment by PJB3005** [comment]
We're using C# 7 now. Hype.
