### ISSUE TITLE
EntityManager's SpawnEntity overload inconsistencies

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#2092]
Currently, `EntityManager` has two `SpawnEntity` methods. One takes in `EntityCoordinates`, and the other takes `MapCoordinates`.
That's all good, but the problem arises when you inspect the implementation of the methods:
The `EntityCoordinates` overload checks if the map the entity is being spawned on is initialized, and if so, it runs `MapInit` on the entity being spawned.
The `MapCoordinates` overload, however, doesn't do this.

What is supposed to be the behavior for `SpawnEntity`? Is `MapInit` supposed to be called on these spawned entities or not?
A lot of SS14 currently depends on spawned entities being `MapInitialized` (see: `MachineComponent`, `AtmosPlaqueComponent`, etc to name a few)
We should probably clarify this as soon as possible.

**Comment by PJB3005** [comment]
Yes the map one should do map init too probably.
