### ISSUE TITLE
Multiline text input UI control

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#2101]
Having an UI control like `LineEdit` but for an arbitrary amount of lines would be very convenient for many things.

**Comment by PaulRitter** [comment]
have some limit tho, because of that "crash by massive unicode char spam" issue

**Comment by Efruit** [comment]
**I REFUSE TO BE BLOCKED BY THIS ANY LONGER**

![1499217568353](https://user-images.githubusercontent.com/602406/140941803-2843a3b6-9450-48fe-9a88-8fcc97bfb3a9.jpg)

**Comment by gradientvera** [comment]
Implemented in #3436
