### ISSUE TITLE
Console exception spam. Can't replicate.

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/RobustToolbox#2108]
I was playing around with the carvings in sandbox, was also suffering a lot of lag, kept getting rubbedbanded back into a specific spot while trying to walk, not sure if that has to do with this.

https://user-images.githubusercontent.com/43253663/136498242-99116ddf-ab5f-4043-bc67-8b8ce80d5b9d.mp4

![unknown](https://user-images.githubusercontent.com/43253663/136498378-4b3f9726-a5ad-4097-983f-5962c6348e1c.png)

The rubberbanding thing happening:

https://cdn.discordapp.com/attachments/790656972801572905/895883424118751293/2021-10-08_00-59-29.mp4

**Comment by ElectroJr** [comment]
This might have been caused by the issue described here: [space-wizards/space-station-14#4800](https://github.com/space-wizards/space-station-14/pull/4800). Even if it wasn't the same cause, it's probably not directly RobustToolbox related.

**Comment by DogZeroX** [comment]
This has been fixed.
