### ISSUE TITLE
IL Verification occasionally throws exceptions on Linux

### ISSUE THREAD

**Issue by Efruit** [space-wizards/RobustToolbox#2130]
[Most involve exceptions saying things like `Unknown PE Magic Value`](https://gist.github.com/Efruit/6e6508d31822a1e7930cf8ef528dd941) or mentioning the `COFF` header. Some mention file structure sizes are wrong. As far as I'm aware, it only impacts game clients; I've neither heard of, nor seen any instances on game severs.

On a rare occasion, [it will mention memory mapping issues](https://gist.github.com/Efruit/66d5ac7331946d6ccc8758b2fd220da8).

Attempted fixes:
- ~~[Limiting parallelism when using `ILVerify`](https://github.com/Efruit/RobustToolbox/tree/linux-ilverify-workaround)~~
- [Setting a flag on `PEReader` that may change its memory mapping behavior](https://github.com/Efruit/RobustToolbox/tree/linux-ilverify-fix-take-2) #2131

"""""Reproduction""""" steps:
- Start and stop a game's `Content.Client` and `Content.Server` repeatedly.
- Sometimes rebuilding the game causes it to happen.
- Sometimes it happens a lot of times in a row, sometimes it doesn't happen for hours.

**Comment by Ygg01** [comment]
Strange I've seen some issues restarting the client fixed. But I didn't take note of exceptions.

Problem is, this happened on Windows.

**Comment by PJB3005** [comment]
Logged bug on dotnet/runtime by the way: https://github.com/dotnet/runtime/issues/60545
