### ISSUE TITLE
Need a way to scale an entity

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#2145]
I'm lazy and need to VV a bunch of stuff right now. Ideally there'd be a method where:
- Sprite is scaled
- Physics fixtures are scaled
- Anything else I didn't think of

Also that this is usable by VV or something. I just want to make a tiny corgi damnit.

**Comment by PaulRitter** [comment]
i think this is of the upmost importance to create good admin ux

also prob should scale maximum interactiondistances n stuff, right?
