### ISSUE TITLE
View Variables (Server Variables) forces server restart

### ISSUE THREAD

**Issue by Streaky-Haddock** [space-wizards/RobustToolbox#2221]
## Description
When a Game Admin opens up certain entries in the Server Variables tab within the View Variables menu, it will trigger a server restart after 5-6 seconds of pressing the entry in question. Which, according to Vera doesn't show up on grafana (I hope you know what that means, I don't.)

Reproduce (replicated on eu 1 spider on zero pop):

Normal Version

1. observe
2. spawn pneumatic cannon
3. Open View Variables with right click > debug> View Variables
4. click server variables tab
5.  click inspect button of (R.Sh.Prototypes.EntityPrototype+ComponentRegistry)
6. Click Item (Ref: C.Se.Items.ItemComponent)
7. Nothing happens, wait 6 seconds
8. server dc's and restarts pretty much immediately.

GOOSE VERSION (honk)

1. spawn goose [AI]
2. vv
3. server variables
4. Page 2
5. Recyclable Ref: C.Se.Recycling.Components.RecyclableComponent
6.  Nothing happens, wait 6 seconds
7. server dc's and restarts pretty much immediately

**Screenshots**
![image](https://user-images.githubusercontent.com/93771043/141328568-bdbcfe71-c7f6-495f-aada-831eaf1e0bb2.png)
![image](https://user-images.githubusercontent.com/93771043/141328692-640692ca-f68a-4365-9157-0047608eb3ab.png)
![image](https://user-images.githubusercontent.com/93771043/141328725-4acde97c-8598-4ada-8abe-f54bf91fa707.png)

**Additional context**
I have had client crashes instead of server crashes in the past, particularly when opening goose butcherable. But I wasn't able to reproduce this. It also didnt leave any messages on the client logs, annoyingly enough.

Given the lack of feedback from when it happens, it took me a while to become certain enough it was me who was doing it. I'm a baby admin with no real understanding of how SS14 works or is laidout in the back-end, so I kinda just went through and started pressing all the buttons to see what they contained.

This issue may not be limited to server variables, but I didn't want to keep crashing Spider (EU1) to find out. I'm hoping whoever picks up this issue will be able to deduce what systems are relevant here.

**Comment by 20kdc** [comment]
To me it kinda looks like:
A. VV needs more exception recovery
B. `R.Sh.Prototypes.EntityPrototype+ComponentRegistry` should never be being accessed via VV as it contains a lot of uninitialized components

**Comment by gradientvera** [comment]
>A. VV needs more exception recovery

No, this exception is *already* caught by NetManager. The fact that it somehow crashes the server is real weird though.

>B. `R.Sh.Prototypes.EntityPrototype+ComponentRegistry` should never be being accessed via VV as it contains a lot of uninitialized components

No, VV should be able to handle it cleanly.

**Comment by gradientvera** [comment]
~~Testing locally on RELEASE, I can't reproduce any crashes~~
EDIT: Seems this is inconsistent... Some prototypes do crash it, some do not?

**Comment by Streaky-Haddock** [comment]
> ~Testing locally on RELEASE, I can't reproduce any crashes~ EDIT: Seems this is inconsistent... Some prototypes do crash it, some do not?

This is my experience, which is why it took me so long to report it.

**Comment by Acruid** [comment]
That is scary because every prototype component should be throwing an exception when accessed with VV, because none of them have an Owner entity (as expected).
![image](https://user-images.githubusercontent.com/1685952/142965517-aca99e3b-5225-4f3b-b3ba-3019a9030fe5.png)
(reproduced with pneumatic cannon steps above)

**Comment by PJB3005** [comment]
@Acruid this is a bug in .NET 6: https://github.com/dotnet/runtime/issues/61486

Didn't realize we had this issue open, or I would've linked it earlier.

**Comment by Acruid** [comment]
Resolved in https://github.com/dotnet/runtime/pull/62719.

There have been runtime releases since then (6.0.2 was released 9 days ago), and they explicitly backported it to 6.0.X, so this should be fixed.
