### ISSUE TITLE
Suss out exposing _entTraitDict for transforms

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#2227]
Take WorldRotation for example. To calculate it we continuously need to go through our parent uid + get the transformcomponent for the parent recursively. Every time we get transformcomponent we need to do _entTraitDict[typeof(T)] when we already know we just need the transformcomponents.

Granted exposing the internal workings of this is somewhat dirty it's still worthwhile investigating the benchmarks on using this just for transform stuff.

@PJB3005 any thoughts?

**Comment by Acruid** [comment]
Something like this? https://github.com/Acruid/space-station-14/commit/77be92fc789368efb7bcfb2d9b8dc37f6180b530

**Comment by PJB3005** [comment]
That was basically my idea, yeah.

**Comment by Acruid** [comment]
The query object can also be used for scheduling Systems and read/write locking component types if ECS ever became multithreaded. Yay back to entityquery objects!

**Comment by metalgearsloth** [comment]
https://www.youtube.com/watch?v=rjQtzV9IZ0Q
