### ISSUE TITLE
Move to a different entity ID integer type?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#223]
Currently entity IDs are done using `int`s. Should probably make this like `ulong` or something.

**Comment by PJB3005** [comment]
I'm moving this to ready soon. If somebody has any complaints tell me now. Nobody really seems interested other than a few 👍s.

**Comment by YotaXP** [comment]
Are 4-billion IDs not enough?  What sort of impact would this have on packet sizes?  Why not `uint`?

**Comment by PJB3005** [comment]
`uint`'s definitely fine too, the point about network overhead is a good one though.

**Comment by Acruid** [comment]
Lidgren has (Read/Write)VariableUInt32() that packs the uint into the smallest number of bits at the cost of processor power. Personally I think ulong is overkill, what would the performance be like with over 4 billion entities? Can the engine even support it?

**Comment by PJB3005** [comment]
In practice, if "the engine" is the .NET CLR, then definitely no. Unless you have some sort of ridiculous amount of RAM, so yeah my proposal for `ulong` was pretty silly.

**Comment by clusterfack** [comment]
4 gigabytes of ram only has 4 billion bytes. Are we going to need 1 ID per byte?

**Comment by ZoldorfTheWizard** [comment]
Stick to int for now and as soon as we overflow we can change it to ulongs ;)

**Comment by Acruid** [comment]
Entity IDs are currently stored in an `Int32`. The engine will never be able to run ~4 billion entities at once, so there is no point changing this to a larger capacity type. Closing This.

**Comment by ZoldorfTheWizard** [comment]
but meh data types ლ(｀ー´ლ)

**Comment by PJB3005** [comment]
My concern was mostly with the possibility of entity ID rollover being a headache, not 4 billion entities at once.
