### ISSUE TITLE
1 direction sprites need a way to snap at cardinals

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#2262]
So something like an airlock can snap at 45 degrees to try to face south instead of being able to go upside down. Not really sure on the best way to store this on a component TBH, maybe an enum to override the behavior to act like it has 4 / 8 directions?

**Comment by Acruid** [comment]
This is going to be a property of the sprite component. This would work with the existing 4/8 dir snapping code, but without the layer changes. Sounds good to me.
