### ISSUE TITLE
Word wrap measurement bug

### ISSUE THREAD

**Issue by Acruid** [space-wizards/RobustToolbox#2356]
The text is not supposed to overlap the scrollbar, and text editors will create the newline *after* the space character so that it isn't at the front of new line (space before the word lazy).

![image](https://user-images.githubusercontent.com/1685952/146654837-ad7653ab-187c-44f0-bfd5-0b9906c1f563.png)

Linked to https://github.com/space-wizards/RobustToolbox/issues/2349

## How to reproduce
* Get into game
* Type long string with spaces into chatbox that causes a word wrap
* resize chatbox until this bug shows

**Comment by Efruit** [comment]
> The text is not supposed to overlap the scrollbar,

From https://github.com/space-wizards/space-station-14/commit/24304324452a2ea07c8762c956f41d01344f25c3:
![Screenshot from 2021-12-19 04-36-39](https://user-images.githubusercontent.com/602406/146670292-61d84a0a-b599-46dc-8a65-1b60b2d62a0b.png)

In that regard, the behavior is identical to before #2213.

> text editors will create the newline after the space character so that it isn't at the front of new line (space before the word lazy)

Will be addressed shortly in #2352.

**Comment by Efruit** [comment]
Fixed in #2352@https://github.com/space-wizards/RobustToolbox/pull/2352/commits/47854f318fe3b02646320649c151f45b889b55af

**Comment by Efruit** [comment]
OBE #2363
