### ISSUE TITLE
Map inadvertantly getting destroyed

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#2364]
Somehow the map still exists but mapdestroyed is called which removes the movebuffer for that particular map.
Previously this was just tryget and ignored but somewhere else something is going funky.
![image](https://user-images.githubusercontent.com/31366439/146881628-eabaae23-b885-4b25-a798-145be56b2ca8.png)

**Comment by ElectroJr** [comment]
> Priority: 1-Urgent

>  Dec 21, 2021

I'm gonna guess this has been fixed at some point or is just no longer relevant.
