### ISSUE TITLE
`RenderTarget`s can't have their clear color set at all.

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#2381]
Setting `IUserInterfaceManager.RootControl.BackgroundColor` doesn't help, of course.
This should default to clearing to black, and allow content to change it as needed...
Robust Pong screenshot:
![image](https://user-images.githubusercontent.com/6766154/147662826-c77beb4e-613e-43df-9231-4986b21bfa88.png)
See: https://github.com/space-wizards/RobustToolbox-Examples-Pong/tree/2021-12-20-updated-to-0.8

**Comment by PJB3005** [comment]
Fixed by 989669791925ccaedb3f6fb40ab14d9279f5582a
