### ISSUE TITLE
Transform parent/grid doesn't update when a grid-tile is deleted.

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#2393]
So I'm not 100% sure of what the issue is here, but I think the title is correct.

To see the problem:
- spawn in entities on a grid
- make some grid tiles into space
- entity is still parented to grid despite not being on grid?

This causes:
- entity lookups can behave unexpectedly
- if you enter and leave PVS, the client-side transform is **not** parented to a grid. can this seems cause extreme client-side lag (constant resetting of predicted entities or something?)

There is also a related issue. Currently if you remove the last tile of a grid (via admin, explosion, or depressurization), the grid is deleted along with any entities on it (including any ghosts). Unless the whole grid was intentionally deleted, the entities should be left floating in space (or flying away from an explosion). If entities are properly de-parented as tiles are removed, this shouldn't be an issue.

## Video ##

https://user-images.githubusercontent.com/60421075/148001088-b305c364-8f7d-4799-b525-fcb604ae7e54.mp4

**Comment by metalgearsloth** [comment]
Thought I left the TODO in but apparently not.

Relevant line https://github.com/space-wizards/RobustToolbox/blob/069ebbc8d094caf0d83fb56488c714afea7c58e8/Robust.Shared/GameObjects/Systems/SharedTransformSystem.cs#L60

I couldn't think of a good way to deparent any entities intersecting at the time.

Grid deletion being unique should be a separate issue because 90% of the time you want to also delete all the children.

**Comment by ElectroJr** [comment]
> I couldn't think of a good way to deparent any entities intersecting at the time.

Assuming `GridTileLookupSystem` is still being removed, I guess you would just have to get the box for the tile and use `EntityLookup` to get all non-anchored entities? If that works, I'm happy to open a PR to try do that.

> Grid deletion being unique should be a separate issue because 90% of the time you want to also delete all the children.

The only instance I can think of where you don't want delete entities on a grid when deleting the grid is when the grid deletion is incidental as a result of removing the last tile on a grid. But if the transform-parenting stuff is fixed, and as long as `mapManager.TileChanged` / the de-parenting gets invoked before the grid is actually deleted this isn't a problem anymore, so I'm not sure if it needs to be a separate issue.

**Comment by metalgearsloth** [comment]
> Assuming GridTileLookupSystem is still being removed, I guess you would just have to get the box for the tile and use EntityLookup to get all non-anchored entities? If that works, I'm happy to open a PR to try do that.

Yeah it works, my main concern was perf as querying each tile is slow if a bunch are modified. We can just use it for now and see how bad it is on live.

**Comment by metalgearsloth** [comment]
This should be gucci now right @ElectroJr
