### ISSUE TITLE
The Authors retain all copyright to their respective work here submitted.

### ISSUE THREAD

**Issue by mmlac** [space-wizards/RobustToolbox#24]
LOL. This is hilarious. Just stop coding right now, as one pissed off committer will tear your project apart, whether you want it or not.

MIT or BSD, or just don't even bother.
(GPL is useless as well)

**Comment by Heredth** [comment]
>coders

hue

**Comment by theOperand** [comment]
> getting mad over licensing for a dead game

lel
Op 22-jul.-2015 22:01 schreef "Markus Lachinger" notifications@github.com:

**Comment by mmlac** [comment]
Who's getting mad? :)

**Comment by volundr-** [comment]
![Eat a bag of dics :+1:](https://i.imgur.com/gM6o4Zf.gif)
