### ISSUE TITLE
Document current world and positioning system

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#240]
It's in for a refactor but it needs docs.

**Comment by Acruid** [comment]
Right now CluwneLib uses a System.Single (float) for world coordinates. One 'tile' is 1.0f world units, regardless of size of tile in pixels. Any system that is converting between world units and another space should provide proper transform functions/matrices.

CluwneLib currently depends on MapManager to define 1 tile = 32px. This will need to be removed in the future, and other systems should not depend on this constant.

**Comment by Acruid** [comment]
Also see https://github.com/space-wizards/space-station-14/issues/252.

**Comment by Acruid** [comment]
Updated information: https://github.com/space-wizards/RobustToolbox/issues/546#issuecomment-526884320

**Comment by Acruid** [comment]
Done.
https://hackmd.io/@ss14/ByoN-9Igd
