### ISSUE TITLE
Vismask issues / ghost pointing

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#2400]
Currently all players can see where ghosts are pointing. Also, all players get sent information about ghost entities, which AFAIK they're not supposed to get. I think problem started in #2312 and has to do with PVS stuff, so I'm not at all sure how to fix, or what part of this is the **actual** problem.

AFAICT the issue results from a combination of:
- vismask gets given a default value of `1`, and a ghost's `VisibilityComponent` cannot prevent this.
- the final vismask is the additive combination of the entity's vismask and any transform parent.
- `PVSSystem` only considers an entity invisible if there is zero overlap between the entity & the client's eye's vismask.
 
As a result, all players get sent ghost & ghost-pointing-arrow entities, the ghost sprites are set as invisible by client-side code, but nothing does the same for the arrow entities. Instead of making the arrows invisible in client-side code, I think the right thing is to just not send them in the first place, like was being done previously?

Just changing it so that vismask defaults to 1 only if the entity has no `VisibilityComponent` doesn't solve the problem due to the parenting: as long as any parent is visible, all children get sent. I assume the logic is supposed to be so that if a client cannot see the parent-entity, don't send the children as otherwise you get errors. 

So is the `visMask & metadata.VisibilityMask) == 0` check in `PVSSystem.TryAddToVisibleEnts()` meant to be a `(visMask & metadata.VisibilityMask) != metadata.VisibilityMask`. I.e., instead of requiring that the observing client matching at least one visibility layer, require them to match all of them? That way the entity won't get sent as long as the entity, or some parent, has a vismask that is missing from the eye.

Does the vismask+parenting calculation have to be updated, or does the PVSSystem need to be updated or something else altogether?

**Comment by metalgearsloth** [comment]
I think you're right on (visMask & metadata.VisibilityMask) != metadata.VisibilityMask from what I remember of my original PR (pre-paulVS).
