### ISSUE TITLE
Set up automatic online documentation.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#242]
I'm thinking about using Sandcastle for it right now.

**Comment by Cyberboss** [comment]
If you're fine with Doxygen (https://tgstation.github.io/tgstation-server/) I can do this

**Comment by PJB3005** [comment]
Personally I was looking at docfx but if you wanna set it up go ahead.

**Comment by AJCM-git** [comment]
We are using [HackMD](https://hackmd.io/@ss14) now, can this be closed?

**Comment by SweptWasTaken** [comment]
Yeah

**Comment by PJB3005** [comment]
This was referring to API documentation, which is something else.

**Comment by SweptWasTaken** [comment]
I accidently sahit close and comment

**Comment by PJB3005** [comment]
Eh it's probably fine to close it. I don't currently see anybody ever needing this.
