### ISSUE TITLE
Remove ComponentFamily?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#250]
Currently, certain components are classified with a certain `ComponentFamily`. Families classify whether a component is a rendering component, transform, etc... on a fundamental level. Issue is there's no actual meaning in relation to types.

Personally I think we should remove them and replace them with generic interfaces that handle their function. Discuss.

**Comment by ZoldorfTheWizard** [comment]
```C#
Entity.GetComponent<TransformComponent>(ComponentFamily.Transform).TranslateTo(pos); 
```
It could be shortened to
```C# 
Entity.GetComponent<Transform>( ).TranslateTo(pos);
```
I agree completely

**Comment by PJB3005** [comment]
More specifically, change it to `Entity.GetComponent<ITransform>( ).TranslateTo(pos);`

All components should be identified by a shared interface like `ITransform`, `IRenderingComponent`, etc...

**Comment by PJB3005** [comment]
I'm gonna work on this  tomorrow, but I'm gonna leave this here. We decided on manual registration alike IoC:
```cs
componentManager.Register<ClientTransformComponent>("transform"); // Register component to transform type for prototypes.
componentManager.RegisterRef<ClientTransformComponent, ITransformComponent>();
componentManager.RegisterRef<ClientTransformComponent, IClientTransformComponent>();
```

**Comment by ZoldorfTheWizard** [comment]
:+1:
