### ISSUE TITLE
Replace SFML

### ISSUE THREAD

**Issue by ZoldorfTheWizard** [space-wizards/RobustToolbox#251]
Working on Robust Engine

**Comment by optimumtact** [comment]
Not invented here syndrome?

**Comment by gbasood** [comment]
SFML gave us many issues that were, I think, mostly fixed when a new binding was written.
But I'm not sure it's working on anything but Windows now.

**Comment by ZoldorfTheWizard** [comment]
something something oranges something goofball something shitpost

**Comment by optimumtact** [comment]
Would you care to elaborate on how attempting to rewrite the SMFL lib with your own cross platform library is a good idea, given the small size of your team?

**Comment by ghost** [comment]
@optimumtact because it's easier than trying to get half-dead lib to work and not crash every fucking system.

**Comment by gbasood** [comment]
If you'd like to maintain SFML and all the bindings between by all means, go ahead
But since you have no intention on contributing we're doing this

**Comment by Iamgoofball** [comment]
@Silvertorch5 you summoned me?

**Comment by ZoldorfTheWizard** [comment]
something something Licensing something

**Comment by ZoldorfTheWizard** [comment]
something something grumble godot replaced sfml for now something period.

**Comment by PJB3005** [comment]
Not done yet.

**Comment by PJB3005** [comment]
Gottem.
