### ISSUE TITLE
Per-client PVS view size is needed

### ISSUE THREAD

**Issue by ike709** [space-wizards/RobustToolbox#2526]
BYOND/OD has a client variable to change the view size.

**Comment by Acruid** [comment]
Also useful if we want the view to zoom out while piloting a shuttle.

**Comment by Acruid** [comment]
Related to https://github.com/space-wizards/RobustToolbox/issues/2527, not everyone will want the same size window.

**Comment by metalgearsloth** [comment]
Another potentially useful feature is extending the viewport by the viewer's velocity to also facilitate faster shuttles that don't have pop-in.
