### ISSUE TITLE
PVS view size needs to support rectangles

### ISSUE THREAD

**Issue by ike709** [space-wizards/RobustToolbox#2527]
SS13 widescreen when

**Comment by Acruid** [comment]
Does it really, or can you just make the square bigger?

**Comment by ike709** [comment]
@Acruid It does really. Treating a `view` of 21x15 as 23x23 (since we do view + 2 offscreen turfs in each direction) would result in *a ton* of extra entities needing to be streamed on top of our already-huge number of entities that are already over the default PVS budget at 15x15.

OD is pushing the entity count a lot harder than SS14.

**Comment by Acruid** [comment]
What would you want the public/content API to look like? `IServerGameStateManager.SetViewBounds(Box2)`? Right now nothing is really exposed to content for this, so what would be the most useful to you?

**Comment by ike709** [comment]
> `IServerGameStateManager.SetViewBounds(Box2)`

I mean something like that would be fine as long as it'd also include a client arg to deal with #2526
