### ISSUE TITLE
Submodule handling?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#255]
To fix #206 I made [`space-wizards/ss14.shared.bsdiff`](https://github.com/space-wizards/ss14.shared.bsdiff) to replace bsdifflib in C#. Problem is as follows: It's a separate repo (and I'd like to keep it this way to separate the Rust code from the main repo but keep the Rust code by its FFI buddy C#)

The problem with submodules is that they don't auto-update. Yay! Thanks git they're god damn useless without this.

To fix this, we need post checkout and pull hooks. To make all of this easier I would also VERY much like to suggest that we make Python 3.5+ a hard dependency used in the build process because for the love of god there's no way to maintain this otherwise.

My original plan was to use msbuild, but this didn't work because msbuild doesn't build missing projects if they get created mid build. Problem!

We can probably use git hooks in some way, I guess?

I need suggestions seriously this is blocking #206.

**Comment by ZoldorfTheWizard** [comment]
P y t h o n.

**Comment by PJB3005** [comment]
The Python script in #275 fixes this. Take it from there when we set up the content repo.
