### ISSUE TITLE
Client Gamestate sequencing cannot handle packet loss

### ISSUE THREAD

**Issue by Acruid** [space-wizards/RobustToolbox#2553]
The game freezes/stutters when there is packet loss, even though the state buffer is not empty.

How to reproduce Argentinian network conditions:
* `net_graph 1`
* `cvar net.interp_ratio 3`
* `cvar net.fakelagmin 0.15`
* `cvar net.fakelagrand 0.01`
* `cvar net.fakeloss 0.05`
* `sudo cvar net.fakelagmin 0.15`
* `sudo cvar net.fakelagrand 0.01`
* `sudo cvar net.fakeloss 0.05`

Run around the station, watch the client freeze even though the net buffer at the bottom of the netgraph does not empty (red ticks). The client is expected to be able to interpolate over multiple missing game states to a future server state. Notice the large `TickTimingAdjustment` fluctuations in the F3 menu, related to #2552. While packet loss and RTT jitter may cause rubberbanding and mispredicts, it should not be freezing the client.

This may be related to the client not implementing state extrapolation.

**Comment by ElectroJr** [comment]
Might be related to the server bulldozing acked states. [See discord discussion](https://discord.com/channels/310555209753690112/770682801607278632/962637168751300618).
