### ISSUE TITLE
Make our own DMI alternative? 

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#256]
Right now sprites in game are direct references to a PNG on disk. To have multiple states available to things like door icons changing on open, the render able component needs to load these before hand in the component definition.

Its kinda clunky, especially with animated states.

Personally I think we should keep the idea behind the DMI format. I already have a spec for a DMI-like format that isn't stupid, GitHub and VCS friendly and more easily workable. The spec can be seen [here](https://github.com/NanotrasenInc/YASSS13RTWCF/blob/master/docs/rsi/rsi.md). There's Python and Rust tooling for it already and writing a C# library can't be hard.

@Silvertorch5 you're the rendering man, opinions?

We should however consider how this'll fit into the current rendering system, including abstractions.

**Comment by theOperand** [comment]
Is there an existing format that could serve here? If there is something, it seems better than making our own spec.

**Comment by PJB3005** [comment]
I've tried looking but could find absolutely nothing.

**Comment by ZoldorfTheWizard** [comment]
we can make our own texture atlas format

**Comment by Iamgoofball** [comment]
Or just use DDS like sane people and don't reinvent the wheel

**Comment by PJB3005** [comment]
@Iamgoofball absolutely proprietary.

**Comment by Iamgoofball** [comment]
And it's also an industry standard, stop stallman spergin

**Comment by Quantomicus** [comment]
We don't need you Goofball, step aside. 


![](https://www.shitpostbot.com/resize/1108/400?img=%2Fimg%2Fsourceimages%2Fangery-blob-5906607c3ef5c.png)

**Comment by ghost** [comment]
@Iamgoofball https://github.com/NanotrasenInc/RSI.py

**Comment by RemieRichards** [comment]
If RSI is what's used in the end, here's a Json Schema to validate it:
(or atleast a 'version 1')
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
        "title": "RSI Image Format Validation Schema V1",
	"description": "Robust Station Image",
	"type": "object",
	"definitions": {
		"size": {
			"type": "object",
			"properties": {
				"x": {"type": "integer", "minimum": 0},
				"y": {"type": "integer", "minimum": 0}
			},
			"required": ["x","y"]
		},
		"directions": {
			"type": "integer",
			"enum": [1,4] //a 1 or a 4
		},
		"state": {
			"type": "object",
			"properties": {
				"name": {"type": "string"},
				"select": {
					"type": "array",
					"items": {"type": "string"}
				},
				"flags": {"type": "object"}, //To be de-serialized as a Dictionary
				"directions": {"$ref": "#/definitions/directions"},
				"delays": {
					"type": "array",
					"items": {
						"type": "array",
						"items": {"type": "number", "minimum": 0} //number == float
					}
				}
			},
			"required": ["name","select","flags","directions"] //'delays' is marked as optional in the spec
		}
	},
	"properties": {
		"version": {"type": "integer", "minimum": 0},
		"size": {"$ref": "#/definitions/size"},
		"states": {
			"type": "array",
			"items": {"$ref": "#/definitions/state"},
			"minItems": 1
		}
	},
        "required": ["version","size","states"]
}
```

Which was used to validate this example (only modifications from the main RSI example is an example flag, couldn't think of an example selector)
```
{
    "version": 1,
    "size": {
        "x": 32,
        "y": 32
    },
    "states": [
        {
            "name": "hello",
            "select": [],
            "flags": {
              "isMovement": "true"
            },
            "directions": 4,
            "delays": [
                [1, 1, 1],
                [2, 3, 4],
                [3, 4, 5],
                [4, 5, 6]
            ]
        }
    ]
}
```
You can play with the above here: http://www.jsonschemavalidator.net/

Json.NET is free to use commercially as MIT and the most popular .NET library on nuget.
<del>Json.NET Schema isn't free (except AGPL3 with 1000 validations per hour, which if content gets large could cause issues) but licenses are $99 for Indie Companies (less than 10 employees, nobody's getting paid so maybe that one would work?) or $149 for a business plan (10+ employees)</del>

<B>Edit:</b>
Fear not! the Schema spec Json.NET implements is an open specifcation, that has an MIT implementation: https://github.com/RSuter/NJsonSchema so both Json.NET and NJsonSchema can be used for json serialising/deserialising and validation.

**Comment by ZoldorfTheWizard** [comment]
This is going to be a part of RobustEngine™ so we can remove ~~kebab~~ msspriterenderer

**Comment by PJB3005** [comment]
Just an FYI. I have a quick dirty RSI loader coded in C# on my fork, but haven't integrated it yet.

**Comment by Acruid** [comment]
We will deal with merging the @PJB3005 RSI loader after the Godot branch is merged.

**Comment by PJB3005** [comment]
Alright time for this stuff.

**Comment by PJB3005** [comment]
I'm gonna close this and make an issue about SpriteComponent.
