### ISSUE TITLE
PVS: parents in chunkcaches are not always ensured to be sent

### ISSUE THREAD

**Issue by PaulRitter** [space-wizards/RobustToolbox#2561]
scenario:
- parent is (new)entry
- child is stayedchanged (the change being the parenting to the new parent)
- budget is already full once it reaches the parent in the iteration

what happens: parent get skipped bc of insufficient budget, child update gets sent bc the budget doesnt care about changes. we have just sent an entity without sending its parent.

this one is really hecking annoying, and i dont know how to fix it rn, but i fear it will include a complete rethinking of how i do chunkcaches rn and maybe even a less performant datastructure :(

**Comment by metalgearsloth** [comment]
shitty bandaid would be nuking an entity from the lastseen any time a parent changes.
