### ISSUE TITLE
Allow content to specify files to be included in the ACZ zip

### ISSUE THREAD

**Issue by ike709** [space-wizards/RobustToolbox#2579]
OpenDream needs to be able to include the assets from the SS13 repo it's compiling & running. Ideally we'd be able to specify a list of file paths rather than a directory, so we aren't sending unnecessary stuff like DM code files.

I might work on this soon but my schedule is a bit hectic the next few weeks so I'm opening this in case I forget or someone else wants to do it.

**Comment by wixoaGit** [comment]
This can be closed
