### ISSUE TITLE
IsFirstTimePredicted issues on live

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#2596]
Potentially related to https://github.com/space-wizards/RobustToolbox/issues/2553

How to replicate:
- Checkout https://github.com/space-wizards/space-station-14/pull/7060
- No matter what you do it sounds all good locally
- Merge to master
- Footstep sounds getting spammed because StepSoundDistance on the client accumulates very fast (which means IsFirstTimePredicted is probably returning true when it shouldn't).

**Comment by Acruid** [comment]
If you find any way to reproduce this locally, please post it here.

**Comment by ElectroJr** [comment]
IIRC was related to physics doing stuff outside of "normal"/server ticks. Probably wasn't a problem locally because server & client were both running 60tps & fps.
