### ISSUE TITLE
Audio should avoid physics raycasting whenever physically possible.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/RobustToolbox#2633]
This means it should likely keep it's own audio grid data and only use physics casts when traversing space or areas on the grid with complex occlusion geometry.
This is the main performance sink for SS14's ambient audio.

**Comment by metalgearsloth** [comment]
Would rather make raycasts faster (which there is a pending PR for) than store yet-another-tilemap. We also got audio tickrate too.
