### ISSUE TITLE
FollowerSystem can crash the game in some instances

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#2718]
It's not following's fault afaict but it exposes a lot of bugs with parent change ordering that we kinda ignored for a long time until now.

![image](https://user-images.githubusercontent.com/31366439/162715208-dce5c2d9-ccc5-42ce-b844-fec43bbac31e.png)

At this point may just need to flowchart the entire entity initialisation / shutdown code flow just to figure out where the bugs are occurring.

**Comment by gradientvera** [comment]
Kinda relevant: https://github.com/space-wizards/RobustToolbox/issues/2591

**Comment by metalgearsloth** [comment]
![image](https://user-images.githubusercontent.com/31366439/162989200-d92f7856-b750-4fb6-8509-775b0fbae6e1.png)

Grid deleted 37 minutes in

![image](https://user-images.githubusercontent.com/31366439/162989311-cf438c38-3ce7-40fb-bcf8-f791ffaebe32.png)

Explodes at almost 39 minutes

So somehow it is trying to attach to something that's been deleted a long time.

**Comment by metalgearsloth** [comment]
90% sure it's fixed in https://github.com/space-wizards/RobustToolbox/pull/2959
