### ISSUE TITLE
SoundSystem/AudioSystem

### ISSUE THREAD

**Issue by gradientvera** [space-wizards/RobustToolbox#2730]
Also see #2544.
As discussed on the March 5th 2022 maintainer meeting, the SoundSystem/AudioSystem APIs should be revamped.

- The current API leads to easy errors using the wrong overload, causing audio to be played globally instead of following an entity.
- We should remove the overloads, and instead have methods with easy to distinguish names.

**Comment by Acruid** [comment]
Sounds good. There was no grand design with the SoundSystem API when I wrote it, the only goal was to get *something* into a shared context.

**Comment by ElectroJr** [comment]
#4421
