### ISSUE TITLE
VVing grids broken in SS14.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/RobustToolbox#2770]
Simply throws a lineedit error in console and dies.

**Comment by PaulRitter** [comment]
what throws the error? opening the window? editing a box for a gridid? needs more details

**Comment by moonheart08** [comment]
> what throws the error? opening the window? editing a box for a gridid? needs more details

Going to server components causes it to fail to load the UI and throw the error.

**Comment by metalgearsloth** [comment]
@ShadowCommander

**Comment by ShadowCommander** [comment]
> > what throws the error? opening the window? editing a box for a gridid? needs more details
> 
> Going to server components causes it to fail to load the UI and throw the error.

So, LineEdit.Text is non-nullable, but VV sends it null sometimes, so we either need to have VV not send null or change LineEdit to handle null strings.
