### ISSUE TITLE
nvorbis allocates a lot

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#2806]
Just fly across the station as an aghost and you'll see; from all of the ambient audio streams.

**Comment by PJB3005** [comment]
Audio isn't streamed though, so this should only happen on first load.

**Comment by metalgearsloth** [comment]
> Audio isn't streamed though, so this should only happen on first load.

Would it be a bad idea to cache it when loading the game?

**Comment by PJB3005** [comment]
Yes because audio is so huge that it'd waste too much memory.

**Comment by metalgearsloth** [comment]
F
