### ISSUE TITLE
Rename engine?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#284]
Currently the engine is called `SS14`. @Acruid raised an interesting point that the naming could be better, especially in relation to the content assembly.

So should we rename the project?

Right now we have `SS14.*` for engine and `Game.*` for the content assembly. Maybe we should rename engine to `Engine.*` or `Robust.*` and then have content be `SS14.*` or `Content.*`.

Edit idea from @yclatious in Discord: calling the engine `Toolbox.*`

**Comment by ZoldorfTheWizard** [comment]
Robust is trademarked in RobustEngine duh
I will have the dreaded @Iamgoofball write me a license and represent me as my space lawyer /s

SS14.* and Content.* is my vote.

**Comment by ghost** [comment]
Call it WITHYN as an opposite of BYOND
__________________________________

Jokes aside Toolbox.* is my vote

**Comment by clusterfack** [comment]
Construct your net dream CYNT

**Comment by RemieRichards** [comment]
Fulfil your creative knowledge FYCK

**Comment by PJB3005** [comment]
Bikeshed painted.
