### ISSUE TITLE
Collision API: how?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#286]
So we have a collision system, and it definitely works. Problem is the API is a mess to say the least.

There's 3 components at play:

* `CollidableComponent`
* `HitboxComponent`
* `ColliderComponent`

First of all **the server has no collision detection at the moment.**
The server side API makes sense though:
* `CollidableComponent` declares that it can be collided with.
* `HitboxComponent`: declares the hitbox for the entity.

The client...
The client has a `Collidable`, but it's unused except for debug drawing. `HitBox` does the same as on the server. `Collider` is unique to the client, and does everything else related to collision. It uses the hitbox from `Hitbox`, or generates it based on the size of the attached `IRenderable` component (which doesn't work, regression in #281).

So how do we clean this up?

Personally I think we should probably unite all of them into one single component.

**Comment by YotaXP** [comment]
> or generates it based on the size of the attached IRenderable component (which doesn't work, regression in #281).

I argue that it never should have.  The server should have no knowledge of what stuff looks like.  Just hard numbers declared in the entity definition.

**Comment by UristMcDorf** [comment]
@YotaXP That puts a bit of extra routine work (and as such room for error) on the spriters and people adding content. There should be some kind of a default hitbox function working off the sprite; but maybe it doesn't need to be done by the running server but rather some script that runs whenever server starts and makes hitboxes for all the things which don't have one but need it.

**Comment by PJB3005** [comment]
Yeah sprite based hitboxes are still a decent idea.

**Comment by UristMcDorf** [comment]
As for merging, I am not sure merging colliding and hitbox would be a good idea - hitboxes can be used for other things such as trigger zones, plus there should be the ability to make a collider use multiple hitboxes if you want them to cover a shape other than a rectangle.

**Comment by PJB3005** [comment]
@UristMcDorf the first case actually has a component on the client but I didn't bother mentioning it because it was unused, there's a `Triggerable` component which is a `Collidable` but without bumping.

As for the second, honestly we should worry later.

**Comment by UristMcDorf** [comment]
@PJB3005 Uh, shouldn't it be a server component? Considering triggering deals with game logic.

**Comment by UristMcDorf** [comment]
As an entity designer I expect to be able to do this:

![image](https://user-images.githubusercontent.com/9199940/28632749-3d201fde-723a-11e7-87f8-9d034b8b5bee.png)

Where red is the object's sprite, green is trigger zone 1, blue is trigger zone 2 and black is a collider combined of two hitboxes. If your system can do that, it's all fine. What I'm thinking of is have Collider/Trigger be the same component (actual detection of whether the objects should avoid overlapping or not on collision should be done by the component that handles movement, probably) which has a list where you can put hitbox components from the entity. And Hitbox components are basically defined by just their width, height, x offset and y offset.

**Comment by PJB3005** [comment]
Honestly it might just be easier to fix the slave mover so parenting is easier, and then just use multiple entities like unity.

**Comment by PJB3005** [comment]
@Acruid Any opinion here?

**Comment by Acruid** [comment]
The best course of action is to just mimic the architecture of Godot or Unity and their component systems. These have already been demonstrated to work, so there is no point reinventing the wheel. As for specific API calls, it will prob be a combination of SS13 and industry standards. The physics engine backend will prob be Bullet.
