### ISSUE TITLE
What to do with the EntityManager's event system?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#287]
The entity manager has an even system. It allows something to subscribe to a certain type of events, and then anything can raise an event of that type and you'll receive it.

Problem: nothing uses it. Zero. There's two `RaiseEvent` calls (input and clicking code) but nothing listens. Having this kind of system is definitely useful, but I'm doubting its usefulness in an ECS.

What do we do with it?

**Comment by clusterfack** [comment]
The interaction system listened

**Comment by PJB3005** [comment]
Ok I guess it can be kept, but honestly the interaction system's use for it felt pretty poor.
