### ISSUE TITLE
Cannot send anything but primitives over component network messages.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#288]
Components can send messages to their counterparts over the wire. These messages are limited to what's serializable [here](https://github.com/space-wizards/space-station-14/blob/master/SS14.Client/GameObjects/ClientEntityNetworkManager.cs#L96), so using custom data structures is out of the question.

Of course, we should probably make things like structs possible. Problem is *how*?

Easiest would probably to use `NetSerializer` for it, with a custom network data type for types serialized like this. This might be slow and bloated however.

The other option is to require registration of the message types ahead of time, using a shared interface so that these custom messages can be understood on both ends. I think this might be the best solution. Any input @Acruid?

**Comment by YotaXP** [comment]
Could put methods on the struct to serialize to or from an `IEnumerable<object>`.  Instead of sending the type information through the network, just have the deserialization code verify that all the primitive types are in the correct order.  Maybe include a `NetworkDataType.EndOfStruct` in the message to help catch edge cases.

**Comment by PJB3005** [comment]
The problem is that then you need to have a decoding schema server side.

On second thought maybe we need that anyways the current system's a mess.

**Comment by PJB3005** [comment]
We could fix this with `NetSerializer`. Would instantly solve all our trouble.

**Comment by Acruid** [comment]
Resolved by #528, component messages now use NetSerializer.
