### ISSUE TITLE
Compose key doesn't work in textboxes

### ISSUE THREAD

**Issue by Veritius** [space-wizards/RobustToolbox#2893]
## Description

I dunno, could be useful.

**Reproduction**
Try using the compose key in chat.

**Screenshots**

**Additional context**
might be an engine issue idk

**Comment by PJB3005** [comment]
This is a Linux specific problem. Both Windows and macOS handle this fine, the problem is that Linux developers decided these kinds of input systems should be implemented in the GUI toolkit.

If you'd like to see this fixed, go write a Wayland spec or something. This isn't our problem to fix.
