### ISSUE TITLE
Access attribute suggestions

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#2936]
Two issues came up when working on space-wizards/space-station-14/pull/8747:
- Classes defined inside of friends should probably automatically also be friends.
  - E,g, the status control was private to CrayonSystem. It should automatically have been a friend, instead of having to make it public and declaring it as a friend.
- readonly methods should probably not require execution permissions
  - E.g., the `Color.ToHex()` method has the readdonly keyword, meaning it makes no changes to the actual color and just returns a string. It could basically just have been a getter instead, in which case the current access checks would have allowed it.
  - If we're being pedantic, getter methods that are not marked as read-only probably should require execute permissions. Though maybe it's too much of a hassle to have to correctly mark all the read only getters.

**Comment by ElectroJr** [comment]
Actually that PR is still failing the access checks?

I think its because the `StatusControl` there is a friend of `CrayonComponent` but not `SharedCrayonComponent`? Help. @Zumorica

**Comment by gradientvera** [comment]
> * Classes defined inside of friends should probably automatically also be friends

No, I'd rather people make that explicit.

> readonly methods should probably not require execution permissions

yes, we already have this, with the `[Pure]` attribute...
