### ISSUE TITLE
I want to contribute Space Station 14 development

### ISSUE THREAD

**Issue by elwray** [space-wizards/RobustToolbox#30]
But I really confused. What repository I must to choose. For now I see that space-wizards/space-station-14 repository is outdated and the lastest commits from Silvertorch5/space-station-14 not merged into it. Thanks for help. I see that volundr- has own fork.

**Comment by PJB3005** [comment]
If you haven't already, join the IRC channel: #spacebus@irc.rizon.net (no that's not supposed to be an e-mail adres)

**Comment by elwray** [comment]
Ok. Thanks for quick reply!
