### ISSUE TITLE
There is no possibility to configure Discord Rich Presence

### ISSUE THREAD

**Issue by KIBORG04** [space-wizards/RobustToolbox#3005]
I mean https://github.com/space-wizards/RobustToolbox/blob/master/Robust.Client/Utility/DiscordRichPresence.cs file. 

Everything in it is hardcoded, cannot be localized and editable. 

![image](https://user-images.githubusercontent.com/26389417/176473816-d5057c6a-ec9b-4a2f-8885-221496890c17.png)

in addition, for some reason, a big picture means the engine, and not the game itself

**Comment by gradientvera** [comment]
I don't think that could be sandboxed sanely.
Instead, we should make this opt-in and easily configurable from content.

**Comment by PJB3005** [comment]
Yeah this should just be made configurable.
