### ISSUE TITLE
Remove resource pack password code.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#305]
Seriously that code is never gonna be useful for anything.

**Comment by ZoldorfTheWizard** [comment]
what if a code base wants to go dark and never release the art

**Comment by PJB3005** [comment]
Then it only provides false security because anybody can crack it. The
client gets sent the password to open it, so modifying your client to say
the password is trivial.

**Comment by UristMcDorf** [comment]
Well the code base could release pre-compiled binaries the players have to use that still have the password buried somewhere inside them that isn't available in the open code.

**Comment by PJB3005** [comment]
That'd be violation of the GPL for one thing, and still incredibly easy to
circumvent with a decompiler.

**Comment by UristMcDorf** [comment]
Ah, okay.

**Comment by UristMcDorf** [comment]
Still, at least the password'll dissuade some. It's not security in the sense that nobody'll get the stuff you don't want them to, but at least most people won't.

**Comment by PJB3005** [comment]
I don't think it's worth the code maintenance hassle.
