### ISSUE TITLE
serv3 doesn't error on duplicate prototype IDs

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3079]
SS14 has several that have gone unnoticed, the most recent one is BoxSurvival.

**Comment by PaulRitter** [comment]
prototypemanager issue, not serv3 but:

uhhhh it *should* already complain, see: https://github.com/space-wizards/RobustToolbox/blob/786ecdb8b1308ebf68e9d00dfaf465630b33629e/Robust.Shared/Prototypes/PrototypeManager.cs#L672-L675

**Comment by metalgearsloth** [comment]
It for sure does not complain, it just seems to bulldoze it atm.

See https://github.com/space-wizards/space-station-14/pull/10037

There was BoxSurvival under general.yml and under emergency.yml
