### ISSUE TITLE
Client broadphase exception

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3094]
Apparently beridot loaded in box on the same map far away. Might be related to some handlestate nonsense.

Relevant screenshot:
![image](https://user-images.githubusercontent.com/31366439/182028095-abc51289-66fa-4391-b750-97bcacab5910.png)

**Comment by ElectroJr** [comment]
Given the significant broadphase changes, this may have been fixed somewhere along the way? So closing for now.
