### ISSUE TITLE
One weird trick to spice up your codebase!

### ISSUE THREAD

**Issue by Acruid** [space-wizards/RobustToolbox#333]
[Click here to go to Sonar](https://sonarcloud.io/project/issues?id=ss14&moduleUuids=AVvq1nXhtgcYCvBl42By%2CAVvq1nXitgcYCvBl42CL%2CAVvq1nXltgcYCvBl42EO%2CAVvq1nXvtgcYCvBl42MR&resolved=false&types=BUG%2CCODE_SMELL%2CVULNERABILITY)

Sonar is a program that finds and lists all bugs and issues with the the code in the is project. These issues are all quick fixes and take under a minute to complete, and require no commitment. If you just want to do some quick and casual coding, or are new to the codebase and want to take the tour, these are perfect to work on.

**Comment by PJB3005** [comment]
Should maybe include code smells in that link too.

**Comment by Acruid** [comment]
Updated.

**Comment by ZoldorfTheWizard** [comment]
Needs more Cluwnes

**Comment by Cyberboss** [comment]
Why not just enable fxcop rules? (Assuming you guys use .NET framework)

**Comment by PJB3005** [comment]
I am planning to get rid of sonar since the suggestions it gives are usually pretty useless and nobody uses it.

Also there's a warning about using a deprecated runner and I really don't feel like putting in maintenance effort for it...

**Comment by Cyberboss** [comment]
Also, I recently added the github code scanner under the repo's security tab to TGS and it caught a security issue I wouldn't have otherwise noticed. If it got released I'd have needed to put out a CVE for it.

**Comment by Cyberboss** [comment]
Also the current recommended analyzer set: https://github.com/dotnet/roslyn-analyzers

**Comment by PaulRitter** [comment]
Is this still relevant?

**Comment by SweptWasTaken** [comment]
> 
> 
> Is this still relevant?

No, 99% sure we ditched Sonar. Closing.
