### ISSUE TITLE
Grid rendering sometimes draws non-existent grids. 

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#3410]
https://user-images.githubusercontent.com/60421075/198893161-b2c16a42-cfce-4724-9515-355d1fa756c3.mp4

**Comment by metalgearsloth** [comment]
Probably related to movedgrids being super sussy. Whenever mapmanager gets refactored I want to add a a component for it to maps instead of storing it on mapmanager.

**Comment by ElectroJr** [comment]
Fixed by #4525
