### ISSUE TITLE
RobustMappedStringSerializer should maybe be split?

### ISSUE THREAD

**Issue by ElectroJr** [space-wizards/RobustToolbox#3475]
It would be nice if the actual serializer part of `RobustMappedStringSerializer` were split off from all the networking/handshake stuff. In particular, It would be nice if single player games could specify their own `MappedStringDict` for deseralizing specific data that was written using `IRobustSerializer`.

**Comment by PJB3005** [comment]
> It would be nice if single player games could specify their own MappedStringDict for deseralizing specific data that was written using IRobustSerializer.

Robust serializer is not intended to be a stable serialization format, so no.

**Comment by ElectroJr** [comment]
> Robust serializer is not intended to be a stable serialization format, so no.

The goal was to use it for replays, which only function as long as the replay-client version matches what would otherwise have been a normal client playing on that server. So this would already be inherently "unstable" in terms of loading old data, and isn't really required for what I want. 

Really I just want to be able to use `IRobustSerializable` without the whole server handshake stuff. Unless all `[NetSerializable]` objects are overhauled to be yaml-serializable or something, somehow reusing `IRobustSerializable`  seems like the most reasonable approach.

I'm open to other options, or hearing about whatever approach you used in your old replay demo, but I really cbf making everything yaml serializable.

**Comment by PJB3005** [comment]
Ok yeah that's probably fine, I was thinking of this from like a save/load system.
