### ISSUE TITLE
MapGrid causes map to become unloadable.

### ISSUE THREAD

**Issue by Vordenburg** [space-wizards/RobustToolbox#3523]
1. Follow the instructions under https://docs.spacestation14.io/en/content/mapping#planets either by running `planet` or doing it manually.
2. Save the map.
3. Load it back in.
4. Client crashes with an error like: `[FATL] unhandled: System.InvalidOperationException: UID already taken: 12074`

Manually removing the MapGrid component from the map entity prevents this from happening.

**Comment by metalgearsloth** [comment]
Should be fixed in https://github.com/space-wizards/RobustToolbox/pull/3516
