### ISSUE TITLE
Broadphase exception

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3528]
AFAICT this only ever happens with stopfollowing:

![image](https://user-images.githubusercontent.com/31366439/203697728-1b6153a2-fe3a-435d-bea9-83afabe97498.png)

**Comment by metalgearsloth** [comment]
Okay so to repro something similar:
1. Follow something
2. Delete grid.

There's still a little bit of leaky so I'll take a look.

**Comment by ElectroJr** [comment]
There are similar errors that can somewhat consistently be triggered by pulling something on a grid and then deleting that grid, where entities with null broadphases end up in the map's move buffer.
