### ISSUE TITLE
CEF initializes too early

### ISSUE THREAD

**Issue by ike709** [space-wizards/RobustToolbox#3703]
I know I'll probably have to be the one to fix this but I'm making an issue anyways so I don't forget.

Right now CEF initializes so early that IConfigManager hasn't read the config files yet and we can't use any cvars to set CefSettings. There doesn't seem to be a way to change CefSettings post-init.

This isn't great because OpenDream needs to be able to set the CefSettings and I'm not sure how else to do it besides cvars.

PJB said that CEF init can probably just be moved later.

**Comment by PJB3005** [comment]
Fixed by d6cbdd221c81447abc7fa0da220b13377eaaebac
