### ISSUE TITLE
PVS: caugh exception while generating mail (with explosion and destroyng)

### ISSUE THREAD

**Issue by troit5ky** [space-wizards/RobustToolbox#3787]
## Description

PVS: caugh exception while generating mail (with explosion and destroyng)

**Reproduction**

Spawn fuel reservoir
Hit it
get error in terminal when reservoir do explostion

**Screenshots**

https://cdn.discordapp.com/attachments/1061573811591458896/1075302137732534332/image.png

**Additional context**

commit: b95f37f93c1a9240e52ae3786a71036727ca2f8f
ss14 fork: https://github.com/starcraft-gazers/craft-station-14

**Comment by metalgearsloth** [comment]
Gonna need more details, e.g. commit number, fork, etc.

**Comment by troit5ky** [comment]
> Gonna need more details, e.g. commit number, fork, etc.

Additional context updated

**Comment by troit5ky** [comment]
Thanx, it fixed
