### ISSUE TITLE
No way to get initial values from prototypes

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/RobustToolbox#392]
We need a more generalized method to get properties that a prototype has, possibly by initializing one of the prototypes as an entity and taking it out of the process lists.

This became a problem for me recently as the entityspawnpanel displays the sprite just by the one hardcoded way we have to get the spritename, and then using getsprite for itself. It this particular example would be far easier if I just used the entityprototype's render method and passed it the X and Y it needs to render to. 

But yeah the primary problem is that components may load nondefault parameters for their components which we have no way currently to read.

**Comment by metalgearsloth** [comment]
Was done in serv3
