### ISSUE TITLE
grid detaching is 100% broken now

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/RobustToolbox#3920]
## Description
on lizard any grid refuses to detach
- ruined my ai sat troll
- completely griefed engis shittle, leading to suicide

**Reproduction**
1. find lattice in space
2. detach it
3. same grid ids

**Screenshots**
![15:17:22](https://user-images.githubusercontent.com/39013340/230777969-16ff640a-27ed-4daf-93b1-9fe90783a54e.png)

**Comment by metalgearsloth** [comment]
https://github.com/space-wizards/RobustToolbox/pull/3919

Discord issue https://discord.com/channels/310555209753690112/1093029597563605063

:)

**Comment by deltanedas** [comment]
:rocket:
