### ISSUE TITLE
Entitylookup / context menu issue

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#3924]
Okay so I managed to repro it for once: when I was following an aghost who went to their test map I could no longer right-click the aghost until I left and came back.

**Comment by ElectroJr** [comment]
Its somewhat inconsistent, but can pretty regularly be triggered by sending yourself to your own testing arena. Seems to have nothing to do with ghosts or following.

The client's transform comp's broadphase field is null, but it seems to be fine on the server.
Maybe related to the same grid/transform hierarchy bugs that #3919 was trying to fix?

**Comment by metalgearsloth** [comment]
I wonder if this is also the source of the null broadphase exceptions I get a few times a round on client?

**Comment by ElectroJr** [comment]
Seems to have been fixed by #3919
