### ISSUE TITLE
CBURN can't BURN

### ISSUE THREAD

**Issue by DogZeroX** [space-wizards/RobustToolbox#4060]
They are using flare rounds, doesn't set on fire anymore. If only we had flamethrowers...

**Comment by EmoGarbage404** [comment]
huh. why do incendiary rounds not set things on fire?

**Comment by DogZeroX** [comment]
Apparently it's useless, saw zombies getting shot with flare shotgun rounds, since they are now, actual flares.

**Comment by LordEclipse** [comment]
> huh. why do incendiary rounds not set things on fire?

CBURN doesn't even get incendiary rounds, they get 2 boxes of flare rounds
