### ISSUE TITLE
Inline IMarkupTags aren't positioned properly when the window isn't fully-sized.

### ISSUE THREAD

**Issue by EmoGarbage404** [space-wizards/RobustToolbox#4120]
With a fullscreen window:
![image](https://github.com/space-wizards/RobustToolbox/assets/98561806/6e2df4db-6e83-466d-942c-02550a6a2f01)

With a window not taking up the whole space:
![image](https://github.com/space-wizards/RobustToolbox/assets/98561806/dbdcee5a-3982-4422-a774-1bd1832bfafa)

Notice how the two links embedded in the page, "heyshitass" and "foo" render correctly in line with the rest of the text in the first one, but in the second, are set back too far and clip into the rest of the text.

**Comment by juliangiebel** [comment]
It's caused by the ui scale not being 1 🙃
