### ISSUE TITLE
Rebase SFML as the master branch

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#42]
No work is being carried out in the master branch. There is nothing left in there that is really going to live through the changes that have already been applied to SFML.

We should nuke Master and rename SFML.

**Comment by ZoldorfTheWizard** [comment]
I've used it to check my sfml code against the original code and its a nice piece of history too.
In my opinion I am against nuking it, but we could rename it to gorgon or something and rename sfml as master.

**Comment by YotaXP** [comment]
The `master` branch isn't even Gorgon anymore.  It's at some point after the SFML port.

**Comment by ZoldorfTheWizard** [comment]
that is very true. it was partially merged into master a while back so nuking it would clean that up.

If any of the other collaborators do not object then yota or I will nuke master and rename sfml

**Comment by psykzz** [comment]
Give it a week or so for feedback, I don't expect guys to be checking this daily.

**Comment by psykzz** [comment]
I guess no one has anything against this.
