### ISSUE TITLE
moq is now adware

### ISSUE THREAD

**Issue by ghost** [space-wizards/RobustToolbox#4255]
see https://github.com/moq/moq/issues/1372 and https://github.com/moq/moq/issues/1374#issuecomment-1671011828

RobustToolbox is currently using Moq v4.16.

Moq after v4.20 adds data collection that (for now only) scrapes git credentials. it will sleep on builds where there is no configured git email connected to a GitHub sponsor.

i am _not_ suggesting using something else; only that at a minimum this dependency not be upgraded ≥4.20. [nuget.org packages cannot be trivially overwritten or permanently deleted](https://learn.microsoft.com/en-gb/nuget/nuget-org/policies/deleting-packages), so older versions should be safe.

EDIT: it apparently broke Mac builds, so it is temporarily removed in https://github.com/moq/moq/pull/1375

**Comment by mirrorcult** [comment]
this is why mocking is a mistake

**Comment by azzzertyy** [comment]
https://github.com/moq/moq/pull/1375
