### ISSUE TITLE
Robust.Shared.Timing.Timer has time drift

### ISSUE THREAD

**Issue by TsjipTsjip** [space-wizards/RobustToolbox#4298]
This issue has been exposed by extending the end-round timer for salamander to five minutes, but it takes way longer than five minutes, no actually accurate timing can be provided.

For a timer set to five minutes:
- On my local machine, no drift is created at all.
- On @Arimah 's machine, the clock drifts 12 seconds.

This is especially a problem for long-running timers, as the dilation is made worse there. The implementation should rely on a more reliable source of passed time to resolve this issue.

**Comment by arimah** [comment]
It should be noted that I was running in a debugger so I could inspect the running application, which may have introduced additional drift as the code is non-optimised. Nevertheless, I was able to consistently produce 312 seconds of real time elapsed for a 300 s timer.

**Comment by arimah** [comment]
Looking at how `Timer.Update()` is implemented, we find this:

https://github.com/space-wizards/RobustToolbox/blob/876de4065a2f1b62fca0d7d619123e203afe3d44/Robust.Shared/Timing/Timer.cs#L49

This tells us `frameTime` is likely a value in seconds, as it's multiplied by 1000 to yield a value in milliseconds. Assume the game is running at a perfect 60 fps: frame time is 0.16666..., and times a thousand we get 16.666... And then the value is cast to `int`. The fraction is cut off, which _guarantees_ a drift unless the frame time happens to line up on an integer boundary every single time (which it doesn't).

Assume we enqueue a 300 s timer and the game runs at a _perfect_ 60 fps.

* 300 / (1 / 60) = 18,000 frames in total that the timer _should_ be running for
* However, we will only subtract 16 ms per tick, meaning after 18,000 frames, only 18,000 * 0.016 s = 288 s of real time will have elapsed
* If we subtract 16 ms per tick, it will take the timer 18,750 frames to complete, which makes for 18,750 * (1/60) s = 312.5 s of real time

Given that the drift I produce is consistently 312 seconds plus some fraction, we can conclude that my game, even in the debugger, runs at an almost ideal 60 fps basically all the time.

If the fraction that gets cut off is close to 0.9 (e.g. running at 59 fps = 16.9492 ms per frame), a great deal of time will be lost. If it's closer to 0 (e.g. 58 fps = 17.2414 ms per frame), less time is lost. Over a longer period of time, this absolutely and adds up...

**Comment by mirrorcult** [comment]
yeah `Robust.Shared.Timing.Timer` specifically is pretty old code and not used often in modern content code regardless (instead just accumulating frametime manually) mostly because it doesnt play well with serialization, so i imagine this wasnt caught before because of that

**Comment by arimah** [comment]
There's a very quick and simple fix: change `_timeCounter` to a `float` and drop the int cast. Timers may now run _very slightly_ too _fast_, but should never be off by more than a few milliseconds.
