### ISSUE TITLE
Expose the container an IServerTransformComponent is in properly.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#432]
We need this for inventories, see [this TODO](https://github.com/PJB3005/space-station-14-content/blob/3e0bcddd4db965bc32638b67558ab0ab1f524fa5/Content.Server/GameObjects/Components/Items/InventoryComponent.cs#L110)

There's no good way other than iterating every container on the parent, which is slow.

**Comment by Acruid** [comment]
Iterating over every container on the parent entity is fast enough, `ContainerHelpers` functions take like 0.02% of total CPU time even on the client. Since this is a non-issue and premature optimization, I am closing this.
