### ISSUE TITLE
Powered lights dont let out light until a game reconnect

### ISSUE THREAD

**Issue by VasilisThePikachu** [space-wizards/RobustToolbox#4378]
## Description

Happening as of now on levi and lizzy as speaking

**Reproduction**

1. Start new round
2. Lights will most likely stay closed
3. Reconnect
4. they are back! and they will stay like that until you reconnect

**Screenshots**

**Additional context**

This kinda makes the game very hard to play cause everything is dark sometimes and you have to reconnect every second

Potentially cause space-wizards/space-station-14#19531
![image](https://github.com/space-wizards/space-station-14/assets/34938708/0906a40a-0a65-4436-a677-e3d57ade245c)
The skipped ones had weird build errors

d5bd1c6f86579103351536861d4dcda876b0ed7c
99b77bc2d3ef31140adc7e09b5d4cff822aa9ae9 this one do something with lights
f594af4a3ef99f8c9e7f3c9a77f845e78fe93858

**Comment by TK-A369** [comment]
Today I experienced similar issue on WizDen Leviathan.
But in my case, at the beginning I saw light normally. After lights broke (caused by EMP explosion), I still saw light on, while another player nearby saw darkness. After I reconnected, I saw darkness (correctly).

**Comment by drteaspoon420** [comment]
The lights seem to update when they and areas they effect go out of render range.
Or more accurately when they return to render range.
