### ISSUE TITLE
Embedding scripting for the actual content.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#44]
<sup> Yes I'm aware this is basically dead but it's worth a shot I guess?</sup>

So I suggest we embed Python for handling content. Low end stuff like atmospherics, rendering, whatever... stays C#, but the actual _meat_ of the game gets created in Python.

This has a couple of advantages:
- Python is easy to learn: SS13 doesn't have insane contributor counts without reason.
- It allows easier and safer syncing of server specific code with clients.

**Comment by ZoldorfTheWizard** [comment]
pjb pls not dead topkek, just dev hell 

Python is pretty nice but i was thinking maybe going further and doing scripting in lua 

Some questions that i think would be nice to discuss:
- How easy is it to embed python vs lua?
- implementation of some secure script loading code that will prevent arbitrary code execution? 
- advantages and disadvantages of python and lua

**Comment by PJB3005** [comment]
> How easy is it to embed python vs lua?

There's IronPython, which is python implemented in . Net, skimming over the documentation it looks like it should be easy to implement. 

I have to go, more coming in a bit.

**Comment by PJB3005** [comment]
> implementation of some secure script loading code that will prevent arbitrary code execution?

I assume you mean preventing scripts that steal a client's personal files from being ran? 

I haven't looked into it enough, but even if it isn't natively possible in IronPython it should be possible to do manually. 

> advantages and disadvantages of python and lua

I found [this page](http://lua-users.org/wiki/LuaVersusPython), the general TL;DR is that python is bigger, Lua is lighter. Also I'm unsure how well multithreading would work with python. 

I also want to say that I don't have much experience with Lua, Python was just the first thing to come to my mind. 

Lua is fine in my book too but the real reason for this issue is that we need to get scripting done very soon because it's gonna play into a lot of other systems heavily.

**Comment by ZoldorfTheWizard** [comment]
An actual discussion is happening #itshappening 

> I assume you mean preventing scripts that steal a client's personal files from being ran? I haven't looked into it enough, but even if it isn't naively possible in IronPython it should be possible to do manually.

Oh uh I should have been more clear.... What i meant from arbitrary code execution is sanitizing the script to prevent them from going crazy. for example: The BestRP Paper HTML code execution bug where you could nuke the station with paper and some HTML 

<sup> unless people want that as some sort of insanely hard puzzle that figuring it out rewards you with the option of blowing up the station :P </sup>

if you want to you can go ahead and begin embedding python/lua (up to you) on your own branch to get it going, and later on when everything isn't in limbo we can just merge and have python embedded :D

**Comment by PJB3005** [comment]
> What i meant from arbitrary code execution is sanitizing the script to prevent them from going crazy. for example: The BestRP Paper HTML code execution bug where you could nuke the station with paper and some HTML

Well of course the content and scripts would be sent from the server in the same sort of way BYOND sends the RSC to clients (so players don't need 20 different client installations to play on different servers).
If the bug you're using as an example worked the way I think it did it's 100% the fault of failing to sanitize user input, something we need to do to prevent hackers and stuff anyways.

**Comment by PJB3005** [comment]
So another issue I'm thinking of:

**How will scripting work in relation to the netcode?**
- Will it work like BYOND, where the server does everything and the client just listens (though slightly more client sided than BYOND in some areas)
- Or will we tell the client some things, like "open the door"

Let's use that door example.

**So, first of all.** Client clicks on a door he's adjacent too, what happens?

Does the client say "I opened this door" or does it say "I clicked this door"?

The latter sounds better as the former requires more sanity everywhere which is annoying.

**Secondly.** How does the server tell the clients the door updated?
We can't just say "this guy tried to open this door", because if the door has bolts the client can't know (if the client does know that'll permit client side hacks), and you'll get desync issues.

We can add a ton of functions for every possibility, but that's gonna get extremely messy.

Adding tons of arguments to the functions has the exact same issue.

So how do we do it? The BYOND way which dictates the client what's happening?

**Comment by psykzz** [comment]
> Does the client say "I opened this door" or does it say "I clicked this door"?

You clicked the door, python should be able to query the door state to know if its open or closed.

> Secondly. How does the server tell the clients the door updated?

Python should be able to get events you can then handle them as you like, you'd restrict clientside cheats by making the python have to query it from the server, and server would say, either like. Yes no or you don't know,

**Comment by PJB3005** [comment]
So after looking at door code, the netcode is just server side dictation.

Probably not an issue due to multithreading possibilities and such.

That a actually makes this much easier to handle, in fact I might even try to implement it if I learn enough C#.

**Comment by PJB3005** [comment]
Unless somebody has anything to say I'll use [moonsharp](http://www.moonsharp.org/)
