### ISSUE TITLE
Disconnecting, then reconnecting causes client to complaint about the CVar player.name being registered twice.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#448]

**Comment by Acruid** [comment]
This is because the CVar registration for `player.name` is inside the `SS14.Client.State.States.GameScreen.Startup()` function, which is called every time the state gets focus. It needs to be moved to the `GameScreen.InitializeGUI()` function which is only called once.

**Comment by Acruid** [comment]
Fixed in https://github.com/space-wizards/space-station-14/pull/488.
