### ISSUE TITLE
Kick player command

### ISSUE THREAD

**Issue by Acruid** [space-wizards/RobustToolbox#458]
The server needs a way to forcefully disconnect players, in the form of a kick command.

You can currently get a list of active players on the server with the `listplayers` command. The kick command could use the players name as an argument, or use the network id of the client. `PlayerManager.GetSessionById()`, `IPlayerSession.ConnectedClient.NetworkId`, and the private `NetManager.DisconnectChannel()` functions are a good starting point. If you are going the NetworkID route, you will want to make `listplayers` display a column of the NetworkID of each client.

**Comment by fleure** [comment]
Do we have client privileges yet? (Admin, moderator, donator etc...)

**Comment by ghost** [comment]
no we libertarians users have right to kick each others

**Comment by fleure** [comment]
Respect muh NAP
