### ISSUE TITLE
Please... What the f**king Robust ToolBox's protocol working ?!?!?!??!

### ISSUE THREAD

**Issue by Lines115** [space-wizards/RobustToolbox#4657]
I trying to write some programs with Robust ToolBox's (Space Station 14's) protocol on python, but NOTHING NOT HELPING ME WITH THIS. (**I trying like a month**)
I readed the official Robust ToolBox Docs on the Robust.Shared/Network.... Nothing...
I trying this with ChatGPT 4... Nothing...
Please, help me with this...
I don't have the nerve to try anymore !!...

**Comment by Morb0** [comment]
skill issue

**Comment by deathride58** [comment]
What exactly are you trying to do with the engine? Why do you need Python specifically? This is a C# project

**Comment by deltanedas** [comment]
ok so learn c#

**Comment by Boaz1111** [comment]
> > ok so learn c#
> 
> It so hard for 2-3 projects

it's what this game uses though

**Comment by Lines115** [comment]
> it's what this game uses though

I know, but it really hard for me

**Comment by Boaz1111** [comment]
I don't see what this issue you made here is about then

**Comment by Lines115** [comment]
> I don't see what this issue you made here is about then

**It is about how to implement the Robust ToolBox protocol in python**

**Comment by deathride58** [comment]
The closest you can get is using IronPython, but this *really* isn't recommended. It's worth learning dotnet regardless.

**Comment by VasilisThePikachu** [comment]
You are trying to develop with python... on an engine made in c# dotnet?

I also only knew python before this, its not hard to learn c#

**Comment by deltanedas** [comment]
see also: #22086

**Comment by Lines115** [comment]
I tryed to run the C# DLL (pythonnet), but namespace.... Uh... Robust.Shared.Network...

**### I going to learn C#...**

**Comment by Lines115** [comment]
I tryed to run the C# DLL (pythonnet), but namespace.... Uh... Robust.Shared.Network...

### I going to learn C#...
