### ISSUE TITLE
complex midis cause crazy lag

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/RobustToolbox#4664]
recent changes to midi playback have made it laggy as hell for really complex midis, even persists after round ends

i dont have a sample midi yet ill do some testing

affects both client and server (so laggy round start timer takes multiple seconds to update)

maybe #4642 constantly trying to lock and lagging a thread idk

**Comment by UbaserB** [comment]
My game crashed several times while me and the clown were playing on 15 instruments at once with a specific midi

**Comment by deltanedas** [comment]
a midi that has it: 
[hamster.zip](https://github.com/space-wizards/RobustToolbox/files/13552205/hamster.zip)

near the end fps goes down to ~20 on debug

almost maybe related whenever frames are lost to lag sound pops which is really nasty

**Comment by muburu** [comment]
another midi related thing that causes insane lag is a certain amount of people in a band, it might also be affected by midi complexity but i'm not sure, the amount of lag is definitely not insignificant either...

**Comment by deltanedas** [comment]
also this

```
[WARN] midi.fluidsynth: Failed to set thread to high priority
```

gets **constantly** spammed in logs, maybe that alone is causing slowdown

**Comment by Anzarot121** [comment]
When I try to play this midi file, all the crew members start killing me, because for some reason the last notes freeze and remain beeping if I don’t press “stop”.
https://www.youtube.com/watch?v=A2d_Oty3QsM
Perhaps this is all part of the same problem.

**Comment by Hmeister-fake** [comment]
Please remove midis until its fixed, or at least limit them to one instrument in one band. It is fucking painful going from a smooth framerate to 20 because you walked anywhere near the bar

**Comment by Hmeister-fake** [comment]
There was a guy playing a midi in the bar and a ghost role took the monkey in the bar to stop the person playing music

**Comment by Anzarot121** [comment]
One more thing, if you start playing on a monkey and enter /ghost, the music will continue until you close the instrument window or select another role.

**Comment by Piras314** [comment]
> Please remove midis until its fixed, or at least limit them to one instrument in one band. It is fucking painful going from a smooth framerate to 20 because you walked anywhere near the bar

it would be nice if setting midi volume to 0 stopped midi rendering instead of outright removing things albeit temporarily

**Comment by deltanedas** [comment]
apparently its been fixed
