### ISSUE TITLE
Lighting issues.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#47]
**SFML branch**

https://dl.dropboxusercontent.com/u/107028026/ShareX/2016/04/2016-04-21_21-25-32.webm

Also pictured: really poor performance.

GPU is a GTX 660m, driver version 353.62

**Comment by PJB3005** [comment]
Gonna have to retest this.

**Comment by ZoldorfTheWizard** [comment]
#63
