### ISSUE TITLE
examining living people causes them to appear catatonic for a split second.

### ISSUE THREAD

**Issue by Carolyn3114** [space-wizards/RobustToolbox#4820]
![image](https://github.com/space-wizards/RobustToolbox/assets/136143032/f10d1433-7d73-418b-9fe0-1a26a949619a)

**Comment by LordCarve** [comment]
Caused by space-wizards/space-station-14#23565
Reported here space-wizards/space-station-14#23677

Also content bug, not engine bug - doesn't belong here.

**Comment by UbaserB** [comment]
OOPS

**Comment by UbaserB** [comment]
what even is this repo why did i report here

**Comment by UbaserB** [comment]
Why did i think this was my issue for a second
