### ISSUE TITLE
RobustIntegrationTest Client and Server share ComponentState objects by reference

### ISSUE THREAD

**Issue by LordCarve** [space-wizards/RobustToolbox#4836]
## The problem
`ComponentState`s internals are shared **by reference** between `Client` and `Server` in a `RobustIntegrationTest`. They should be cloned and/or serialized/deserialized when being passed via netcode.

This causes Client to mysteriously know of component changes **before** they are sent by Server. Because of it, `RobustIntegrationTest` simulation does not reflect that of a real Client+Server and tests sensitive to order of execution (i.e. prediction) may result in false positives and false negatives.

How could it possibly apply changes before they are sent by server you ask? It's a convoluted **delete case**. In the delete case, both server and client share the same reference object. When it's deleted on the server - it goes poof on the client as well. **GC is involved.**

Below is a summary of how I managed to replicate it:
1. Sync `Server`'s `FixtureComponent` state with `Client`
2. Have `Server` call `DestroyFixture`
3. When `manager.Fixtures.Remove(fixtureId)` is called **_on the server_** and `Fixture` is removed from dictionary, garbage collector destroys the "apparently-unreferenced" object.
4. Which magically makes said `Fixture` disappear from `GameStateProcessor._lastStateFullRep` **_on the client_**. That dictionary stores `ComponentState`s used for prediction resetting. More importantly, it's client-side and should not be impacted by server-side logic until netcode happens.
5. The following `Client` tick won't correctly reset predictions of that entity, because it works off a future game state (prediction resets to values client has yet to acknowledge this tick).

\+ I absolutely can and do assert that prior to the fixture deletion, the `object.ReferenceEquals(serverFixture, clientComponentStateFixture);` is indeed `True`. This alone is a no-no.

## The good news
**This is tests only. The engine code itself is unaffected.** Kind of obvious, but I wanted to make it extra clear.
We still want tests to correctly verify stuff works as expected, so we still want this to be fixed.

## Plan of attack
[X] I have already confirmed the above is true by creating a test that reproduces this problem conclusively and 100% of the time following the above steps.
[X] Verified that this is also happening for generated `AutoState`s.
[X] Currently cleaning up the test and publishing it (maybe in comments of this issue) - it will serve as a test to see if the underlying issue was resolved when the actual fix PR is ready.
~~[ ] And then I'll jump to fixing the problem (probably end up cloning server objects for `RobustIntegrationTest` netcode?).~~
~~[ ] Check if any existing tests were affected and adjust as necessary~~

## Final notes
GC involvement really threw me off.
**Hopefully**, existing tests won't be affected... hopefully. They might though.

**Comment by PJB3005** [comment]
Huh I thought we fixed this.

**Comment by metalgearsloth** [comment]
This ties into the issue behind https://github.com/space-wizards/RobustToolbox/pull/4827 where we should realistically be deepcopying on state getters now, at least with the engine as is.

**Comment by PJB3005** [comment]
The real fix should just be to make the integration net manager run `WriteToBuffer()` and `ReadFromBuffer()` to an internal buffer, but the annoying problem is that Lidgren makes the constructors for those internal...

I guess I could bodge something together in Lidgren for testing purposes.

**Comment by LordCarve** [comment]
Update: confirmed that this also happens for generated `AutoState`s. But in a different flavor™

For `AutoState`s, the component object _**itself**_ is shared by reference. Not just its "client-side server state" (as was the case with `FixtureManagerComponentState`). I believe this part of the issue in particular is addressed by #4827

We'll be able to test it right away when I clean up and publish the tests (working on it now).
