### ISSUE TITLE
imagesharp dep has vulnerability apparently 

### ISSUE THREAD

**Issue by deltanedas** [space-wizards/RobustToolbox#4943]
`warning NU1903: Package 'SixLabors.ImageSharp' 3.1.2 has a known high severity vulnerability, https://github.com/advisories/GHSA-65x7-c272-7g7r`

bump to 3.1.3 probably

**Comment by metalgearsloth** [comment]
fixed in <1 morbillion backported engine versions>

**Comment by deltanedas** [comment]
somehow every build i make has 4 imagesharp warnings so apparently this wasnt done or it needs some cache to be cleared idk? @metalgearsloth reopen maybe

its using 3.1.3 but thats vulnerable too?
apparently 3.1.4 is the real fixed one
