### ISSUE TITLE
Version of SpriteView for EntityPrototypes

### ISSUE THREAD

**Issue by Plykiya** [space-wizards/RobustToolbox#4976]
This is... kind of a request for a feature? I don't really know how to implement this myself... or if I'm really understanding this properly.

I've been working on https://github.com/space-wizards/space-station-14/pull/26178 and encountered a problem with EntityPrototypes not really having a way to support layering of textures, so I'm stuck with just the base texture appearance. A lot of the textures I'm working with are pretty much only differentiable as a result of the additional sprite layers, without it they all look the same.

My only options at the moment are to pretend it's not a problem (bad), create custom icons for each LatheRecipe (bad), or to just pray and hope someone helps me (sad but best choice)

**Comment by moonheart08** [comment]
> This is... kind of a request for a feature? I don't really know how to implement this myself... or if I'm really understanding this properly.
> 
> I've been working on [space-wizards/space-station-14#26178](https://github.com/space-wizards/space-station-14/pull/26178) and encountered a problem with EntityPrototypes not really having a way to support layering of textures, so I'm stuck with just the base texture appearance. A lot of the textures I'm working with are pretty much only differentiable as a result of the additional sprite layers, without it they all look the same.
> 
> My only options at the moment are to pretend it's not a problem (bad), create custom icons for each LatheRecipe (bad), or to just pray and hope someone helps me (sad but best choice)

What you should do is spawn a copy of the entity client-side and have a view showing that client-side version.
Drawing prototypes directly won't ever be supported, but drawing client-side entities works perfectly fine. Look at guidebook's entity view for an example.
