### ISSUE TITLE
AtlasTexture.GetPixel didn`t work if SourceTexture is so big

### ISSUE THREAD

**Issue by Cinkafox** [space-wizards/RobustToolbox#5001]
I needed to manipulate textures for one small thing. Specifically hand sprites. However, due to the huge size of the AtlasTexture, I was unable to do this because the stack was overflowing. I quess is because in ClydeTexture.GetPixel: 
```cs
Span<byte> rgba = stackalloc byte[4*this.Size.X*this.Size.Y];
```
Size of SourceTexture is realy huge. 8192px 8192px. And during creation of span the stack simply overflowed.

**Comment by PJB3005** [comment]
This API is terrible and it's never going to run well, but I'll at least fix the immediate issue...
