### ISSUE TITLE
Audio player/manager runs out of memory when running for a few hours or too many audio streams are played

### ISSUE THREAD

**Issue by MeowVal** [space-wizards/RobustToolbox#5007]
There seems to be a problem with the Audio player/manager that causes it to run out of memory after some hours of playtime or when too many sounds are played at once. For instance, when 20-30 players are stunned by the behonker at once 5 times in a row after playing for like an hour, it will cause partial audio loss as AL runs out of memory. This will also happen after a few hours too 5 or 6 hours depending on how many audio sources are played during gameplay hinting at a slow memory leak as previous audio sources that have been played are not cleaned up correctly. I have run into this on Wizden servers, Delta-V servers and Frontier server. The fastest way I have found to reproduce it during live gameplay was by jumping into the Delta-V server during peak hours because of the number of sounds played at once. I do not have the error logs but someone has already posted error logs regarding the same issue on the ss14 issue tracker linked here https://github.com/space-wizards/space-station-14/issues/25254#issue-2135502227
The issue pops up in the error log on line 91044 and just repeats until the client is closed.
![image](https://github.com/space-wizards/RobustToolbox/assets/46445294/57278b94-a8eb-4e3e-8131-ed55a82024ff)

**Comment by metalgearsloth** [comment]
What's your platform, are you on mac.

**Comment by metalgearsloth** [comment]
Digging through ahelps seems like it might be a widespread problem? Need logs from other people to confirm.

**Comment by metalgearsloth** [comment]
Okay I tracked it down will submit a PR later after I check commit history for something.
