### ISSUE TITLE
AtlasTexture support for Shader

### ISSUE THREAD

**Issue by Cinkafox** [space-wizards/RobustToolbox#5013]
I want to do some funny think with sprites, but i need a texture input for shader. And i see, currently shader does not support AtlasTexture.
```cs
//Clyde.Rendering.cs 505 line
...
                   case ClydeTexture clydeTexture:
                        //It's important to start at Texture6 here since DrawCommandBatch uses Texture0 and Texture1 immediately after calling this
                        //function! If passing in textures as uniforms ever stops working it might be since someone made it use all the way up to Texture6 too.
                        //Might change this in the future?
                        TextureUnit cTarget = TextureUnit.Texture6 + textureUnitVal;
                        SetTexture(cTarget, clydeTexture.TextureId);
                        program.SetUniformTexture(name, cTarget);
                        textureUnitVal++;
                        break;
                    default:
                        throw new InvalidOperationException($"Unable to handle shader parameter {name}: {value}");
```

**Comment by PJB3005** [comment]
This isn't possible due to how graphics APIs work.

**Comment by moonheart08** [comment]
As Luna didn't elaborate too much on the why, i'll (try to) explain: AtlasTexture is an abstraction the engine makes, GPUs don't actually innately support atlases at all. They're just a wrapper over a standard texture that tells anything aware of *our* atlas *abstraction* to only use some smaller region of a larger texture.

Shaders don't have a way to directly specify that subregion in a texture binding, the shader code needs to be written explicitly to support it. What you could do instead is give the shader the underlying texture, and the subregion to use in a uniform.
