### ISSUE TITLE
Color.ToHSV returns wrong values in the purple hue band

### ISSUE THREAD

**Issue by Errant-4** [space-wizards/RobustToolbox#5039]
#### Issue

When an RGB Color is input into Color.ToHSV where Red > Blue > Green, the Hue returned is incorrect. 
There hasn't been an easy way to spot this until now, because where species allow the use of a hue slider, the game does not try to validate or modify the Hue selection, thus it never runs ToHSV on it. 
However since I am squashing the Vox colors into a certain range, it became immediately apparent that reaching the 300+ range of the Hue slider abruptly jumps to the start of the hue range

https://github.com/space-wizards/RobustToolbox/assets/35878406/004986f9-3980-48d0-9272-2180fb7ee5c8

#### Reproduction:

```
var red = 255 / 255f;
var green = 200 / 255f;
var blue = 240 / 255f;
Color input = (red, green, blue, 1);
var testHSV = Color.ToHsv(input);
var outHue = testHSV.X * 360f;
```
Correct Hue value of 255, 200, 240 would be 316.4, but the engine returns -43.6

#### Why?
The issue is this specific bit of code in Robust.Shared.Math/Color.cs ~line 590

```
if (max == rgb.R)
    h = (rgb.G - rgb.B) / c % 6.0f;
```
If blue is greater than green, this will result in a negative input for the %6 remainder division operation.
Essentially, in this case it will return `(rgb.G - rgb.B) / c - 6` which will always be a negative value since all preceding numbers in the equation can be no larger than 1.

(This issue does not appear when Green or Blue are the highest color value, because those execution branches don't need a % division to calculate the hue)

#### Solution, maybe?
Interestingly when I tried to use MOD() in OpenOffice Calc (to generate a stack of output expectations), seemingly the same type of "remainder after division" calculation to generate a stack of "expected results", it gave me a DIFFERENT result. Basically it gave me `(rgb.G - rgb.B) / c + 6` instead, which (perhaps not coincidetnally) resulted in the exact values I needed.

My test fix was then to use +6 instead when the %6 results in a negative number, and this appears to work as expected.

```
if (max == rgb.R)
    h = (rgb.G - rgb.B) / c % 6;
        if (h < 0)
            h = (rgb.G - rgb.B) / c + 6;
```
This seems to fix the issue, but I would like for someone who has been messing with this part of the game/engine code for more than 2 days to sanity-check this

**Comment by moonheart08** [comment]
a remainder bug! terrible. This likely occurred because `%`/`mod` is defined differently in different languages. Your fix however is not correct. Instead, if the result is negative, add six to the *remainder* (essentially flipping it about the axis).

The effect you're seeing is the fact C# uses truncated division for rem, resulting in this (green line is the remainder):
![Divmod_truncated svg](https://github.com/space-wizards/RobustToolbox/assets/7806367/ef171eb6-025d-4716-ba65-6510528a4f79)

**Comment by Errant-4** [comment]
WTF, somebody _knew_

![image](https://github.com/space-wizards/RobustToolbox/assets/35878406/fcd82124-4c0a-49ce-9a12-c76ef53bc020)
