### ISSUE TITLE
BSDiff removal and replacement

### ISSUE THREAD

**Issue by SaphireLattice** [space-wizards/RobustToolbox#505]
As it was said in the chat, usage of BSDiff is a huge hack, and should not be a thing. Proposed solution was to mark things "dirty".

Something something issue to keep track of this?

**Comment by RemieRichards** [comment]
use ```INotifyPropertyChanged``` to mark things dirty, so props and vars can remain uncluttered/everything is covered.

**Comment by PJB3005** [comment]
We're using `SS14.Shared.Bsdiff` now which uses Rust, so performance should be much better already. It still needs to get replaced completely though.
