### ISSUE TITLE
Physics raycasts only hit broadphase nodes; don't perform narrowphase tests

### ISSUE THREAD

**Issue by eoineoineoin** [space-wizards/RobustToolbox#5074]
Physics raycasts hit broadphase nodes, and don't check for actual shape intersection. This results in some bad behaviour when picking/placing objects around structures whose shape doesn't fill the whole AABB.

Placing an object towards a diagonal wall will only place that object at the broadphase AABB:

https://github.com/space-wizards/RobustToolbox/assets/1676295/97f49d04-6e4a-4a3b-874a-a4c3fc7312c8

If you stand inside the AABB, you _can_ place an item down in the free space, but you can't pick it up if the ray originates outside the AABB:

![pickOutside](https://github.com/space-wizards/RobustToolbox/assets/1676295/d7089bb2-8ba1-42a1-9ddd-0cecdfe1177b)

But it can be picked up if the ray originates inside the AABB:

![pickInside](https://github.com/space-wizards/RobustToolbox/assets/1676295/4dc7fb78-6797-421f-bdf5-0588609d5f94)

In Robust.Shared.Physics.Systems.SharedPhysicsSystem.IntersectRayWithPredicate, there's a "TODO: Shape raycast here", which is where the narrowphase checks _should_ happen. There's no implementation of the ray-shape intersection tests, though the original Farseer physics code does have them, so not sure what happened here (this looks like it might violate restriction 2 in the Farseer license? IANAL, just play one in space.)

**Comment by metalgearsloth** [comment]
Dupe https://github.com/space-wizards/RobustToolbox/issues/1707
