### ISSUE TITLE
Dev envorment crash (Holding backspace)

### ISSUE THREAD

**Issue by beck-thompson** [space-wizards/RobustToolbox#5095]
## Description

The client crashes when holding backspace in the spawn entity pannel.

**Reproduction**

Open the spawn entity panel and search something but then hold backspace (Clicking backspace will not crash).

**Screenshots**

https://github.com/space-wizards/space-station-14/assets/107373427/c88f7cc9-cc66-4c41-a0f3-451903b15090

Line where the assert statement fails:
![Screenshot 2024-05-01 101943](https://github.com/space-wizards/space-station-14/assets/107373427/6f0e08cf-40d0-4b4e-bd0c-762a0877bdf1)

**Comment by beck-thompson** [comment]
Update this actually seems to happen anytime hold backspace in a text window. I find it hard to believe that I am the only one who has noticed that so I think this might just be a me issue!

**Comment by moonheart08** [comment]
Closed in favor of the other issue.
