### ISSUE TITLE
Placement Manager Improvements

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/RobustToolbox#510]
Current problems to resolve: Placement manager right now spawns as long as your holding down the mouse click, this is **100% okay for tiles** but awful for non-tile spawning for a few reasons why

1. It spawns way more objects than you need even when trying to click quickly to spawn 1, makes testing more difficult
2. Theres an issue when you're using breakpoints and the debugger on things that are newly spawned where it will keep trying to spawn objects everytime you press continue because it hasn't registered mouseup

Improvements to make: Placement manager should have (at least) two alternate modes for spawning objects. These will be linked to clicking with key modifiers on, and only for certain spawn types such as snapgrid, snapgrid offset, align wall, and align tile any

1. Shift Click - Shift clicking once will make it so that the place you clicked is now locked in, and that the system will try to create an object at each node (along each cardinal direction) until it reaches your mouse. So if you shift click and move your mouse eight tiles up it will display the eight objects its going to spawn at each node (such as tile in align tile any) and then spawn them the next time you click.

2. Cntrl Click - Cntrl clicking once will do the same thing as above, but instead of spawning in a line in any cardinal direction it will spawn in a grid all the way to your cursor.

Right clicking should cancel out of either of these alt modes and back into normal spawn placement. This will make quick editing, such as placing a line of walls, a line of wires for the powernet, or extending/contracting the station much easier.

**Comment by Acruid** [comment]
All of these features are in the game now, so i'm closing this.
