### ISSUE TITLE
PVS View bounds need to be per-viewer and non-square.

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/RobustToolbox#5154]
I could've sworn we solved this in like 2022 but apparently not.

# API Changes
- `net.pvs_range` needs removed (as range should be per viewer) or changed to be only the default.
- View range and priority view range should become Vector2s, boxes centered around the viewer.

**Comment by metalgearsloth** [comment]
dupe https://github.com/space-wizards/RobustToolbox/issues/4600
