### ISSUE TITLE
Entity Deserialization - Resolve Cross Refs

### ISSUE THREAD

**Issue by Acruid** [space-wizards/RobustToolbox#524]
Right now when maps and blueprints are deserialized, all cross references between `GridId`, `MapId`, and `EntityUid` types can be changed, causing the deserialized old value to be invalid.

There isn't much that can be done to resolve a `MapId`, maybe it should be set to `MapId.Nullspace`. When loading a map, `GridId` is not changed so the ref is still valid, when loading a blueprint this cannot be properly resolved, so maybe set it to `GridId.DefaultGrid`. `EntityUid` can be resolved in both cases by mapping old ent ID's to new ones, then setting the new value after all entities are deserialized.

This issue prevents things like parenting from working properly with saving/loading.

**Comment by PJB3005** [comment]
In general the entire map format needs a rewrite.
