### ISSUE TITLE
Need a lightweight LinkedList

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/RobustToolbox#5255]
I have been eyeing out the new dynamictree and erin seems to just implement the pointer / linked-list handling manually whereas it would be preferable if we just had a class that handles this. I also think the default dotnet implementation might be too slow.

**Comment by PJB3005** [comment]
This literally isn't possible. The whole point of linked lists is that they can be easily integrated into existing memory spaces. An off-the-shelf linked list as the BCL has sucks for exactly this reason, there's no magic way to make that faster.

**Comment by metalgearsloth** [comment]
F, copying C code it is.
