### ISSUE TITLE
Replays Sometimes Generate A Small 10-13 Byte Null File Which Break Replays

### ISSUE THREAD

**Issue by Admiral-Obvious-001** [space-wizards/RobustToolbox#5494]
Just did some troubleshooting with a few other users about a broken replay file and determined that in both cases the replays threw a bufferSize: (0) exception.

Deleting the .dat file with only null contained within fixes the issue and allows replays to be loaded.

This issue is present on at least 3 forks that I'm aware of, including potentially upstream Wizards Den.

Was told to add an issue here.

**Comment by PJB3005** [comment]
Likely I happened to fix this with c794bd84bfb1a22c6ff5960ef9beb0a6ac2e07d0?

**Comment by Admiral-Obvious-001** [comment]
Unsure right now, I'd need to find a current replay with a similar data structure, but if that's a commit specifically for this I can close and reopen later if it crops back up.
