### ISSUE TITLE
Github tag missing

### ISSUE THREAD

**Issue by Rinary1** [space-wizards/RobustToolbox#5568]
Robust toolbox v238 published, but it doesn't have a tag with compiled versions for client, what breaks publishing

**Comment by metalgearsloth** [comment]
there is no 238?

**Comment by Rinary1** [comment]
> there is no 238?

yes:
![image](https://github.com/user-attachments/assets/b9389e87-31fc-415f-9dc3-35d7011bfa5a)
![image](https://github.com/user-attachments/assets/67a11d25-aaee-41cd-8514-f7133ba87beb)

**Comment by Rinary1** [comment]
last tag is 237.4.0, but published 238.0.0

**Comment by ElectroJr** [comment]
Ah.  I probably forgot to push tags. My bad

**Comment by ElectroJr** [comment]
Should be fixed now, sorry about that.
