### ISSUE TITLE
3D

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#593]

**Comment by praisenarsie** [comment]
![](https://i.imgur.com/vA6U4kM.jpg)

**Comment by ghost** [comment]
muh 2d anime world

**Comment by GithubPrankster** [comment]
![friendshipendedprogram](https://user-images.githubusercontent.com/33995085/41121774-c13118c2-6a6f-11e8-81e7-40c13915d1e4.png)

**Comment by PJB3005** [comment]
Er, please keep the shitposting down, mmkay.

**Comment by GithubPrankster** [comment]
Anyways, I am Uneven Prankster from discord, and I love 3d. Send me ideas.

**Comment by ghost** [comment]
Ideas for models? 
https://docs.google.com/spreadsheets/d/1d7JmC1ESyY50EGhpB0VuY7f3Ytk1Q-xmj75yToQunKU/edit?usp=sharing

**Comment by Acruid** [comment]
Outside the scope of the current project, and put on hold indefinitely.

**Comment by PJB3005** [comment]
To elaborate: there's no good game engines/frameworks/libraries that we know of to help here, and writing our own 3D renderer has been deemed off the table.

**Comment by io-june** [comment]
Have you actually looked for good frameworks/libraries for 3D rendering, I think we only looked for game engine (godot) to do all the stuff including 3D, not specifically 3D?
