### ISSUE TITLE
Add exception handling to common events.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#596]
Right now, a single exception and the entire server dies. At least you can't sneeze it to death I guess.

Anyways, we need multiple levels of exception catching and logging. Something in the main loop as a last resort for one, then try catches around events such as input should all be nice.

Client could probably use some too. It doesn't crash but it can make it flat miss an entire update tick.

**Comment by PaulRitter** [comment]
AFAICT this is resolved

**Comment by SweptWasTaken** [comment]
> 
> 
> AFAICT this is resolved

Yes. Closing.
