### ISSUE TITLE
Overlay manager screen overlays should be below the UI layer. 

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#598]
They're above it right now.

Just gotta reorder the `Node2D` used to be before the UI root in the UI layer.

**Comment by Acruid** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/commit/6db4722a13d6b10d02d20bd0ddb011f2c3776cb1, and probably resolved since ~~Mike~~Clyde was created.
