### ISSUE TITLE
DllNotFoundException when running

### ISSUE THREAD

**Issue by greym0uth** [space-wizards/RobustToolbox#60]
Exact message.

> An unhandled exception of type 'System.DllNotFoundException' occurred in sfmlnet-graphics-2.dll
> 
> Additional information: Unable to load DLL 'csfml-graphics-2': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

The issue happens when it attempts to add the 'base_font', in the LoadBaseResources method, in the ResourceManagerZip class.

`
_fonts.Add("base_font", new Font( _stream));
`

Everything builds fine but this doesn't work. I don't know where to post this since the website and irc seems to be down...

**Comment by ZoldorfTheWizard** [comment]
http://www.spacestation14.com/wiki/Developer_Bootcamp#Windows 

make sure the csfml libs are being copied to the output directory (http://imgur.com/a/nlR9y)
