### ISSUE TITLE
Entity Spawn Panel Mousewheel

### ISSUE THREAD

**Issue by clusterfack** [space-wizards/RobustToolbox#608]
The vertical scroll container in the entity spawn panel doesn't seem to accept mousewheeling by itself due to its parameters I assume. Entity spawn panel buttons accept mousewheeling so you can mousewheel up and down the menu as long as your cursor remains on one of these buttons. 

However there is a small gap between the entity spawn panel buttons so scrolling up or down with your mousewheel has a chance to end up in one of these gaps, which prevents further mousewheeling. This means that if you rapidly mousewheel from top to bottom or vice versa your cursor will often get stopped midway as it reaches one of those gaps.

**Comment by PJB3005** [comment]
Probably the fact that the scroll container has mouse filter mode set to ignore.

**Comment by PJB3005** [comment]
Done.
