### ISSUE TITLE
Appearance controller system

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#609]
Basically, decouple game logic from visuals like sprite or (in 3D) models.

Stuff like a battery component pushes data into an appearance controller which acts upon it. This can be any implementation, such as toggling sprite overlays, an FSM for 3D animations, ...

**Comment by RemieRichards** [comment]
FSM FTW TBH.

**Comment by PJB3005** [comment]
This is kinda done. Appearance visualizers are in. Specific ones for preset FSMs are something we'll worry about later.
