### ISSUE TITLE
There is no todo list

### ISSUE THREAD

**Issue by rouge** [space-wizards/RobustToolbox#61]
If you guys don't have a todo list, how are people interested in contributing to this wonderful project going to know what to work on?

**Comment by rouge** [comment]
inb4 theentiregame

**Comment by wakeuphate** [comment]
I'd mentioned this in #22 and some other repo was mentioned, but it looks like ~~that's dead now.~~ the issues have been turned off.

**Comment by rouge** [comment]
This exists: http://www.spacestation14.com/wiki/Roadmap 

but this isn't a todo list :(

**Comment by theOperand** [comment]
its dead

**Comment by ZoldorfTheWizard** [comment]
lol

**Comment by PJB3005** [comment]
Really should just make a Trello or something.

**Comment by ZoldorfTheWizard** [comment]
@wakeuphate My issues are gone :O  guess its time to make new ones

**Comment by ZoldorfTheWizard** [comment]
#65 please feel free to discuss on there if other things are missing, this list is off the top of my head and ill be adding stuff to it
