### ISSUE TITLE
cannot join server

### ISSUE THREAD

**Issue by bobster707** [space-wizards/RobustToolbox#613]
when I host the local server and try to join with the client to try it out it just stays on the main screen and does not do anything. in the server console, it says I have joined but I am still on the main menu. I have the versions: 
SS14.Server_macOS_amd64.zip and SS14.Client_Windows_amd64.zip from the spacestation14.io website please help or tell me what I am doing wrong, thank you.

**Comment by PJB3005** [comment]
If you hit ` are there any obvious errors in the console?

**Comment by bobster707** [comment]
yes, seems to be errors to do with textures with a greyshirt. says
[ERRO] go.comp.sprite: Unable to load RSI 'Textures/Mob/greyshirt.rsi'. Prototype 'HumanMob_content'
[ERRO] go.comp.sprite: No base RSI set to load states from: cannot use 'state' property. Prototype 'HumanMob_content'
[ERRO] go.comp.icon: Failed to load RSI 'Textures/Mob/greyshirt.rsi'. Prototype 'HumanMob_content'

**Comment by Acruid** [comment]
Come talk to us in Discord if you are still having problems.
https://discord.gg/MwDDf6t
