### ISSUE TITLE
Client can't find csfml libs

### ISSUE THREAD

**Issue by rouge** [space-wizards/RobustToolbox#62]
CSFML libs are not in the 'Client' directory.

**Comment by ZoldorfTheWizard** [comment]
Hello there! Github (or maybe a repository setting) does not save the settings of dynamically linked libraries so you manually have to go to your project and make sure the CSFML Libs are being copied if newer.

![2016-08-02 10_27_01-spacestation14 - microsoft visual studio](https://cloud.githubusercontent.com/assets/7108570/17336504/be9963f4-589b-11e6-866c-44170b8fd0bc.png)

![2016-08-02 10_27_19-spacestation14 - microsoft visual studio](https://cloud.githubusercontent.com/assets/7108570/17336507/c12dd8c0-589b-11e6-82f0-0b6efc01d2c7.png)

**Comment by PJB3005** [comment]
Definitely gonna need to add this to the readme or something.

**Comment by ZoldorfTheWizard** [comment]
http://www.spacestation14.com/wiki/Developer_Bootcamp#Windows
