### ISSUE TITLE
Hands - Deleted entity Crash

### ISSUE THREAD

**Issue by Acruid** [space-wizards/RobustToolbox#648]
The hands system holds a reference to the IEntity in each hand. If the entity is deleted the hands system will continue to reference the entity, causing any access to any of the components of the entity to throw an exception, because the components were already disposed.

How to reproduce:
Spawn a `Steel Sheet 1`, place a wall blueprint down, and click twice on the wall.

Exception:
https://cdn.discordapp.com/attachments/310555209753690112/476846426291175452/unknown.png

**Comment by PJB3005** [comment]
This is a bug in content, isn't it? It should be removing the item from the hand on deletion not keeping a reference around.

Preventing it from doing a hard crash is just up to #596

**Comment by Acruid** [comment]
Yup this is a content issue and I made this issue in the wrong repo.
