### ISSUE TITLE
SS14 TODO 

### ISSUE THREAD

**Issue by ZoldorfTheWizard** [space-wizards/RobustToolbox#65]
Overall goal: Create a platform independent of BYOND that can be forked into different stations. 
[Reworking this section]

**Comment by Jaden-Giordano** [comment]
Could you add the client throwing a NotImplementedException crashing the whole client (should just make a log with the exception info). Oh and fixing collisions (its done bad, cant press key towards wall and move perpendicular to it) too. Im working on both of those right now.

**Comment by Silvertorch5** [comment]
#68

**Comment by PJB3005** [comment]
I think our goal should be to strip game code entirely, going from job handling to the lobby. Unless removing said code would interfere with development.

**Comment by greym0uth** [comment]
Yeah, I agree, would you mind expanding on that idea a bit more, I'm interested in what you have in mind and wouldn't mind helping out.

**Comment by PJB3005** [comment]
Issue's too generic and we have independent issues all discussing this.
