### ISSUE TITLE
One bounding box is not cutting it.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#678]
Right now, collision and click bounding boxes are shared.

This is already problematic for humans, tables and doors.

They should be separated into their own deal.

**Comment by Acruid** [comment]
I suggest that click boxes should be calculated on-the-fly, and bounding boxes a purely physics concept. Click boxes (or circles?) can be a minimum size, and expand to fit the bounding box of the entity. This way small objects will have a fixed 0.5x0.5m box so they are still clickable, and large objects will have a bigger click box. We can always add a click box override component for special entities.

**Comment by clusterfack** [comment]
Bring back transparency clicking!

**Comment by Acruid** [comment]
I explained a bit how we can design the physics architecture here: https://github.com/space-wizards/space-station-14/issues/286

**Comment by Acruid** [comment]
This would require https://github.com/space-wizards/space-station-14/issues/698.

**Comment by captkirk88** [comment]
Use a sphere to detect clicks on each part of the entities "body".  Have one sphere encompass the entity and all parts to filter out clicks by radius.

**Comment by captkirk88** [comment]
I don't know if your collision system supports rotating collision shapes relative to a root shape, if it does, you could even rotate entities and maintain that collision support without too many calculations per frame.

**Comment by PJB3005** [comment]
I don't think a sphere would be a good default shape because it doesn't encompass items well.
