### ISSUE TITLE
Replace INetChannel with IPlayerSession instances in common events.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#704]
Net channels are pretty useless for common events like component messages. If you care where the message is from at all you'll always be resolving a player session.

Pretty annoying boilerplate and a leaky abstraction.

**Comment by Acruid** [comment]
There is no common interface between the client and server IPlayerSession that is useful in a shared context. If we went through with this, instead of resolving the channel to a session, you would be upcasting the shared session to the client/server version. Would this be better?

**Comment by PJB3005** [comment]
What code is passing around `INetChannel` in shared as a reference to a player, not just, you know, a network channel?

**Comment by Acruid** [comment]
https://github.com/space-wizards/RobustToolbox/blob/master/Robust.Shared/GameObjects/Component.cs#L196

iirc this was what this issue was originally about when you made it, having to resolve the session from the net channel.

**Comment by PJB3005** [comment]
See the thing about that is that the channel isn't actually used in shared itself. Only passed aroudn

It feels like it would be better to have explicit versions for "from server" and "from client" versions instead...

**Comment by snowsignal** [comment]
If possible, I would like to help resolve this issue.

**Comment by gradientvera** [comment]
@InquisitivePenguin Sure thing. I just assigned you to it.

**Comment by snowsignal** [comment]
Thanks, I'll get on it.

**Comment by PJB3005** [comment]
The icky part here is what should happen in the case of `void HandleMessage(ComponentMessage message, INetChannel netChannel = null, IComponent component = null)` on the client. What should the session be if the message is from the server, on the client? Should it just be the player session representing the local player?

**Comment by PJB3005** [comment]
Oh also, you'll probably want to use `ICommonSession` instead of actual `IPlayerSession`, since `ICommonSession` is shared.

**Comment by snowsignal** [comment]
@PJB3005 just to make sure I understand the problem: we're passing in an INetChannel to the function that handles component messages, but we should be passing in session data instead, correct?

**Comment by PJB3005** [comment]
The problem is that net channels aren't particularly high level, and for most situations *on the server* you'd rather have the actual player session. After all, players can't actually send these kinds of messages until long after they've gotten a player session assigned.

The hard part is that on the client, the only one sending you messages will be the server, so a player session isn't the "correct" way to map it necessarily. Net channel is but because the component API is in shared client and server have to share these.

So the server would prefer to have sessions, while on the client the most it would probably need is a way to tell "is this a networked message". Just using a dummy session on the client is probably fine.

**Comment by snowsignal** [comment]
@PJB3005 what if I added an extra parameter to `HandleMessage` that's null by default, which provides an `IPlayerSession` if the function is being executed on the server and null if it is being executed on the client?

**Comment by PJB3005** [comment]
It may just be best to split the method into two so there's a `HandleNetworkMessage` and a `HandleLocalMessage` (or just `HandleMessage`). Then we can also get rid of that uglyness where `component` is null for remote messages so the signature can be made cleaner.

It would probably significantly help with keeping client/server cleanly separated too. And then yeah, just have an parameter that contains the player session if relevant.

**Comment by snowsignal** [comment]
@PJB3005 that makes sense. I rewrote the code so that `HandleMessage` now takes a message, a component, and an optional session (in the form of a ICommonSession), while `HandleNetworkMessage` takes a message and an INetChannel. Question: how can I check if I'm the client or the server, and how can I retrieve the player session if I'm the server?

**Comment by snowsignal** [comment]
Or should I just make the session an optional parameter for `Entity.SendMessage` and have the client/server-specific code deal with it?

**Comment by PJB3005** [comment]
Player session is only relevant when the message comes from a client, on the server.

> Question: how can I check if I'm the client or the server, and how can I retrieve the player session if I'm the server?

`INetManager` has some properties for whether it's server/client. `IPlayerManager` on the server can resolve net channel -> player session.

**Comment by snowsignal** [comment]
> Player session is only relevant when the message comes from a client, on the server.

In other words, I should put the optional session parameter in `HandleNetworkMessage` and not `HandleMessage`, correct?

> `INetManager` has some properties for whether it's server/client. `IPlayerManager` on the server can resolve net channel -> player session.

Is there a way to use IPlayerManager inside shared code, or do I need to pass the session in as a parameter to `Entity.SendNetworkMessage` from the client/server-specific code?

**Comment by snowsignal** [comment]
Wait, I realized that `Entity.SendNetworkMessage` shouldn't be passing the session. Instead, we somehow need `EntityManager` to supply the session when it receives a component message.

**Comment by PJB3005** [comment]
> In other words, I should put the optional session parameter in HandleNetworkMessage and not HandleMessage, correct?

yes.

> Instead, we somehow need EntityManager to supply the session when it receives a component message.

yep. `EntityNetworkManager` is in chagre here

**Comment by snowsignal** [comment]
Alright, my solution was to add a `Session` field to `NetworkComponentMessage` that is null by default in its constructor. `ServerEntityNetworkManager` can then initialize the message it dispatches to `EntityManager` with the client session that it retrieves from `IPlayerManager`.

**Comment by snowsignal** [comment]
Alright, one last question about PRs: should I make a PR on this repo for the changes specific to RobustToolbox and a separate PR on space-station-14 for the updates made to the content repo (because this breaks a whole lot of stuff), or should I make a single PR on space-station-14 that includes the changes made to RobustToolbox?

**Comment by gradientvera** [comment]
The former. When you open the content PR, you should probably specify that it requires an engine change and link to the engine PR

**Comment by PJB3005** [comment]
RobustToolbox is a submodule so you can't make a single PR to update both repos. You'll need to make a separate PR on both repos yes.

Don't commit the submodule update in the non-engine PR though, I'll handle it after merging the engine PR. So yes it's fine to leave the content PR failing compile.
