### ISSUE TITLE
Client-side map sync race conditions galore

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#707]
@Acruid 

Right now the map netcode is completely disconnect from the entity netcode. This causes tons of race conditions *everywhere*.

If you make a new grid and put an entity on it, the entity may be on the client before the grid, causing tons of code to flat out not work.

Map netcode should be merged into the gamestate system so that we can be sure of when they arrive on the client, so that we can prevent these race conditions.

**Comment by Acruid** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/pull/726, closing.
