### ISSUE TITLE
Out or in with Godot's editor?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#713]
So we're kinda in a tricky spot where *specifically* interfaces are made with Godot's own editor.

This is nice because it means we have to put zero effort into an interface editor, but at the same time modifying Godot's editor to suit our needs is a serious barrier and hassle too.

In the future this is only gonna get more complicated.

How do we deal with this? Do we commit to using the Godot editor as a standard tool, or do we try to phase it out for anything we might need?

**Comment by captkirk88** [comment]
Commit to it as a standard tool.  You already bargained with the devil, might as well go and give the rest of your soul.

No more flip-flopping.  Stick to your guns and get SS14 completed.

**Comment by N3X15** [comment]
NO WE NEED MORE REFACTORS

**Comment by PJB3005** [comment]
"Stick with it" is surprisingly difficult when it's extremely difficult to modify the editor.

Outside of hard forking godot of course, but even then it's a royal pain.

Godot C# still doesn't do editor plugins so it's basically "hahaha time for C++" for a tool that we will barely use. Working it into our file system and such will also just bloody suck.

This isn't me going "hahah time to refactor everything" I'm genuinely unsure whether it's easier to fork editor or NIH the relatively small set of features we need.

**Comment by clusterfack** [comment]
Stick with it forever, godot is love, godot is life

**Comment by ajvsol** [comment]
From the [documentation](https://docs.godotengine.org/en/3.0/tutorials/plugins/editor/making_plugins.html) it seems you can make editor plugins with GDScript (which has a Python-like syntax).

**Comment by PJB3005** [comment]
I'm fully aware and I even did for the 3D branch.

Problem: it's agony. GDScript is pain.

**Comment by ajvsol** [comment]
Surely better than having to use C++ or build a replacement. 

Godot already isn't being used as the game engine in favour of a custom solution, swapping out even more parts doesn't make much sense to me long-term. Seems like a good way to miss out on all the support, features and add-ons that sticking with Godot fully would bring.

**Comment by PJB3005** [comment]
> Surely better than having to use C++

Debatable, and that might be necessary either way.

**Comment by PJB3005** [comment]
Kinda relevant: Godot has been EXTREMELY unstable for development for me personally. The client will just randomly die on various forms of abort/segfaults internal to Godot. I don't see a solution here other than making our own OpenGL renderer.

**Comment by clusterfack** [comment]
To be fair you are using the alpha version?

**Comment by PJB3005** [comment]
@clusterfack let's be real I'm pretty sure the "stable" version has the exact same problems.

**Comment by Acruid** [comment]
Three months later, and Godot has been thrown into the growing pile of rejected game engines.
