### ISSUE TITLE
Database Connection System

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#720]
A way to connect to an SQL database.

I'm thinking having it be a universal API so that we could either have the data be stored in an SQLite database, OR a proper server (MySQL/PostgreSQL). Maybe we can use .NET Entity Framework or whatever for this.

**Comment by Cyberboss** [comment]
Use EFCore > Entity Framwork which is netstandard iirc

**Comment by PJB3005** [comment]
@Cyberboss EFCore is still Entity Framework though is it not :thinking:

**Comment by Cyberboss** [comment]
Yeah, just the cross platform active development version

**Comment by captkirk88** [comment]
Redis

**Comment by PJB3005** [comment]
Next you're gonna recommend MongoDB.

**Comment by clusterfack** [comment]
Yeah let's use mongoDB

**Comment by elwray** [comment]
https://github.com/thangchung/awesome-dotnet-core#database
As for me the best solution - SQLite/LiteDB. The main advantages is:
- Store data in a single file.
- No additional database servers needed.

MySQL/PostgreSQL is overkill.

**Comment by PJB3005** [comment]
@El-Wray A server based database is necessary for big servers like TG so they have a central ban database.

SQLite is good because it means we can get these features to work on a local dev environment without having people set up local Postgres instances or whatever.

**Comment by Acruid** [comment]
MongoDB is web-scale, and does not use SQL or Joins, so it is high performance. Everybody knows relational databases like SQLite don't scale because they use Joins and write to disk.

In seriousness, I would set up a local SQLite database that has a shared API for now. It would cover all requirements for a small server, and allow the client to store things as well. This is what GMOD servers use, [here is the API for it.](https://wiki.garrysmod.com/page/Category:sql) If needed in the far future, server content can implement a SQL server API for whatever they want.

**Comment by optimumtact** [comment]
is it an ORM or just a connection API?

**Comment by PJB3005** [comment]
@optimumtact if you're talking about the GMOD API, it seems to be a connection API akin to BYOND's.

The reason I brought this up was because I figured using something like Entity Framework NOW might've been simple enough for SQLite and then relatively trivial to make it use Postgre later, vs having to duplicate the back end.

I also have little experience with databases so...

**Comment by Acruid** [comment]
GMOD uses a local SQLite database running in the process for its DB needs.  You still use SQL to interact with the database. IDK if this is what .Net Entity Framework does. The benefit is you don't have to set up a full SQL database system on the local machine, which works great for a small hosted server that does not need other services interacting with the database.

**Comment by PJB3005** [comment]
Entity framework is a proper ORM so it hides the SQL.

No idea whether that's a good thing or not but I assume it does mean we don't need to duplicate code.

**Comment by clusterfack** [comment]
Mongo is honestly best for a project of this scale, it's also OPEN SOURCE

**Comment by Cyberboss** [comment]
Entity Framework is a pretty good ORM as far as they come. Adding more database backends is as easy as adding a package and then generating the migration (I can add Postgres support to TGS4 if you need an example). The only issue I've ever had with it was while running concurrency tests I had a locking issue with SQLite (https://github.com/aspnet/EntityFrameworkCore/issues/9994) but that's more SQLite's implementation's fault than anything else.

Also, NoSQL DBs are terrible when scale is this small, come on guys

**Comment by PJB3005** [comment]
You're failing to see that ever since #709, SS14 has to be web scale. It embeds a web server now after all.

**Comment by Cyberboss** [comment]
Fair enough, I still think NoSQL is overkill when you're not enterprise level.

Also SQLite just isn't webscale, if you're willing to give that up (in production/high concurrency scenarios) then you'll be fine

**Comment by optimumtact** [comment]
NoSQL is terrible at any and all levels.

There are far better products that will give you SQL guarantees at scale now.

**Comment by io-june** [comment]
Like what?

**Comment by ajvsol** [comment]
> There are far better products that will give you SQL guarantees at scale. 

Citation needed. 

Also I vote for Postgres NoSQL over Mongo.

**Comment by optimumtact** [comment]
@Injazz https://en.wikipedia.org/wiki/NewSQL

CockRoach DB, Google's Spanner, Amazon Aurora Apache Ignite etc

**Comment by optimumtact** [comment]
Also Foundation DB and TiDB

**Comment by optimumtact** [comment]
In all seriousness, this is definitely something we would want, first, to manage bans across multiple servers and second to manage connection logging and other data.

Having these as viewable by our admins in a third party environment such as a webserver or other more useable environment than in the game is definitely a key issue.

Requiring admins to login to the game to review someones ban or to get round info is not ideal

**Comment by PJB3005** [comment]
Content is handling this on its own. Can be closed.
