### ISSUE TITLE
Relicense engine to MIT/MPL/LGPL?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#732]
Right now the engine is under GPLv3, while the content repo is under MIT.

Personally, I want the possibility for closed source codebases like Goon to exist. While I would of course not wish the engine to have closed source forks (or, well, forks at all, but that's besides the point), the GPL is extremely viral when it comes to linking and honestly too dangerous. Or at least I want to rule out the possibilities of GPL-related drama in the future as peace of mind.

[GNU's FAQ](https://www.gnu.org/licenses/gpl-faq.en.html) pretty much implies that under our current GPLv3 engine license, the GPL would be viral enough so that content also gets the terms of the GPL applied. This is obviously a problem with my desire to allow closed source codebases. For what it's worth, I checked the license text (but am not a lawyer) and can't see a direct mention of many of the requirements listed in the FAQ, but I still want to play it safe and avoid drama/headaches.

So, my suggestion is we re-relicense the engine to MIT or MPL (either is fine by me). This would apply to all future commits (and I at the very least would retroactively relicense my code). While this doesn't technically prevent us from getting drama'd because we still have the old code under GPL, this will still be a nice peace of mind for me personally, and if it comes to it we could later put in the effort to clean room and replace the GPL code with MIT.

Thoughts?

Edit: I can't believe I forgot about the LGPL. I believe LGPL might work great for our purposes too.

**Comment by d34d10cc** [comment]
thog don't caare

**Comment by ZoldorfTheWizard** [comment]
👍 Vote for MIT/MPL.

**Comment by hecksadecimal** [comment]
I would personally prefer the license be MIT.

**Comment by captkirk88** [comment]
I submit this proposal.

http://www.wtfpl.net/

It goes like this.

```
DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
                    Version 2, December 2004 

 Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 

 Everyone is permitted to copy and distribute verbatim or modified 
 copies of this license document, and changing it is allowed as long 
 as the name is changed. 

            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 

  0. You just DO WHAT THE FUCK YOU WANT TO.
```

**Comment by captkirk88** [comment]
It is perfect for a game like SS13.

**Comment by io-june** [comment]
👍 MIT/MPL

**Comment by io-june** [comment]
hey calling contributor gang, are you okay with relicense?
@psykzz @volundr- @harikattar @YotaXP @spoogemonster @ComicIronic @h3half @gbasood @N3X15 @Szunti @RednoWCirabrab @BGare @wixoaGit @NickPowers43 @Centronias @Cyberboss @BobdaBiscuit @patrikturi @kalanosh @digitalic @PJBot @deathrat @tkdrg @RemieRichards @DamianX @KroshkaMu @nullarmo @Serkket @SignalWalker @avghdev @UristMcDorf @theOperand @dylanstrategie @actioninja @Pangogie @johnku1 @thatrandomcanadianguy

**Comment by UristMcDorf** [comment]
I'm okay with anything that's not retardedly viral like GPL and allows for closed source/commercial use.

**Comment by h3half** [comment]
I'm good with MIT, or literally any other license.

**Comment by PJB3005** [comment]
New consideration: LGPL. It's fine for allowing closed source content repos, but the engine still has to be open (which is the perfect scenario).

**Comment by Decappi** [comment]
LGPLv3 it is then.

**Comment by d34d10cc** [comment]
Sounds good to me.

**Comment by N3X15** [comment]
Whatever license you feel is appropriate.

**Comment by Szunti** [comment]
I had only a couple of lines, which were removed since. I would be fine with your choice anyway.

**Comment by RednoWCirabrab** [comment]
I'm okay with whatever you choose

**Comment by RednoWCirabrab** [comment]
I'm okay with whatever you choose

**Comment by patrikturi** [comment]
Fine for me. I have contributed on the SFML engine, which is already replaced by Godot I think.

**Comment by NickPowers43** [comment]
I'm okay with whatever you choose

**Comment by DamianX** [comment]
I think I contributed two to three lines? Feel free to relicense them as you please.

**Comment by ghost** [comment]
Oh lawd I'm a contributer now ? Uuuh, good for me fam

**Comment by Pangogie** [comment]
Oh. I tweaked the readme once. Do whatever you see most fit.

**Comment by psykzz** [comment]
I recommend keeping away from any GPL license, LGPL isn't terrible but still requires consideration.

Ideally I'd vote for Apache, MIT or BSD

**Comment by kyrahabattoir** [comment]
Okay I know this is none of my business but, why not a GPL incompatible license? To safeguard the project from being taken over/infected by GPL additions, such as MPL 1.1

**Comment by PJB3005** [comment]
@kyrahabattoir There aren't any sane GPL incompatible licenses for software AFAIK, and I'm definitely not gonna write my myself. While yes I definitely don't want a crazed mso forking the engine as AGPL I don't think there's anything we can against that.

@psykzz We should be fine with LGPL though I can understand where you're coming from. It's basically "absolute safety but somebody can make a closed source fork", and I'm not sure which of those is better.

**Comment by kyrahabattoir** [comment]
What about merely amending an extra restriction on an existing license? I believe that's allowed, but it's efectively a different license.

**Comment by PJB3005** [comment]
@kyrahabattoir I am not a lawyer and would prefer to stay away from that kinda thing.

**Comment by PJB3005** [comment]
Something I'm reconsidering about the LGPL is the fact that it puts a distinction on static vs dynamic linking. I'm really against this because those are technical reasons that should be disconnect from the license in my opinion. While it's maybe far fetched, if we were to write all kinds of hacky inlining code manipulation for performance this could end up being problem, maybe. Again it's quite far fetched but it's an example.

**Comment by kyrahabattoir** [comment]
@PJB3005 It also seem to brush over languages/environment that simply are not capable of providing that distinction.

**Comment by PJB3005** [comment]
@kyrahabattoir the reason for this distinction is that you should be able to provide drop-in replacements of an LGPL library even if the program is proprietary. Now, you could theoretically do this by providing object files TOO so you can re-link the static binary but yeah uh... I don't think there's any program doing that and I'd rather drop LGPL libraries than deal with that.

Now granted with C# this is mostly irrelevant because of how assemblies work, but that doesn't mean it makes me personally OK with the license.

**Comment by psykzz** [comment]
Honestly MIT is the best case for me

https://tldrlegal.com/license/mit-license
> A short, permissive software license. Basically, you can do whatever you want as long as you include the original copyright and license notice in any copy of the software/source.

**Comment by Cyberboss** [comment]
I vote MIT

**Comment by PJB3005** [comment]
Since I don't want to stall this any longer, I'm just gonna go with MIT.

**Comment by PJB3005** [comment]
Done, 010d32424a1c571f54b456918c7bd9dcb33deca6
