### ISSUE TITLE
SVG Rendering?

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#734]
Does it make sense to allow direct rendering of SVGs? Godot "supports" this but SVGs are converted to bitmaps on import by the editor, so it's not true SVG rendering and scaling WILL mess it up.

A couple options here:
1. No SVG support in engine. Tell people to render the SVGs ahead of time to PNGs and load those.
2. SVGs get imported by the engine and rendered into bitmaps kinda like fonts, then render different levels of SVG sizes depending on precision needed, for GUI scaling and such. This would probably be the best:tm: solution though still kinda involved.
3. Convert SVGs to meshes and draw them as such instead of pre-rendering to bitmaps. Probably hugely overcomplicated with little gain.

**Comment by Acruid** [comment]
SVG rendering is not a priority, this feature request has been DENIED.
