### ISSUE TITLE
Remove game code, refactor to "engine" level.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#74]
Stuff like job code, antag code, etc...

There are some files and stubs related to such things all over the code, removing this kind of crap would be useful.

**Comment by ComicIronic** [comment]
What's the ultimate goal for game code? Is it going to come out of a scripting language, and if so, which one (I think Python would be good for easy scripting and OO)? Or are we going to expect people to use raw C#?

**Comment by PJB3005** [comment]
Definitely move to scripting I'd say yes.
