### ISSUE TITLE
Bus Factor is too low.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#742]
https://en.wikipedia.org/wiki/Bus_factor

**Comment by io-june** [comment]
WARNING: Sad, depressive picture
![2019-02-27 16 19 07](https://user-images.githubusercontent.com/43905364/53486753-6e8c0700-3aab-11e9-8125-75615a124b60.png)

**Comment by Cyberboss** [comment]
something something tgs

**Comment by Acruid** [comment]
The project is doing better. 👍
