### ISSUE TITLE
Implement shadow casting on Clyde.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#747]

**Comment by PJB3005** [comment]
If anybody is experienced with this and wants to implement it, I'd be glad to help make sense of Clyde to help out. 

To make the requirements more specific:

* Anything really goes, as long as it looks decent and performs decently (*cough* Godot).
* I would prefer if light maps supported HDR (is that the term) at least optionally to get nice a nice "oversaturation" effect if you have too much lights.
* Definitely gonna need a way for objects to be exempt from lighting for that sweet sweet computer and such effects.

**Comment by PJB3005** [comment]
Lighting is now implemented but shadow casting is not. Help still wanted.

**Comment by ZoldorfTheWizard** [comment]
Assigned. Created Branch.
