### ISSUE TITLE
Improve LineEdit under Clyde.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#748]
Features that are missing that kinda need implementing:

* Can't do text selection.
* Can't do copy/paste. This one's kinda icky because OpenTK does not expose a clipboard..
* Needs undo.

**Comment by PJB3005** [comment]
Pasting is now implemented on Windows and Linux, doesn't work on macOS. Oh well.

**Comment by ShadowCommander** [comment]
Another thing to add to this:
Scrolling text so that the cursor is always visible. (So that when the text entered is longer than the textbox it scrolls to the right to keep typed characters on screen.)

**Comment by tentekal** [comment]
Adding myself to this because I'm assigned to the Content one
