### ISSUE TITLE
Implement sound under Clyde.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#750]
Some considerations:

1. Should we use OpenAL via OpenTK, or should we handroll our own sound system?
2. I have literally no experience with this.

**Comment by Acruid** [comment]
I have zero experience with sound/OpenAL.

**Comment by captkirk88** [comment]
I, also, have zero experience with sound/OpenAL.

**Comment by PJB3005** [comment]
I no longer have zero experience with OpenAL aaand done.
