### ISSUE TITLE
Implement Split Containers.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#752]
Talking about `HSplitContainer` and `VSplitContainer` here.

They're not implemented yet and need to be to fix some interfaces.

**Comment by PJB3005** [comment]
They are now implemented but you can't exactly drag them.

**Comment by john1405** [comment]
Change the System.Windows.Forms.SplitContainer.BorderStyle to Fixed3D. The Splitter will look like the same you mentioned.

**Comment by PJB3005** [comment]
We aren't using winforms @john1405

**Comment by chairbender** [comment]
I need to get more experience with our UI stuff, taking this one
