### ISSUE TITLE
Re-entering a server crashes client

### ISSUE THREAD

**Issue by ScumbagDog** [space-wizards/RobustToolbox#764]
Connecting to a server, then exiting it and connecting back to it will cause the client to throw the following runtime exception:
runtime: Caught exception in GameLoop Tick: System.InvalidOperationException: We already have an overlay with ID 'EffectSystem'

**Comment by PJB3005** [comment]
Fixed in 1ff08f70efdc3947064aac4ff5a02b918b3c13f0
