### ISSUE TITLE
Move away from XML

### ISSUE THREAD

**Issue by psykzz** [space-wizards/RobustToolbox#80]
A lot of the definitions are in XML. 
Can we move to something a little cleaner? YML or even JSON?

**Comment by d34d10cc** [comment]
JSON would be best IMO.

**Comment by PJB3005** [comment]
Nah. JSON's pretty awful. It's not meant for human writing.

YML is my pick.

**Comment by ZoldorfTheWizard** [comment]
Stick to the oldies, use text files

**Comment by ComicIronic** [comment]
Can I recommend we do none of these things and have definitions as code instead? Do static configurations do anything major for performance?

**Comment by d34d10cc** [comment]
Not that I know of, but it isn't good practice and I'm pretty sure we want at least some standards to be followed.

**Comment by psykzz** [comment]
>Do static configurations do anything major for performance?

No but its make prototyping easy.

I agree though, we should focus on other things first. Just wanted to have this issue there.

**Comment by h3half** [comment]
I think we should be careful "hardcoding" things, as it just means it'll be a pain later to fix it and make the code easier to add to.

I'm not one to really talk since I'm not contributing, but I think it's important to keep the end goal in mind (SS13 but better - easy content additions are an important part of SS13). One of the things that really burned out the original dev team was having to go back and refactor huge swaths of code that they thought were already finished. So if we think we will eventually have to go back and move to a "human-readable" data format, it's probably best to just do that the first time.

Which is fairly obvious, but I just wanted to be part of the discussion.

**Comment by ComicIronic** [comment]
>No but its make prototyping easy.

What exactly do you mean? I would have thought code definitions made prototyping easier, since they would be inherently more powerful.

>but it isn't good practice

Why is this?

**Comment by psykzz** [comment]
Take an example of clothing items.
We should not have to code loading in the sprite and the name and description.

Those would be better served in a yaml file where you can quickly copy paste a similar item, update its values and point to a new sprite and good to go.

Having that defined in code, would make it easier to create special features for the clothing items, but really you should have generics and have items "turn on" the features they require via some simple flags.

**Comment by d34d10cc** [comment]
> Why is this?

Exactly because of reasons psykzz and h3half stated. Prototyping is important and this just makes it easier to do this. It is true that code definitions would allow for more control over custom functions, but this can be achieved without any or little extra effort with a separate definition system.

**Comment by ComicIronic** [comment]
> We should not have to code loading in the sprite and the name and description.

Well, we could do this the way it's currently done by DM now, which is to override initial values for common behaviour (which is basically what the XML defs do anyways) and then the loading code uses that value, but you could still override the method that does it.

>but really you should have generics and have items "turn on" the features they require via some simple flags.

Wouldn't this require that any specific behaviour then has to be put into the general code for all items? I feel like you'd end up with

```
public void do_thing() {
    if(flag_one) {
        ...
    } else if (flag_two) {
        ...
    }
     ...
}
```
rather than proper OO design of overriding the function behaviour you want.

**Comment by PJB3005** [comment]
I want to remind you that SS14 has an ECS and I can't think of a clean C# syntax way of defining component types to use off the top of my head. External prototypes bypasses that.

**Comment by ComicIronic** [comment]
How would the syntax for loading components from code be different to loading them from an external file?

**Comment by PJB3005** [comment]
Because in code you need to do it with a constructor which is kind of ugly.

**Comment by ComicIronic** [comment]
Only if you do all the loading directly in each new object - if you basically pull the XML behaviour up into the code, you're just defining constants and letting shared code do all the work. It could be as simple as 
```
public abstract class MyBaseObject {
    public string foo { get }
}

...

public class AObject {
    public string foo { get {
           return "bar";
       } 
   }
}
```

which still gives you the power of doing things yourself if need be without weird config workarounds, and the ease of a common skeleton that you just slot values into if you're not doing anything special for a new instance. In some scripting languages, this is even easier. Hell, do:

```
public class AObject : MyBaseObject {
    public AObject() {
        LoadFromFile("path/to/file");
   }
}
```
if you want.

I agree that it will be a bit more verbose, but current code has demonstrated that people eventually demand the power for new systems, and they'll get it one way or another. I think being proactive with anticipating how much people will want to do, and how static configurations wouldn't be right for the job, will save a lot of headaches in the future.

**Comment by greym0uth** [comment]
YAML is a superset of JSON, it can do everything JSON can do plus a bit more, so my votes with YAML. I also agree with the clothing example for not "hardcoding".

**Comment by ComicIronic** [comment]
The issue with avoiding "hardcoding" is that you're not actually avoiding writing stuff into code, you're just moving where it happens. The danger you have is using an external system for easy definitions, until you discover it's too weak - so you extend it, and extend it, and extend it, until you've just made a new programming language, only it's much worse than the one that you started with in the first place. 

https://en.wikipedia.org/wiki/Inner-platform_effect

There's nothing you can do with JSON, or YAML, or any static defining language, that can't be done in whatever scripting language we end up choosing for game content, or just raw C#. It just creates a system that's initally less powerful and will eventually be either replaced, or spagettified into a mess that nobody will ever want to touch. You'll see this the moment this happens:
```
my_item:
  name: "My item!"
  ...
  on_equipped: "my_function_name"
  on_unequipped: "my_other_function_name"
```

I agree that game content shouldn't be coded into the game engine - it should be loaded in a way that lets individual games specify what they want on their own. But that doesn't mean it shouldn't be in code in some form.

**Comment by greym0uth** [comment]
Perhaps we can hit two birds with one stone (#75)?

**Comment by PJB3005** [comment]
Yeah best to merge this with the other one.
