### ISSUE TITLE
Implement alternate mouse cursors.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#807]
For things such as resizing in game windows.

The problem is OpenTK does not expose the OS ones at all. I also looked at say GLFW, and while it does expose some, it doesn't expose all (notably, diagonal resize, because macOS does not document having it, even though it does have it, thanks Apple).

So we have two options here:

1. Draw our own mouse cursors and use them via OS hardware cursors.
2. Switch to GLFW for windowing and simply don't have a diagonal cursor.

Which.. is more preferable?

**Comment by io-june** [comment]
use CC-licensed cursors, you don't even need to draw anything

**Comment by tentekal** [comment]
After taking a look at OpenTK further, I think we should go into GLFW for windowing, it's a hell of a lot easier and cleaner for this feature. No idea how difficult it would be to convert it though.

**Comment by PJB3005** [comment]
Well I'll be glad to let you know that as of 52e5afd27736f6485c068b3e619fa355b2323ab7 we *are* using GLFW for windowing and that with https://github.com/glfw/glfw/issues/427 GLFW 3.4 will have support for all the cursors we could need.

**Comment by tentekal** [comment]
Nice, I got this idea from looking in OpenTK and seeing the cursor updates you pushed. This will be super useful for those RTS-like cursor indicators we talked about forever ago.

**Comment by PJB3005** [comment]
For RTS-like cursor indicators it's probably better to just manually draw at the cursor position, because you can't really sanely render them to the OS.

**Comment by tentekal** [comment]
I think GLFW supports small images, and animations wouldn't be necessary (would be pretty awful for trying to click fine detail). At the very least a cursor-recolor would be sufficient.

**Comment by PJB3005** [comment]
Yeah but if you want to display something like a count next to your cursor you're out of luck.

**Comment by PJB3005** [comment]
Done by 832a4e01f1fca7280ce94d973f554f5a8c8bf8e4
