### ISSUE TITLE
Rendering segfault on OSX

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#81]
https://pastebin.com/m5hcMJAd

Everything works, until you hit ready in the lobby. You can see for what I assume is a frame or two before the segfault happens.

![](https://cdn.discordapp.com/attachments/281851282166251520/308686695627227148/unknown.png)

Screenshot taken by breakpointing in Xamarin before the crash happens.

Trying to step through with a breakpoint seems to have the crash happen completely at random, somewhere in network manager code during cluwnelib idle. Maybe the GC is causing SFML.NET to do something during the debugging and that thing in SFML.NET is the issue?

**Comment by BobdaBiscuit** [comment]
Remove sfml remove sfml

**Comment by PJB3005** [comment]
This can be fixed by upgrading to SFML 2.4.
