### ISSUE TITLE
Redesign UI Input Handling

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/RobustToolbox#838]
Redesign input handling so that keyboard and mouse inputs act the same.

This will allow keyboard presses to activate any controls under the mouse, as well as make it easier to change keybinds.

KeyboardKeyEventArgs from OpenTK do not have mouse position info, so the information needs to be stored from MouseMoveEventArgs somehow.

There's also a bunch of variables that seem to be leftover from Godot that look like they can be removed.

**Comment by PJB3005** [comment]
> KeyboardKeyEventArgs from OpenTK do not have mouse position info, so the information needs to be stored from MouseMoveEventArgs somehow.

FWIW, OpenTK 4 will use GLFW and GLFW doesn't pass mouse data to mouse button events either, so either way that information will be derived anyways.

I do wish the UI system would use the input manager, so we could use key bind maps correctly for a bunch of UI interactions (think shortcuts like copy paste).

**Comment by ShadowCommander** [comment]
The current plan is to have MouseMove check for controls under the cursor and set a variable. MouseDown and KeyDown when fired will take that value and pass it to the relevant functions.

MouseMove already checks for controls, so it shouldn't be too hard.

I've been looking at KeyEventArgs and the OpenTK KeyboardKeyEventArgs and it includes Alt, Ctrl, and Shift bools as well as Modifiers as a bitwise combination of KeyModifiers. It also has the ScanCode of the key that triggered the event. Currently KeyEventArgs stores Alt, Ctrl, and Shift. Should Modifiers and/or ScanCode be added?

**Comment by ShadowCommander** [comment]
Here's a list of keybinds that we should eventually have. These are the internal names and the temporary keybinds they are currently set to:

- ShowDebugMonitors: `F3`
- HideUI: `F4`
- MoveUp: `W`
- MoveLeft: `A`
- MoveRight: `D`
- MoveDown: `S`
- Run: `Shift`
- ShowEscapeMenu: `Escape`
- FocusChatWindow: `T`
- EditorLinePlace: `MouseLeft`
- EditorGridPlace: `MouseLeft`
- EditorPlaceObject: `MouseLeft`
- EditorCancelPlace: `MouseRight`
- EditorRotateObject: `MouseMiddle`
- SwapHands: `X`
- Drop: `Q`
- ActivateItemInHand: `Z`
- OpenCharacterMenu: `C`
- ExamineEntity: `MouseLeft`
- UseItemInHand: `MouseLeft`
- ActivateItemInWorld: `E`
- ThrowItemInHand: `MouseLeft`
- OpenContextMenu: `MouseRight`
- ToggleCombatMode: `Tab`
- OpenCraftingMenu: `G`
- OpenTutorial: `F1`
- OpenInventoryMenu: `I`

### Partially implemented:
Keys have functionality, but they do things based on hardcoded keys instead of going through the InputManager. Keybind names are WIP.

- ShowDebugConsole: `~`

LineEdit

- CursorLeft: `Left`
- CursorRight: `Right`
- Backspace: `Backspace`
- SubmitText: `Return` or `NumpadEnter`
- Paste: `Ctrl + V`
- Copy

DebugConsole

- InputHistoryPrev: `Up`
- InputHistoryNext: `Down`
- ScrollToBottom: `PageDown`

ChatBox

- ReleaseKeyboardFocus: `Esc`
- InputHistoryPrev: `Up`
- InputHistoryNext: `Down`

### Things that are not implemented yet:

- Grab/Drag
- Resist
- Target Doll/Targeting whatever it happens to be later on
