### ISSUE TITLE
Minimization crashes the game

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#841]
At least on Windows I think, it causes the window size to be set to 0,0. So when it goes to create the lighting framebuffer, it'll try to create a framebuffer with attachments of size 0,0. This is invalid in OpenGL so...

**Comment by Acruid** [comment]
To reproduce:
* Be Windows
* Collapse the game window
* Watch the explosions

![image](https://user-images.githubusercontent.com/1685952/64207113-ce93a980-ce50-11e9-8c62-df80e6bb8f7a.png)
