### ISSUE TITLE
Secure Server Info Protocol

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#882]
We need a properly secure protocol for fetching info from the server before doing a full connect.

This info is necessary to download the content pack so that a proper connection to the server can be made. Ideally this info should be sent *securely*.

For most public servers, this can be delivered over HTTPS without any other issues. For self hosted servers however, this cannot be, since people won't have proper certificates for their home IP address.

Is there an alternative method that can be used to ensure a secure connection for these self hosted servers? Is it possible to, for example, use the auth server to create a secure connection here?

**Comment by N3X15** [comment]
Self-signed certs may be an option for SSL connections.

For LAN/loopback connections, you may want to just leave it unsecure since it's highly unlikely your neighbor is going to be trying to MITM your spessman sprites.

**Comment by elwray** [comment]
To distribute content better to use torrents or something like IPFS.

**Comment by PJB3005** [comment]
Torrents/IPFS are indeed a neat possible solution to distributing the content pack, but the problem still remains that we should try to securely get a hold of the torrent data, somehow.
