### ISSUE TITLE
Improve launcher connection dialog in engine.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#890]
With the new launcher, the main menu is not shown. This is because the launcher is responsible for both account management and server selection. When the launcher starts the client, it passes `--launcher`, `--connect-address` and `--username` as command line arguments for this instead.

The client instead goes into a very basic "connecting" dialog. This dialog is in fact so basic that it doesn't even say anything if the connection fails.

This should be improved.

The code for this is in `LauncherConnecting.cs`

**Comment by gradientvera** [comment]
Was this closed by https://github.com/space-wizards/space-station-14/commit/45e9be43ef8f384f17c0059c03d1ab42813b0714?

**Comment by PJB3005** [comment]
Yes
