### ISSUE TITLE
Implement a TimerComponent

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#894]
This component would handle timers on entities. It would listen to things such as pausing the entity, and correctly use simulation timing (unlike the current timer manager). Also timers would just stop if the entity were deleted.

Example usages of this would be the airlock component, it would register a timer with the timer component, so if the map gets paused or the airlock gets deleted, it gets transparently handled.

**Comment by DrSmugleaf** [comment]
Done in https://github.com/space-wizards/RobustToolbox/pull/1358
