### ISSUE TITLE
Higher level RPC netcode.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#895]
Right now if you want to send a message to the other end of the wire you have to do all kinds of shit like manually registering net messages and handling them.

Proposed idea: you make some interface in shared, on the receiving end you implement this interface like any other, on the sending end you get an auto-generated "implementation" that handles all the net messages and serialziation for you.

So uhhhh, example code:

```cs
// Client -> server

public interface IFoo
{
	void Hello(IPlayerSession sender, string message);
}

// Client

IFoo NetApi = /* something */
NetApi.Hello(null, "hello there!");

// Server

// Uhhh register this somehow?
internal sealed class Foo
{
	public void Hello(IPlayerSession sender, string message)
	{
		Console.WriteLine("{0} sent {1}", sender.SessionId, message);
	}
}
```

**Comment by Acruid** [comment]
Can there be more than one static instance of Foo? If the server has two instances of Foo, how does the networking determine which instance to call the function on?

You are basically trying to remotely invoke a method on a class instance, so there needs to be a way to reference said instance without using a memory pointer. The existing networking gets around this by making all RPC calls static, so you don't need to resolve a `this` memory pointer to invoke the method on the other peer.

**Comment by PJB3005** [comment]
The idea is that you'd get/register the `IFoo` instance with context related to what you're doing. So like for a component the "other side" would be magic'd to the component on the other side of the wire for this entity UID.

**Comment by Acruid** [comment]
EventBus now takes care of networking, and we are not doing networked interface events for components.
