### ISSUE TITLE
Contribution Guide?

### ISSUE THREAD

**Issue by greym0uth** [space-wizards/RobustToolbox#90]
I was wondering if I should work on a contribution guide: setting up project, building, testing, etc.. I just wasn't quite sure what should all go into this. Maybe I could get some insight as well as things I need to make sure I take into account?

**Comment by PJB3005** [comment]
As for building you just download the project, install Visual Studio or Xamarin, open the solution and hit run and you should be good.

Testing is, well, nothing special.

**Comment by greym0uth** [comment]
Alright, I was thinking of going into helping people just starting out with contributing to this repo, it's a bit of a challenge and takes a bit of time to figure out. I was thinking of maybe creating a diagram or something along those lines.

**Comment by ComicIronic** [comment]
I'd be in support of it. All good repos have Getting Started guides, and it would be a better fit for the README.

**Comment by ZoldorfTheWizard** [comment]
I have enabled the wiki on this project, feel free to add stuff to it

**Comment by greym0uth** [comment]
Awesome I'll get to work on this!

**Comment by clusterfack** [comment]
This was our temp project guide when we were getting ready, some of the info is already outdated even
https://docs.google.com/document/d/1qWvY3ix8RTnYcGGNnG0rxJjclub96dQBlBzjgNoBaFQ/edit

**Comment by Pangogie** [comment]
We seriously need a guide.
If you guys are serious about getting it done this time we're going to need a big set of guides and documents on what every modules does and what the actual plan for the game/engine is. I would love to help, but I cannot find enough information without digging through all the code.

**Comment by PJB3005** [comment]
Personally I think having a brief overview of all the modules and important services, then doc comments for the rest is good.

But yeah we need a guide.

**Comment by Pangogie** [comment]
The [Getting Started](https://github.com/space-wizards/space-station-14/wiki/Getting-Started) page in the wiki now gives a decent idea on how to start contributing.
Make sure to join us in `#documentation` on [Discord](https://discord.gg/t2jac3p) to help the documentation crew.

**Comment by Acruid** [comment]
The Getting Started page on the Github wiki has been made and is correct. Issues #240, #242, and #249 go into depth on what needs to be added to the documentation. The rest of this issue is pretty much summarized as "Write all the documentation for all the things." Please make a new issue on a specific topic you want added or changed in the existing documentation. Closing this because it is way too broad.
