### ISSUE TITLE
Need a way to display a SpriteComponent at different orientations in the same frame

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#905]
This is necessary for being able to do stuff like rendering an area of a camera into a UI element for example. This is also necessary to fix https://github.com/space-wizards/space-station-14/issues/474

The problem is that state of playback for animations and such in a sprite components depends on the camera orientation, so drawing a single sprite at two locations with a different orientation is kind of impossible.

My current idea, that I got while writing this issue, is to fold all per-direction animation times into a single set of animation delays by duplicating frames where necessary. This would make it possible to simplify animation playback state in the `SpriteComponent` so that it is independent from the orientation the sprite is perceived at. If we then pull the exact texture in `Render` instead of `FrameUpdate`, we should not see a significant performance decrease.

**Comment by Acruid** [comment]
Drawing non-`Directional` sprites with a different view should be trivial. You can already easily do this in Clyde by just modifying the view matrix of the Eye.

The total length of each animation should be a fixed value, which is completely independent of where the Camera is. For a 3D model this is an intrinsic property, with the added property that the spacing between the keyframes is also independent of the camera orientation (normally you don't make separate animations in a 3D model for being viewed from various directions). We don't have the second restriction in 2D, so you *can* allow the keyframes of the RSI animation to be placed at a different % of the total time on a per-direction basis, but don't have to.

So yeh, pretty much what you suggested.

I'm thinking of something like
`static void RenderRSI(DrawingHandle drawingHandle, RsiInstance rsi, Matrix3 worldMatrix, Angle viewRotation)`
would be useful, you could call it from anywhere and be able to get a RSI drawn at any location for any given camera rotation to the drawing handle. Pretty much a modified version of the current `SpriteComponent.OpenGLRender`.
