### ISSUE TITLE
Remove ScrollBar width when children fit inside

### ISSUE THREAD

**Issue by ShadowCommander** [space-wizards/RobustToolbox#911]
It would be nice if the ScrollBar disappeared completely and allowed its children to expand into that space when the children fit inside the Container.

For example when you have a web page where all the content fits inside the browser, then there aren't an scroll bars and the content expands to all the edges. When resizing and the content doesn't fit any more then the scroll bar pops up and moves the content slightly to accommodate the scroll bar.

Currently ours always has the content moved over to accommodate the scroll bar even when the content fits.

I'm not sure how to accomplish this right now since the ScrollBar isn't the container that holds the content. How it is used right now is: ScrollBar -> VBoxContainer -> Buttons.

**Comment by pratap424** [comment]
Why don't you add meta tag that
-<meta name="viewpoint" content="width-device-widht , initial-scale=1.0">

To your html code.

**Comment by PJB3005** [comment]
@pratap424 we... aren't using HTML.

**Comment by branDPatl** [comment]
Lili ½°º³

**Comment by Qeeq777** [comment]
https://www.qeeq.com/a/mcs18596

**Comment by io-june** [comment]
guys i think these are not actually real people
don't click links
