### ISSUE TITLE
Map Loader may not be able to write/read full maps anymore.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#920]
While the map loader can write/read *blueprints*, full maps (multiple grids) aren't gonna work I don't think.

Right now, default grids will definitely be an issue. Otherwise it *might* work but I doubt it. We need to verify this works.

**Comment by PaulRitter** [comment]
this was fixed(?)

**Comment by SweptWasTaken** [comment]
Looks like chairbender fixed it.
