### ISSUE TITLE
Ensure sprite animations always play for SpriteViews

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#922]
I made `SpriteSystem` not update sprite animations for sprites outside the view box, for performance.

This doesn't take `SpriteView` into account, so if you have a `SpriteView` to an entity, and you move that entity out of your view, animations will stop.

**Comment by Acruid** [comment]
Fixed in https://github.com/space-wizards/RobustToolbox/pull/2181
