### ISSUE TITLE
Parallax space is too small / needs automatic rescaling or tiling

### ISSUE THREAD

**Issue by ghost** [space-wizards/RobustToolbox#935]
![image](https://user-images.githubusercontent.com/10257081/72846599-e7b9bd00-3c6e-11ea-8e59-7281bffd2984.png)

Noticeable when making game window full size on a large monitor

**Comment by Moneyl** [comment]
Matching issue on the content repo is [#339](https://github.com/space-wizards/space-station-14/issues/339).

**Comment by PJB3005** [comment]
Parallax is purely a content issue so closing this as duplicate.

**Comment by ghost** [comment]
oops, wrong repo. didn't realize i was on robust
