### ISSUE TITLE
Exceptions during entity init should delete entity automatically.

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#949]
Right now if *something* goes wrong while an entity is being created, it'll leave an uninitialized entity inside the entity list. This is really problematic because it creates a ton of fun exceptions down the road. Probably best to pass the exception through but make sure the entity is marked as deleted.

**Comment by ComicIronic** [comment]
Looks like you fixed this #996 .

**Comment by PJB3005** [comment]
Indeed it was.
