### ISSUE TITLE
Client should handle already being connected gracefully

### ISSUE THREAD

**Issue by Moneyl** [space-wizards/RobustToolbox#958]
If you try to connect to the server when you're username is already connected the client throws an exception and crashes. Instead it should throw you back to the main menu and tell you why. Interestingly this even happens sometimes if you disconnect and reconnect with the same username. [Relevant code](https://github.com/space-wizards/RobustToolbox/blob/5d37780f4ee7d09b2101d1f809de20b11e76cba5/Robust.Shared/Network/NetManager.ClientConnect.cs#L34).

**Comment by Acruid** [comment]
Cannot reproduce, assumed fixed. Currently when joining a server with duplicate usernames, the second client has his username suffixed with a number.
