### ISSUE TITLE
You move slower when diagonally moving against a wall.

### ISSUE THREAD

**Issue by BobdaBiscuit** [space-wizards/RobustToolbox#96]
When your direction is corrected from diagonally moving into a wall the speed is slower than if you just walk in one direction manually.

**Comment by d34d10cc** [comment]
I am pretty sure that is intended behaviour.

**Comment by psykzz** [comment]
I dont know about intended, its intended code wise, but we should be helpful and assume that you want to move that way at full speed.

**Comment by ZoldorfTheWizard** [comment]
🤡
