### ISSUE TITLE
The great Enum Space Waste of 2020  (aka why are enums not byte sized)

### ISSUE THREAD

**Issue by moonheart08** [space-wizards/RobustToolbox#973]
This is probably of importance to networking in particular:
Enums default to `int` sized. It is highly likely that *every single enum in the codebase* should be `byte` sized for network savings.
Using up a byte of space is better than using 4 and depending on the compressor to handle the 3 extra zero bytes.

**Comment by Moneyl** [comment]
Good idea. I can't think of any SS14 enums that are even anywhere near 256 values. If we do this we should probably check if it makes any difference with networking/performance/memory usage to see if it's worthwhile.
