### ISSUE TITLE
Collision layers need to be human readable

### ISSUE THREAD

**Issue by ghost** [space-wizards/RobustToolbox#974]
They're bitflags serialized as decimals and there's no apparent definition for which layer is which bit at the moment. Probably should be defined as a list of strings in the YAML and converted to the bitflag on serialization.

**Comment by ghost** [comment]
Okay, turns out there's definitions for which bitflag corresponds to which layer in the content repo but they're only used internally for a few things so the issue of the YAML being a pain to read still stands.

**Comment by PJB3005** [comment]
It could be good if `enum.` syntax in YAML applied to int fields. Then you could refer to the correct layers from content.

**Comment by moonheart08** [comment]
Not 100% familiar with yaml, but couldn't you use a list of those enums and then convert to bitflags in code?

**Comment by PJB3005** [comment]
The annoying problem is that the layers are defined in content (as they should be) so there has to be some way to wire up which content enum is responsible for layer names.

Then again I suppose that's more a case of "somebody has to write some glue" and it's not the end of the world to implement manually.

**Comment by ComicIronic** [comment]
@PJB3005 I shouldn't have marked this as auto-close, since it's not actually implemented.
