### ISSUE TITLE
Building Walls Next to Player Mob causes player to be stuck on wall.

### ISSUE THREAD

**Issue by Auri3l** [space-wizards/RobustToolbox#982]
Hello, the bug is very easy to recreate, stand real close to a wall while building with steel in hand and you'll get stuck into it. Image available below.

![image](https://user-images.githubusercontent.com/8057918/74595787-efdeff80-5056-11ea-9bc5-823c995e3c46.png)

**Comment by ShadowCommander** [comment]
This is because we don't have collision resolution, which means when things collide, they don't try to not collide anymore. The same thing happens when using a Medical Scanner. space-wizards/space-station-14#385
