### ISSUE TITLE
Update GLFW

### ISSUE THREAD

**Issue by PJB3005** [space-wizards/RobustToolbox#986]
GLFW we're shipping is outdated right now, this means `glfwGetKeyName` is broken on Linux/X11.

**Comment by gradientvera** [comment]
Is this still an issue?

**Comment by PJB3005** [comment]
Does the key binding menu correctly report key names when you start the game with different keyboard modes?

**Comment by gradientvera** [comment]
seems fixed
![image](https://user-images.githubusercontent.com/6766154/125291949-3e62fd00-e322-11eb-9e39-ee3976c06428.png)
